### ISSUE TITLE
Add exclusivity to simple-opening-hours

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#202]
We use this library https://github.com/mfdz/simple-opening-hours to calculate opening hours but there is a feature missing.

The string `00:00-24:00; Tu,Sa 02:00-14:30 off;PH 00:00-24:00` means that it's open 24/7 but not on Tuesday and Saturday from 2-14:30. So basically the same as `Mo,We,Th,Fr,Su 00:00-24:00; Tu,Sa 00:00-02:00, 14:30-24:00; PH 00:00-24:00`.

Acceptance criteria

- Add a test for this string. Should give the same results as this: https://github.com/mfdz/simple-opening-hours/blob/master/test/parser.tests.js#L103-L116
- Adjust code in library to take this into account.
- Write more tests with various combinations.

Notes:
- It's probably not easy to do this, so don't worry if it takes time.
- The project is written in typescript, so you have to run `npm run compile` before `npm test`.

**Comment by Beck-berry** [comment]
Can we say it for sure that the first part of the string will be the universal opening hours and then comes the restriction? Or shall we suppose that time without days (like `00:00-24:00;`) can occur anywhere in the string?

**Comment by leonardehrenfried** [comment]
We have to be paranoid, so everywhere.

**Comment by leonardehrenfried** [comment]
And can you please also add a github actions workflow to the repo?

**Comment by Beck-berry** [comment]
I'm not sure about the edge cases but it handles very well if there is one given time off. I'm thinking whether it is likely to have something like `tu 10:00-11:00, 13:00-14:00 off`, when there are more than one "closing hours".

**Comment by leonardehrenfried** [comment]
That wouldn't make much sense anyway, but just add a test to make sure.
