### ISSUE TITLE
iPad: Feedback button covers hamburger menu when in landscape mode

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#209]
A customer reports that the red feedback button covers the hamburger menu in the top right corner.

I can reproduce this when setting my Firefox into iPad mode (in the developer tools).

![Screenshot from 2020-05-19 14-34-38](https://user-images.githubusercontent.com/151346/82327022-0ee68800-99de-11ea-926c-087adee067e4.png)

Acceptance criteria:

- Move the red feedback button a little bit to the left so that it's between the language switcher and the hamburger menu.

**Comment by meromisi** [comment]
I moved it but there's no hamburger menu under the feedback button so I guess something else is the issue here.

**Comment by meromisi** [comment]
Actually we think its working fine in the menu there are items which can be found at the bottom of the page in landscape mode(so no need for hamburger menu).

**Comment by leonardehrenfried** [comment]
You are totally right! We really should have known this ourselves.

/cc @hbruch
