### ISSUE TITLE
Bus icons are shown for trains in overview

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#211]
![Screenshot_2020-05-21-05-50-53](https://user-images.githubusercontent.com/151346/82521473-0f3e6a80-9b27-11ea-9513-d9e74389ae0d.png)

The route above doesn't contain any bus routes but the bus icons are shown. Please use the normal dots for non-bus stops.

**Comment by leonardehrenfried** [comment]
Had to revert your commits so you have to unrevert on your branch.

**Comment by meromisi** [comment]
no need for that I didn't like that solution anyway. I could solve it other way now it seems to be working fine.
![image](https://user-images.githubusercontent.com/54352878/82542427-3f4f3300-9b52-11ea-8046-d7bcc2777aa5.png)
![image](https://user-images.githubusercontent.com/54352878/82542438-44ac7d80-9b52-11ea-9629-b0d8c10c62f5.png)
