### ISSUE TITLE
Write script to extract bike shops from OSM regional extracts

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#213]
Right now we occasionally get the bike shop data from overpass. We would like to to get much more data and in order to switch to downloadin the raw OSM data and extracting the information from it.

Write a (bash) script that does the following:

- Download the OSM extract from http://download.geofabrik.de/europe/germany/baden-wuerttemberg.html
- Use osmium (https://docs.osmcode.org/osmium/latest/) to extract the bike shop data and convert it to GeoJson.
- Commit the script to https://github.com/mfdz/digitransit-ansible/tree/master/roles/thingsboard-to-parkapi/templates

Note: Use the the subcommands `tags-filter` and `export`.

**Comment by Beck-berry** [comment]
What name would you prefer for the script?
