### ISSUE TITLE
Add info text to bicycle service stations

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#215]
![Screenshot from 2020-05-25 10-09-20](https://user-images.githubusercontent.com/151346/82792569-e17f5b80-9e6f-11ea-96db-69c0ee7be710.png)

The are currently out of order.

The info text should read:

de: "Derzeit nicht in Betrieb – voraussichtlich Anfang / Mitte Juni mit verbessertem Angebot wieder verfügbar – ggf. mit leicht geändertem Standort"
en: "Currently out of order. The service will resume in June, possibly at a slightly different location."

**Comment by Beck-berry** [comment]
![Screenshot_2020-05-25_11-18-18](https://user-images.githubusercontent.com/46535522/82798905-7cc8fe80-9e79-11ea-95b5-25c80c0d14db.png)
![Screenshot_2020-05-25_11-18-32](https://user-images.githubusercontent.com/46535522/82798907-7d619500-9e79-11ea-8729-023265f47e1c.png)
