### ISSUE TITLE
Update simple-opening-hours version in digitransit

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#221]
@Beck-berry has added new features to the lib but it's not actually used yet.

Please change the version in package.json test the app.

**Comment by Beck-berry** [comment]
Seems to be working fine.
![Screenshot_2020-06-01_09-26-53](https://user-images.githubusercontent.com/46535522/83385755-13ea0500-a3ea-11ea-8d3d-81d44c2fb32d.png)
