### ISSUE TITLE
Public transport routing not adjusted to streets/rails of OSM tiles

### ISSUE THREAD

**Issue by mahlzahn** [stadtnavi/digitransit-ui#222]
Depending on the zoom level the misalignment can be 50m or 500m …, see e.g. [here](https://herrenberg.stadtnavi.de/reiseplan/Weinbergstra%C3%9Fe%2044%2C%2071083%20Herrenberg%3A%3A48.58003877321969%2C8.84221137035619/Waldkindergarten%20Nufringen%2C%20Wengert%2C%2071154%20Nufringen%3A%3A48.616460751195184%2C8.89683168287086?mapMode=default&modes=BUS%2CRAIL%2CSUBWAY%2CPUBLIC_TRANSPORT&optimize=TRIANGLE&safetyFactor=0.4&slopeFactor=0.3&time=1590858282&timeFactor=0.3)
![Screenshot_2020-05-30_19-07-04](https://user-images.githubusercontent.com/6549824/83334829-65d74180-a2a9-11ea-81db-17180429ef95.png)

**Comment by leonardehrenfried** [comment]
Hi, thanks for reporting this and welcome to the repository!

I have just deployed a fix to correct this. Could you please check it out again?

**Comment by mahlzahn** [comment]
Hi, thanks. Now it works! Although I probably will never use it in Herrenberg, just saw the project interview on [netzpolitik.org](https://netzpolitik.org/2020/eine-mobilitaetsplattform-fuer-alle) …
