### ISSUE TITLE
Self-host Google fonts

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#226]
A user has complained that we are using Google Fonts. They have a point: we are doing a lot to not have any dependency on Google but the font allows it to still track our users.

For this reason, please remove the HTTP call to `fonts.googleapis.com` and replace it with the self hosted version  the fonts we use. Here is a tool to help you do it: https://google-webfonts-helper.herokuapp.com/

I think the fonts we use are "Lato" and "PT Sans Narrow".

**Comment by hbruch** [comment]
<img width="528" alt="grafik" src="https://user-images.githubusercontent.com/2187389/122675833-838c8700-d1db-11eb-820d-4260238ec2d3.png">

DT-next again uses google fonts. Changes to self-host them need to be adapted.

**Comment by leonardehrenfried** [comment]
@Beck-berry I noticed that DT2 requires different fonts.

## Prod
![Screenshot from 2021-06-22 16-52-14](https://user-images.githubusercontent.com/151346/122947867-c59fff00-d37a-11eb-903e-8816b80a3b2e.png)

## Dev
![Screenshot from 2021-06-22 16-52-08](https://user-images.githubusercontent.com/151346/122947871-c6389580-d37a-11eb-8bee-beae1819bad3.png)

Can you create another PR, remove the current fonts (Lato) and use [this tool](https://google-webfonts-helper.herokuapp.com/fonts) to get just Roboto and Roboto Condensed as specified in the Google Fonts URL?
