### ISSUE TITLE
Move parking back into its own layer

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#227]
Users have complained that they cannot find the parking information.

A few weeks ago we combined the carpool parking spaces and the ordinary parking spaces into a single layer. It seems that people cannot find it.

Please revert the change and make it two separate layers again. Also enable the parking spaces by default.

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-09_11-13-21](https://user-images.githubusercontent.com/46535522/84129454-42975980-aa42-11ea-8019-95fcd89d160b.png)
