### ISSUE TITLE
Investigate why we don't see the bus/train logo in the departure board

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#229]
https://reittiopas.hsl.fi/linjat/HSL:31M1/pysakit/HSL:31M1:0:01?sort=no shows you the train next to the times in the route view.

![Screenshot from 2020-06-09 09-57-53](https://user-images.githubusercontent.com/151346/84121749-d7488a00-aa37-11ea-9668-51efe7ad515a.png)

However, in Herrenberg we don't see this: https://herrenberg.stadtnavi.de/routen/hbg:10-1-j20-29/haltestellen/hbg:10-1-j20-29:0:08?sort=no

![Screenshot from 2020-06-09 09-59-58](https://user-images.githubusercontent.com/151346/84121909-ffd08400-aa37-11ea-9eb9-fd4b6c79e663.png)

Please investigate why that is.

Avenues to explore:

- do we need the realtime vehicle position for this to work?

**Comment by Beck-berry** [comment]
Must be because `vehicle` in RouteStop.js is null. <- Because `vehicles` in RouteStopListContainer is an empty object. <- It should be retrieved from the RealTimeInformationStore - and we have this file identical to the HSL version.

**Comment by leonardehrenfried** [comment]
I'd say that's because HSL has the real time position of their trains and busses and we don't.

However, it should be possible to infer this information, shouldn't it. We don't need the actual position but the 2 stops it is in between.

**Comment by leonardehrenfried** [comment]
Could you give yourself a time box of 2 hours and explore how hard it would be to fake this data? We can already see the "jump" in times in the UI. Shouldn't it be possible for the app to figure out where to draw the vehicle even without the real time position?

**Comment by Beck-berry** [comment]
Originally the icon is a link which would need different data of the vehicle (id, route, destination..) - can we skip this functionality and only display a "plain" icon?

**Comment by leonardehrenfried** [comment]
Absolutely.

**Comment by leonardehrenfried** [comment]
Everything that makes this display less confusing is a win.

**Comment by Beck-berry** [comment]
Seems good :)
![Screenshot_2020-06-10_08-43-44](https://user-images.githubusercontent.com/46535522/84237635-00315380-aafa-11ea-8a8c-24310c55816e.png)

**Comment by leonardehrenfried** [comment]
Nice! 

How did you calculate the position?

**Comment by Beck-berry** [comment]
I only check if the departure time of the next stop is smaller than the previous one.
