### ISSUE TITLE
Fix translation

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#236]
The following translation in this page is incorrect: https://mih.mitfahren-bw.de/routen/hbg:10-1-j20-29/haltestellen/hbg:10-1-j20-29:1:11?sort=no

![Screenshot from 2020-06-10 11-19-10](https://user-images.githubusercontent.com/151346/84250719-b1d98000-ab0c-11ea-895a-91205c4aafb5.png)

Instead of "bis um 14.6." it should just say "bis 14.6."

Acceptance criteria
- Find translation in one of the subprojects (not sure where exactly but not the main translations) and translate it
- Upstream the change

**Comment by Beck-berry** [comment]
[PR](https://github.com/HSLdevcom/digitransit-ui/pull/3325) is right there!

**Comment by leonardehrenfried** [comment]
Lets keep this ticket open until they've merged it.

Afterwards you can merge their master and create a PR.
