### ISSUE TITLE
Add "Nette Toilette" to OSM

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#240]
"Nette Toilette" is scheme for open access to toilets.

In preparation for a GeoJson layer, please add the toilets in the following PDF to OSM.

[Herrenberg_NetteToilette_2018_DRUCK 1mm Anschnitt.pdf](https://github.com/stadtnavi/digitransit-ui/files/4771509/Herrenberg_NetteToilette_2018_DRUCK.1mm.Anschnitt.pdf)

## Acceptance criteria
- If you don't have one, make an OSM account.
- Check that the toilets in the PDF are already in OSM.
- If they aren't, then add them to the map. https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets has information about how to tag toilets.

**Comment by hbruch** [comment]
First thing we need agree on a mapping schema.
In 2011, it was already discussed in the [German OSM forum](https://forum.openstreetmap.org/viewtopic.php?id=14505), without a final decission. I think, things have settled for now and are sufficiently well described in the wiki.

General mapping scheme [amenity=toilets](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) with `access=yes` or `access=permissive` is appropriate if they are more or less standalone, e.g. a proper building or street-accessible entry or have a specific location e.g. in a larger building. For toilets in places, see the corresponding section in the wiki as well.

In addition, please tag `toilets:scheme=Nette Toilette`, which is an emerging tag which is [already in use](https://taginfo.openstreetmap.org/tags/toilets%3Ascheme=Nette%20Toilette).

**Comment by meromisi** [comment]
I uploaded the points from the PDF to OSM, could someone check it out?

On overpass this is how they looked like:
![image](https://user-images.githubusercontent.com/54352878/84756049-99f97480-afc2-11ea-9383-f01262d9ee3b.png)

**Comment by hbruch** [comment]
Where does the classification unisex=yes come from? In the flyer I see no such info.
Could you check again all entries for spelling issues, e.g. https://www.openstreetmap.org/node/2887846588#map=19/48.60283/8.90302 : It's Hildrizhauser Straße, tag name is toilets:scheme not toilets:cheme.

**Comment by leonardehrenfried** [comment]
Can you share the link to the overpass query?

**Comment by meromisi** [comment]
I thought unisex meant that there were toilets for both genders if you want I can remove them. 
overpass query: https://overpass-turbo.eu/s/V7T
About the wheelchair accessibility: whats the difference between `limited` and `yes` and which one should be appropriate? I couldn't find anything about it in the pdf.

**Comment by hbruch** [comment]
http://overpass-turbo.eu/s/V7S shows all `amenity=toilets` and nwr with `toilets` key. Not all of them participate at Nette Toilette, so we should only list those with toilets:scheme=Nette Toilette.
Waldseilgarten and Mauerwerk participate (according to city staff) also now, but are not listed in the flyer. I asked them to provide additional infos concerning their features.

unisex, as written in the wiki, means gender neutral toilet (one for both sexes). The flyer instead says they have explicitly toilets for each sex, so we instead should use male=yes/female=yes, if at all.

If a wheelchair is depicted in the flyer, I'd set to yes, if not an editor before already set wheelchair=limited. Limited is chosen, if their are some obstacles, which can be surmounted (see https://wiki.openstreetmap.org/wiki/Key:wheelchair). We should only tag this for `amenity=toilets`. If `toilets=yes` is tagged (when toilets are part of a place), we should tag [toilets:wheelchair=yes](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Toilets_within_places).

**Comment by leonardehrenfried** [comment]
Note for the administrators of Nette Toilette:

- Naturfreundehaus ist listed as wheelchair-accessible on the flyer but a wheelmap user said it isn't: https://www.openstreetmap.org/node/2887846588/history
- The toilet at Eiscaffe Piazza is listed as "Zugangsrampe (Länge 26m/Neigung 9%)" in the flyer. Correct me if I'm wrong but I would tag this as limited.

**Comment by leonardehrenfried** [comment]
@meromisi I'm afraid I'm going to have to ask you to rework the OSM entries.

If the toilets are part of an already existing business/building then they need to be added to that. They should only be a separate node (point) if they are a standalone, which none of the ones from the flyer are.

As an example take this node: https://www.openstreetmap.org/node/4455051600

Instead of creating a separate entry we should add the tags here. The tags to be added should be:

```
toilets=yes
toilets:scheme=Nette Toilette
toilets:male=yes
toilets:female=yes
changing_table=yes
```

If there are opening hours or wheelchair tags already then leave them as they are. Otherwise use the ones from the flyer.

If you have any questions then please don't hesitate to ask.
