### ISSUE TITLE
Add station bound bike-sharing as first/last mile option

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#241]
We should support RegioRad bikesharing as first/last mile option.

A GBFS feed of RegioRad is available via http://gtfs.mfdz.de/gbfs/regiorad_stuttgart/system_information.json.

While ultimately we should support kind of floating drop off in allowed areas (Herrenberg has only on bikesharing station at the station), with this task only station-bound bikesharing shall be supported.

Sub-tasks:

- [x] Add GBFS Updater to OTP's router config for the GBFS feed cited above
- [x] Enable bikesharing as first/last mile mode in digitransit (it uses a specific brand name citybike. We should use a brand agnostic naming)
- [x] Check (better in Stuttgart) that bikesharing connections are found. Perhaps routing has to analyzed and/or parameters need to be changed.
- [x] Add bikesharing stations to map via tile live (see [tilelive-otp-citybikes](https://github.com/HSLdevcom/tilelive-otp-citybikes) for an example how ). Keep in mind, that we have currently already a `Sharing` layer, which ideally would contain all sharing offers. Perhaps easiest thing to do would be to add a (for now) static car-sharing and taxi feed.
- [x] Add details popup which contains meaningful infos from GBFS feed. If anything is missing from the feed, we should discuss if it could be enhanced.
- [x] Possibly, we need to prettify bike-share legs in the trip summary/details

**Comment by leonardehrenfried** [comment]
I've tested the feed locally and it works well in Stuttgart for walking & cycling routes, but not so much for cycling & transit routes:

![Screenshot from 2020-06-14 21-12-10](https://user-images.githubusercontent.com/151346/84601946-2fdab580-ae84-11ea-9cec-52b2b83784be.png)

But since there is only a single station in Herrenberg it's hard to find any routes there.

Nevertheless, this is now on staging.

@Beck-berry @meromisi you need to make sure that you're connecting your local digitransit-ui to the staging, not the production system, so start it with `API_URL=https://api.mih.mitfahren-bw.de`.

**Comment by Beck-berry** [comment]
So if I understand right, this is already added to the OTP, right @leonardehrenfried? Can you tell me what is the mode to the OTP, which I can bond to the 'citybike' in the config?

**Comment by leonardehrenfried** [comment]
Try `BIKE_RENT`.

**Comment by leonardehrenfried** [comment]
I do wonder why they've chosen to rename the mode to `CITYBIKE`.

**Comment by Beck-berry** [comment]
When I enabled the `citybike` transportMode for selection, the following appeared:
![Screenshot_2020-06-17_10-41-08](https://user-images.githubusercontent.com/46535522/84876105-253c3e00-b087-11ea-9f49-64ce1f99dc22.png)
Do you have any idea where those data come from? On our map in Kalkofenstraße the Ebikestation only has a capacity of 10:
![Screenshot_2020-06-17_10-50-52](https://user-images.githubusercontent.com/46535522/84877178-6e40c200-b088-11ea-9adf-84f23afb7d70.png)
https://www.openstreetmap.org/node/3777877009

**Comment by leonardehrenfried** [comment]
So there is a bike rental station in Herrenberg but the website says that it has 10 bikes: https://www.regioradstuttgart.de/de/rad-finden

Not sure where that exactly comes from.

The source data are here:

https://gtfs.mfdz.de/gbfs/regiorad_stuttgart/station_information.json
https://gtfs.mfdz.de/gbfs/regiorad_stuttgart/station_status.json

Can you find the station in Herrenberg and check the numbers?

**Comment by hbruch** [comment]
For Herrenberg station, the GBFS feed reports zero available bikes:
`"num_bikes_available":0,"num_docks_available":99`
 I'll have to check this in the original flinkster API and flinkster2gbfs transformer, which generates the GBFS.

However, the Flinkster API does not report any capacity, users are allowed to park their bikes besides the docks if they are full. So the number of docks (99) should not be displayed.

And displaying the (internal) ID does not make sense neither.

How is Bikes translated in German and is space sufficient if displayed?

**Comment by Beck-berry** [comment]
@hbruch: In German it looks like this
![Screenshot_2020-06-17_11-13-43](https://user-images.githubusercontent.com/46535522/84879550-a72e6600-b08b-11ea-85c2-54670b4d9002.png)
So I think the space is enough.

I can remove the number of docks and also the ID.

**Comment by leonardehrenfried** [comment]
BTW, in Helsinki they display a sort-of-human-reabable ID: 
![Screenshot from 2020-06-17 11-20-46](https://user-images.githubusercontent.com/151346/84880345-afd36c00-b08c-11ea-835a-1933e3311941.png)

**Comment by leonardehrenfried** [comment]
And in case we want to change the branding, here is usable SVG I found: https://www.regioradstuttgart.de/regiorad/svg/fahrrad.svg

**Comment by hbruch** [comment]
...and perhaps you have a better idea for displaying low availability than the clock symbol? I'ts not very intuitive, IMHO

**Comment by leonardehrenfried** [comment]
> ...and perhaps you have a better idea for displaying low availability than the clock symbol? I'ts not very intuitive, IMHO

What about simply red, orange and green dots?

**Comment by Beck-berry** [comment]
Changed the citybike icon:
![Screenshot_2020-06-17_11-59-08](https://user-images.githubusercontent.com/46535522/84884757-6d149280-b092-11ea-91ce-a8dbf862d082.png)
![Screenshot_2020-06-17_12-01-43](https://user-images.githubusercontent.com/46535522/84884758-6dad2900-b092-11ea-95e3-10aca636b0d5.png)
![Screenshot_2020-06-17_12-01-56](https://user-images.githubusercontent.com/46535522/84884759-6dad2900-b092-11ea-8d11-22deb4442eed.png)
![Screenshot_2020-06-17_12-02-08](https://user-images.githubusercontent.com/46535522/84884760-6e45bf80-b092-11ea-897a-cd132c12e54e.png)

**Comment by leonardehrenfried** [comment]
Can you use the RegioRad colour scheme? https://www.regioradstuttgart.de/de

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-18_08-01-02](https://user-images.githubusercontent.com/46535522/84983849-f03cf380-b139-11ea-8caf-402ed3ae0e67.png)
![Screenshot_2020-06-18_08-01-28](https://user-images.githubusercontent.com/46535522/84983851-f0d58a00-b139-11ea-9228-eab964d18686.png)
Is this ok?

**Comment by hbruch** [comment]
Could you compare how the light blue #009fe4 looks like? The color of the bikes is rather that light blue than the greenish blue.

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-18_08-19-21](https://user-images.githubusercontent.com/46535522/84985124-778b6680-b13c-11ea-83bf-e4a265754258.png)
![Screenshot_2020-06-18_08-19-35](https://user-images.githubusercontent.com/46535522/84985125-7823fd00-b13c-11ea-909b-ab0577788609.png)
Would you then prefer this one?

**Comment by Beck-berry** [comment]
And would you like to change the text 'citybike' to 'RegioRad' in the tooltips and in the menu?

**Comment by hbruch** [comment]
If we need to explicitly name the network, yes. Otherwise I'd prefer the generic mode Bike-Sharing ("Leihrad" in German, @leonardehrenfried WDYT? 
Were you already able to do some routing? Especially in Stuttgart, there should be more stations so you can pick up at one and drop off at the other. If not done already, you probably need to specify the network explicitly in the Digitransit config.

**Comment by Beck-berry** [comment]
Without any configuration, GBFS (string) is set as a network but I was not yet able to plan a trip. (It only shows walking routes when only citybike is selected.)

**Comment by Beck-berry** [comment]
BTW if there is more available bikes, it looks like this
![Screenshot_2020-06-18_09-16-15](https://user-images.githubusercontent.com/46535522/84989736-6ba3a280-b144-11ea-8f6e-424899fced4d.png)

**Comment by leonardehrenfried** [comment]
> Without any configuration, GBFS (string) is set as a network for each station but I was not yet able to plan a trip. (It only shows walking routes when only citybike is selected.)

Our friends in Ulm had a very similar problem. This fixed it: https://github.com/verschwoerhaus/digitransit-ui/commit/930d4df9af784743a6a047cd560e41febdf209d9

**Comment by Beck-berry** [comment]
Well, I added the network as 
```
gbfs: {
        icon: 'citybike',
        name: {
          de: 'RegioRad',
          en: 'RegioRad',
        },
        type: 'citybike',
        url: {
          de: 'https://www.regioradstuttgart.de/de',
          en: 'https://www.regioradstuttgart.de/en',
        },
      },
```
but nothing's changed.

**Comment by leonardehrenfried** [comment]
> Well, I added the network as
> 
> ```
> gbfs: {
>         icon: 'citybike',
>         name: {
>           de: 'RegioRad',
>           en: 'RegioRad',
>         },
>         type: 'citybike',
>         url: {
>           de: 'https://www.regioradstuttgart.de/de',
>           en: 'https://www.regioradstuttgart.de/en',
>         },
>       },
> ```
> 
> but nothing's changed.

Here you can see the stations: https://api.mih.mitfahren-bw.de/routing/v1/router/bike_rental

When I named the network I must have called it `GBFS` which is a mistake. Can you try `GBFS` (uppercase).

> Also which is weird I don't see the stations on the map, although I enabled them.

This is to be expected because we don't have the map layer in the backend yet.

**Comment by Beck-berry** [comment]
When it looks for the network (see any method in the `citybikes.js` file), it changes the id to lowercase, so it should not be a problem. (TBH at first I tried with `GBFS` but then I found this code snippet and changed to lowercase.)


> This is to be expected because we don't have the map layer in the backend yet.

Ok then!

**Comment by leonardehrenfried** [comment]
I just added configuration to name the network `regiorad`: https://github.com/mfdz/OpenTripPlanner-data-container/commit/5fbcacc9388806c6bdee96b976f08bdcbb59e821

Sadly it will take around and hour until we can try it out. I will let you know.

**Comment by Beck-berry** [comment]
This have solved the problem, thanks!
![Screenshot_2020-06-18_11-46-34](https://user-images.githubusercontent.com/46535522/85005653-669d1e00-b159-11ea-8312-c51905abbf4b.png)
However it is not yet perfect, the last leg should be a walking, but you see how it looks right now.

**Comment by leonardehrenfried** [comment]
Is this a UI problem or does the backend return the wrong thing?

**Comment by Beck-berry** [comment]
Must be UI related since all the other data is OK (color, name..), only the icon is misleading.

**Comment by leonardehrenfried** [comment]
Ok, please take a look.

**Comment by Beck-berry** [comment]
Fixed :smile: 
![Screenshot_2020-06-18_13-19-37](https://user-images.githubusercontent.com/46535522/85014357-65beb900-b166-11ea-9029-04efbc715ac8.png)

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-06-18 14-04-07](https://user-images.githubusercontent.com/151346/85018080-e08ad280-b16c-11ea-9675-47a296013fa3.png)
![Screenshot from 2020-06-18 14-02-46](https://user-images.githubusercontent.com/151346/85018085-e1236900-b16c-11ea-8f0b-39f4fb928dad.png)

Please give the logo rounded corners in the itinerary detail view like for the other modes.

**Comment by leonardehrenfried** [comment]
Also, enable regiorad by default.

**Comment by hbruch** [comment]
And instead of "mieten" I'd prefer "ausleihen".

**Comment by leonardehrenfried** [comment]
![Capture+_2020-06-18-23-12-41](https://user-images.githubusercontent.com/151346/85072352-47ce7400-b1b9-11ea-94c6-6c38efb9a27c.png)

And please make the greyed out logo the same shade as the rest.

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-19_08-44-15](https://user-images.githubusercontent.com/46535522/85104826-9c99db00-b209-11ea-8c37-19e49a8067a1.png)
![Screenshot_2020-06-19_08-47-56](https://user-images.githubusercontent.com/46535522/85104831-9d327180-b209-11ea-9311-f3a13079d4d2.png)

**Comment by leonardehrenfried** [comment]
And a bit more padding so the wheels don't "touch" the edge.

**Comment by hbruch** [comment]
Or shrink the bike a bit as we want to have equals size icons for all modes

**Comment by Beck-berry** [comment]
Looks better now:
![Screenshot_2020-06-19_08-57-00](https://user-images.githubusercontent.com/46535522/85105470-dae3ca00-b20a-11ea-8f62-48221ea703ab.png)

**Comment by leonardehrenfried** [comment]
Ok, please make a PR with the changes.

**Comment by leonardehrenfried** [comment]
Now that we have the map layer I have more requests:

![Screenshot from 2020-06-19 14-42-17](https://user-images.githubusercontent.com/151346/85134330-9b35d600-b23c-11ea-9436-3dfc952b86ea.png)

Please remove the bottom half of the popup. We don't have any kind of integration with RegioRad.

**Comment by leonardehrenfried** [comment]
And also give the icon some more padding please.

**Comment by Beck-berry** [comment]
There is a `cityBike.useSpacesAvailable` variable which if false, the "progress bar" and the available places are not displayed. I set this at the beginning to false. Otherwise it it were true:
![Screenshot_2020-06-19_15-13-32](https://user-images.githubusercontent.com/46535522/85136237-a1798180-b23f-11ea-9a3d-42c2da8fadd7.png)
Would you like to display this?
This variable is also responsible for the display of the `/availableSpaces` in the near you view.

**Comment by leonardehrenfried** [comment]
I like it in the popup and I wouldn't mind it in "Near you".

@hbruch do you have an opinion?

**Comment by hbruch** [comment]
As the numbers are plain wrong, we shouldn't display them. Flinkster API has no concept of a capacity of a station, so which proportion is still available. 

What would happen if you press the bike-sharing button? While the GBFS feed currently has no link to book bikes from a specific station, GBFS2 was extended to support such urls. I suppose OTP does not support them now, but it would be helpful, e.g. for Ulm as well. For RegioRad, I could add a static link to the homepage at least.

**Comment by Beck-berry** [comment]
> What would happen if you press the bike-sharing button?

It goes to the given link in the config: https://www.regioradstuttgart.de/de

**Comment by hbruch** [comment]
Ok, that's fine for now. We can add more support later on.

**Comment by leonardehrenfried** [comment]
Ok then ignore my comment about removing it and the capacity.

Just make it all orange with a black bike.

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-19_16-24-36](https://user-images.githubusercontent.com/46535522/85147466-3637ab80-b24f-11ea-9e4f-60c932b0a88a.png)
![Screenshot_2020-06-19_16-53-41](https://user-images.githubusercontent.com/46535522/85147470-36d04200-b24f-11ea-825f-3ef54dadd42e.png)
![Screenshot_2020-06-19_16-57-46](https://user-images.githubusercontent.com/46535522/85147474-3768d880-b24f-11ea-9e83-0abcf5bee260.png)
![Screenshot_2020-06-19_16-49-52](https://user-images.githubusercontent.com/46535522/85147468-36d04200-b24f-11ea-8bd5-14486f48601b.png)

**Comment by leonardehrenfried** [comment]
Since it's the end of the week, I'm going to close this issue. If there are small adjustments to be made, let's create new ones for that.
