### ISSUE TITLE
Add GeoJSON layer for "Nette Toilette"

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#242]
Add a Overpass-to-GeoJSON layer for the toilets added in #240.

**Comment by meromisi** [comment]
what icon should we use for the layer? Just added a temporary icon, because I couldn't find that 'Nette Toilette' red smiling icon.
![image](https://user-images.githubusercontent.com/54352878/84876956-2ae65380-b088-11ea-9701-30969fdb00e2.png)

**Comment by leonardehrenfried** [comment]
http://www.grosskuchen.de/site/Heidenheim/get/params_E1988530966/12138247/Lay-Flyer-Nette-Toilette-1.jpg

Here is a good quality PNG. We need a SVG, right?

**Comment by meromisi** [comment]
yes it accepts only SVG.

**Comment by leonardehrenfried** [comment]
I will write to them and ask for an SVG. In the meantime, can you add a white background to the SVG and make it a circle?

**Comment by meromisi** [comment]
sure

**Comment by meromisi** [comment]
Its a little bit smaller because of the circle. (otherwise people would stick out of the circle)
the background is also light so its a little bit hard to recognize, maybe switching the colors could help. What do you think?
![image](https://user-images.githubusercontent.com/54352878/84881512-3e94b880-b08e-11ea-8b8f-da82e27396fa.png)

**Comment by leonardehrenfried** [comment]
Yes, please experiment a little. Would it be possible to add some padding around the "people"?

**Comment by meromisi** [comment]
Which icon do you prefer? 
Btw in german the POI shows "Nette Toilette" in English just 'Toilet' is it okay?
![image](https://user-images.githubusercontent.com/54352878/84884574-350d4f80-b092-11ea-9e16-3dc07b108a3f.png)
![image](https://user-images.githubusercontent.com/54352878/84884578-36d71300-b092-11ea-9298-ab8a9fb3d8dd.png)

**Comment by leonardehrenfried** [comment]
I prefer the bottom one.

The names are ok.

**Comment by leonardehrenfried** [comment]
What we also need to do is to add a name to the popup so users can easily identify in which cafe/shop/libray the toilet is.

That should be possible when we retag the entries.

**Comment by leonardehrenfried** [comment]
One more request: can you make the header say that's it's a toilet?

en: Public toilet "Kreissparkasse Böblingen"
de: Nette Toilette "Kreissparkasse Böblingen"

**Comment by leonardehrenfried** [comment]
Reopening because of this the previous comment. Please make a second PR.

**Comment by meromisi** [comment]
Renamed nodes:

![image](https://user-images.githubusercontent.com/54352878/85111376-88a7a680-b214-11ea-9da4-8e7705042d6b.png)

![image](https://user-images.githubusercontent.com/54352878/85111389-8d6c5a80-b214-11ea-9e78-9513df3f7d36.png)
