### ISSUE TITLE
Investigate broken deep links on iOS

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#244]
Holger has reported that on his iPhone the deep links look very broken.

![image](https://user-images.githubusercontent.com/151346/85099124-d9130a00-b1fc-11ea-9f34-b2f6b311d65b.png)

Example link: https://herrenberg.stadtnavi.de/reiseplan/Institut%20f%C3%BCr%20F%C3%B6rdertechnik%20und%20Logistik%2C%20Holzgartenstra%C3%9Fe%2015B%2C%2070174%20Stuttgart%3A%3A48.781475659811434%2C9.169464111328127/Kruppstra%C3%9Fe%2036%2C%2070469%20Stuttgart%3A%3A48.81612548331387%2C9.173240661621096?modes=PUBLIC_TRANSPORT%2CCITYBIKE&optimize=TRIANGLE&safetyFactor=0.4&slopeFactor=0.3&time=1592539979&timeFactor=0.3

Deep links in Helsinki look ok: https://reittiopas.hsl.fi/reitti/Merimiehenkatu%3A%3A60.160917%2C24.93791/Tinasep%C3%A4ntie%2035b%2C%20Helsinki%3A%3A60.22299617117426%2C24.943599700927738?time=1592543072

Please investigate what could be the problem. One way could be to use `git bisect` to isolate the offending commit.

**Comment by meromisi** [comment]
It looks like the first bad commit is [this one](https://github.com/stadtnavi/digitransit-ui/commit/da12f03a081fd4fa1830e47274ed9158cb57bd29). Reverting this commit solves the issue, but I guess we need this commit so it's not the desired solution. Anyhow I'm not really sure what causes the bug only on iOS, is there any chance that it has something to do with the backend?

**Comment by leonardehrenfried** [comment]
Note sure if that helps but I could imagine that this triggers different HTML/CSS to be placed onto the page.

**Comment by meromisi** [comment]
Maybe, but I don't know how to check that on my phone without developer tools. I was trying to enable them but it turned out they only work with iOS 11 and I have 13. Additionally its nearly impossible to roll back to a previous version of iOS, so it's quite difficult to debug rn.

**Comment by leonardehrenfried** [comment]
After you've created the upstream ticket, please add a link here.
