### ISSUE TITLE
Bikeshare icons

### ISSUE THREAD

**Issue by Beck-berry** [stadtnavi/digitransit-ui#246]
Few things to be fixed, cleared:
- [x] rounded bikeshare icon is slightly cropped
- [x] which icons are used and where -> table
- [x] badge is slightly on the left of the map icon (should be as it is at parkings)
- [x] remove unnecessary geojson layer

**Comment by Beck-berry** [comment]
There are two types of icons: one for the citybike as a mode, and one for each network which can be set in the config file via the `cityBike.networks.[network].icon` variable. There is a `getCityBikeNetworkIcon` function which would check this variable and if null, the fallback is the mode icon.

Here's a table about which type of the icons are used where:
| UI component | icon type | file | screenshot |
|-------|-----|------|------|
|Near you view / Departure list | network | BicycleRentalStationRowContainer.js | ![Screenshot_2020-06-19_17-10-37](https://user-images.githubusercontent.com/46535522/85148000-e5748280-b24f-11ea-93ca-55e3ae8bdb08.png) |
| Map | network | Citybikes.js | ![Screenshot_2020-06-19_16-53-41](https://user-images.githubusercontent.com/46535522/85147470-36d04200-b24f-11ea-825f-3ef54dadd42e.png) |
| Popup | network | CityBikeCard.js | ![Screenshot_2020-06-19_16-57-46](https://user-images.githubusercontent.com/46535522/85147474-3768d880-b24f-11ea-9e83-0abcf5bee260.png) |
|Mode selection (itinerary settings) | mode | ModeFilter.js | ![Screenshot_2020-06-22_08-58-23](https://user-images.githubusercontent.com/46535522/85257796-b2580c00-b466-11ea-8b0a-994abf1f1011.png)![Screenshot_2020-06-22_08-58-40](https://user-images.githubusercontent.com/46535522/85257798-b2f0a280-b466-11ea-9d05-e814d18b3600.png) |
|Itinerary summary row | network | SummaryRow.js (ModeLeg) | ![Screenshot_2020-06-22_08-58-57](https://user-images.githubusercontent.com/46535522/85257824-ba17b080-b466-11ea-9e49-cf3e6c3e0370.png)![Screenshot_2020-06-22_08-59-09](https://user-images.githubusercontent.com/46535522/85257825-bab04700-b466-11ea-987a-243cab7bc298.png) |

**Comment by Beck-berry** [comment]
Fixed the badge:
![Screenshot_2020-06-22_09-31-46](https://user-images.githubusercontent.com/46535522/85260636-47f59a80-b46b-11ea-9de5-76dfe9603bde.png)

**Comment by hbruch** [comment]
Much better. Hbg decided to switch to RegioRad light blue color. Could you switch for mode and network color, please? 

And thanks for the table, that's exactly what I thought of. I think that should go into the docs some day :-).  A speciality of this mode is, that we don't display the mode in the itinerary views, where we usually do so. Here I see the reason to have the numbers of the specific station displayed. We will see, if we get feedback on this.

**Comment by Beck-berry** [comment]
I believe that at the itinerary page the badge only *looks* to be further away than it should be since the icon is a circle. 
See the icon of HSL, or our mode icon used as network:
![Screenshot_2020-06-23_10-20-47](https://user-images.githubusercontent.com/46535522/85378820-54492880-b53b-11ea-818e-bcb97c55a180.png) ![Screenshot_2020-06-23_10-45-39](https://user-images.githubusercontent.com/46535522/85381900-bb1c1100-b53e-11ea-8fbb-69d0c6e6f8d1.png)

And the problematic one:
![Screenshot_2020-06-23_10-20-38](https://user-images.githubusercontent.com/46535522/85378840-58754600-b53b-11ea-8108-045a2f543f65.png)

On the map the icon has its own method which I could modify easily but here it would be more complicated: the same `Icon` component renders the badges for all types of modes, stops, legs... We can (1) modify the CSS tag which controls its display (`.icon-badge`) - but then all of the badges would be moved, or (2) add a new, citybike specific class to the icon - but then if there is a rectangular icon for a citybike network, the badge might be "too close".

BTW the modifications on the map looks nice for me with both kind of icons:
![Screenshot_2020-06-23_10-44-39](https://user-images.githubusercontent.com/46535522/85382133-ee5ea000-b53e-11ea-82ce-5ebe11f2aa8c.png) ![Screenshot_2020-06-23_10-45-12](https://user-images.githubusercontent.com/46535522/85382138-eef73680-b53e-11ea-9d67-14a87664fda7.png)
