### ISSUE TITLE
Switch RegioRad bikesharing back to blue colour

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#247]

**Comment by Beck-berry** [comment]
![Screenshot_2020-06-23_07-59-38](https://user-images.githubusercontent.com/46535522/85366369-851f6280-b527-11ea-863b-995c376b1ddc.png)
![Screenshot_2020-06-23_08-00-55](https://user-images.githubusercontent.com/46535522/85366531-d2033900-b527-11ea-9543-c432fd1c770b.png)
![Screenshot_2020-06-23_08-05-32](https://user-images.githubusercontent.com/46535522/85366789-548bf880-b528-11ea-9c05-b1ea1775eafa.png)
