### ISSUE TITLE
Fill static GBFS feed for taxis with more information

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#253]
GBFS is originally a specification for returning the availability information of bike rentals but we are using it for taxis and car sharing too.

Later on the data will be dynamic but at the moment it's completely static and placed in the following repo: https://github.com/stadtnavi/static-gbfs-feeds/tree/master/taxi

Acceptance criteria

- Take the data from https://github.com/stadtnavi/digitransit-overpass-layers/blob/master/geojson/taxistand.geojson
- Add it to both `station_status.json` and `station_information.json`

It might be quicker to write a quick script to make the modifications or it might be quicker to do it by hand.

**Comment by Beck-berry** [comment]
What data should go to the status file?

**Comment by leonardehrenfried** [comment]
Just add the fact that there are stations. Copy the already existing "stations".
