### ISSUE TITLE
Add warning about bike rental free-floating drop off

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#263]
In Helsinki you can only return a rented bike in one of the bike rental stations.

Herrenberg wants to have the ability to leave them anywhere but with a warning about additional fees.

Take the following trip as an example, where we rent a bike in Böblingen and ride it to Ehningen: https://tinyurl.com/yb3yl54j

Check the JSON returned from the server for the following alert URL: `alert:bikerental:free-floating-drop-off` and display a message in the ItineraryDetail.

- EN: Destination is not a designated drop-off area. Rental cannot be completed here. Please check terms & conditions for additional fees.
- DE: Ziel ist keine Rückgabestation. Ausleihe kann hier nicht abgeschlossen werden. Anbieterabhängig fallen weiter Gebühren bis zur Rückgabe an einer Station an.

Also make sure that the warning icon is shown in the overview (left hand panel) just like when a train has an alert.

![Screenshot from 2020-06-30 10-25-07](https://user-images.githubusercontent.com/151346/86113232-48281280-bac9-11ea-9b17-b880fefe4ef2.png)

Since this requires changes to the GraphQL schema, please use the branch `free-floating-dropoff-alert` for your work.

**Comment by leonardehrenfried** [comment]
Hmm, it appears that the alert is not returned by default by the backend. I need to investigate how to change th GraphQL query so it is.

**Comment by Beck-berry** [comment]
One question: where should the alert message appear?

**Comment by leonardehrenfried** [comment]
Inside the panel, LegDetail (?). A bit like the "Add carpool route" button.

**Comment by Beck-berry** [comment]
Would this be a good position for the info? I also added the info icon to it.
![Screenshot_2020-07-01_10-55-35](https://user-images.githubusercontent.com/46535522/86224636-69e8ce80-bb89-11ea-8272-374051d2c563.png)

**Comment by leonardehrenfried** [comment]
Yes it's a good place.

Can you add more padding and perhaps put it into some kind of yellow box to make it more prominent? Maybe something already exists.

**Comment by leonardehrenfried** [comment]
FYI: I've changed the translations slightly.

**Comment by Beck-berry** [comment]
About the subicon: which would you prefer? You mentioned the exclamation mark but there is another option (you might not saw) so it's better to ask. :)
![Screenshot_2020-07-01_11-23-35](https://user-images.githubusercontent.com/46535522/86228039-2e043800-bb8e-11ea-9e1d-ccde8cb1d107.png) ![Screenshot_2020-07-01_11-28-41](https://user-images.githubusercontent.com/46535522/86228043-2e9cce80-bb8e-11ea-915e-5b113f7da1b5.png)

**Comment by leonardehrenfried** [comment]
I'd go with the exclamation mark.

**Comment by Beck-berry** [comment]
I did not want to choose a *too* dark color, what would you say to these?
Gold:
![Screenshot_2020-07-01_11-51-33](https://user-images.githubusercontent.com/46535522/86230428-56d9fc80-bb91-11ea-858d-24136d93fc2e.png)
Sandybrown:
![Screenshot_2020-07-01_11-52-14](https://user-images.githubusercontent.com/46535522/86230431-57729300-bb91-11ea-9198-0d5f90ce4917.png)

**Comment by leonardehrenfried** [comment]
I like this idea with the border.

**Comment by Beck-berry** [comment]
This is the colour of the subicon:
![Screenshot_2020-07-01_12-02-03](https://user-images.githubusercontent.com/46535522/86231346-b684d780-bb92-11ea-9d98-b888ee9d4178.png)

**Comment by leonardehrenfried** [comment]
That's too bold. Can you make the border 2px and use the colour #f7ab38 ?

**Comment by Beck-berry** [comment]
Here you go:
![Screenshot_2020-07-01_12-06-10](https://user-images.githubusercontent.com/46535522/86231731-47f44980-bb93-11ea-9a12-fca56c7f5331.png)

**Comment by leonardehrenfried** [comment]
Yes, and a bit more margin at the top.

**Comment by Beck-berry** [comment]
:smile: 
![Screenshot_2020-07-01_12-09-09](https://user-images.githubusercontent.com/46535522/86232023-b0432b00-bb93-11ea-9f93-a408919c97f9.png)

**Comment by leonardehrenfried** [comment]
Maybe it would be more visually pleasing if we put it in the same colour as the mode, so the blue. Can you try what that looks like and tell me if you like it?

**Comment by Beck-berry** [comment]
I agree, the too many colours can be a bit confusing. I think this is the best so far.
![Screenshot_2020-07-01_12-17-06](https://user-images.githubusercontent.com/46535522/86232822-d2897880-bb94-11ea-8ab4-b6cca26addad.png)

**Comment by leonardehrenfried** [comment]
Yes, we don't want to make it look like a Christmas tree.

Last try: border 1px and border-radius also a bit less.

**Comment by Beck-berry** [comment]
Hmm, nice!
![Screenshot_2020-07-01_12-21-15](https://user-images.githubusercontent.com/46535522/86233229-68250800-bb95-11ea-9231-4375e2f4aa84.png)

**Comment by leonardehrenfried** [comment]
Yes, let's leave it at this.
