### ISSUE TITLE
Improve UI for car sharing

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#265]
Just like with the taxi stands, also change the icon for car sharing.

**Comment by Beck-berry** [comment]
![Screenshot_2020-07-01_09-42-32](https://user-images.githubusercontent.com/46535522/86217131-5173b680-bb7f-11ea-9399-1b34a5c48853.png)
![Screenshot_2020-07-01_09-42-44](https://user-images.githubusercontent.com/46535522/86217135-52a4e380-bb7f-11ea-8e74-b1b8e6856929.png)

**Comment by leonardehrenfried** [comment]
Yes looks good.
