### ISSUE TITLE
Take rentalUriWeb into account

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#271]
Depends on #270

Right now we have the possibility to have a single URI for all rental bikes but we want to support individual deep links.

Therefore we'd like to adjust the following UI:

![Screenshot from 2020-07-06 11-25-43](https://user-images.githubusercontent.com/151346/86578075-84e98300-bf7b-11ea-9fc7-cee0dcd47f83.png)

Acceptance criteria

- Make sure that the network `uri-demo` is added to the backend.
- Configure the previously created bike sharing network `uri-demo` (#270)
- Find the GraphQL query for fetching the detail information when clicking on a bike sharing icon
![Screenshot from 2020-07-06 11-27-15](https://user-images.githubusercontent.com/151346/86578230-c2e6a700-bf7b-11ea-9fab-e28bac87e2c4.png)
- Add the field `rentalUriWeb` to the query
- If `rentalUriWeb` is defined then use this as the URI for the link instead of the globally configured one.

- Find the query for the routing result
![Screenshot from 2020-07-06 12-50-28](https://user-images.githubusercontent.com/151346/86585831-55d90e80-bf87-11ea-9d99-e76e2fd81e0d.png)
- Add the field `rentalUriWeb`
- Display a button in the bike sharing leg just like the carpool one which points to the `rentalUriWeb` (if available) or the the global URL from the config.

**Comment by Beck-berry** [comment]
Added the link under the warning:
![Screenshot_2020-07-08_10-06-54](https://user-images.githubusercontent.com/46535522/86894058-ce180f00-c102-11ea-9ede-d6f3f0e8fa00.png)

What do you think, a button would look better than the simple link? I'm afraid it would look too overcrowded with the alert.
