### ISSUE TITLE
stadtnavi does not find a good transfer for SSB Stadtbahn

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#273]
A user reported a connection reported by the local transport agency VVS which stadtnavi did not find:

![image](https://user-images.githubusercontent.com/2187389/87065357-39e89d80-c211-11ea-8dd9-86a085d1e0d8.png)
![image](https://user-images.githubusercontent.com/2187389/87065501-63092e00-c211-11ea-9610-2c9a7882bb12.png)

Probable reason is a not yet configured "subwayAccessTime" (defaults to 2 minutes), which will add 4 minutes to the transfer at Wasenplatz, so the 2 minutes time between the two connections won't suffice.

As in Stuttgart, for the Stadtbahn some stops are underground and some are not. Setting the subwayAccessTime to a lower value will probably fix this transfer but might have impacts on others, depending on the level of detail of OSM mapping. 

When changing this value, we should check for unintended overly optimistic transfers times.

**Comment by leonardehrenfried** [comment]
I configured the subwayAccessTime to be 0 and lowered the wait reluctance to 0.4.

The latter was a value I came to through experimentation. The previously suggested 0.8 didn't yield the expected results.

**Comment by leonardehrenfried** [comment]
With the above changes we get these results: https://tinyurl.com/ybhx6xdh
