### ISSUE TITLE
Compare Herrenberg routing results with VVS and Google Maps

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#274]
We would like to get a subjective "feel" of how we are doing when compared to the VVS and Google Maps route search.

For the next week (or whenever you are working on our project), please spend 15 minutes per day doing route searches in and around Herrenberg (major focus), Stuttgart and perhaps other larger cities in Baden-Württemberg. 

Compare the results you receive with the the VVS search (http://en.vvs.de/home/) and Google Maps.

Afterwards, please spend another 15 minutes documenting what the results were and put particular focus on how they were different. Please also analyse if you think that we are doing better of worse and perhaps even add suggestion on how to improve.

**Comment by Beck-berry** [comment]
## Nüfringen → Herrenberg
All three offered the same route with S1 line.
## Aidligen → Herrenberg
* Stadtnavi: 763 + RB14 - 58 min
   https://herrenberg.stadtnavi.de/reiseplan/Kniebisstra%C3%9Fe%2C%2071134%20Aidlingen%3A%3A48.6813027%2C8.8922622/Herrenberg%2C%2071083%20Herrenberg%3A%3A48.595557%2C8.8674715?optimize=TRIANGLE&safetyFactor=0.4&slopeFactor=0.3&time=1594921637&timeFactor=0.3
* Google: 763 + S1 + 774 - 1h 6min
   https://www.google.com/maps/dir/48.681458,8.8932327/48.5934721,8.8360435/@48.6412668,8.8471247,12z/am=t/data=!3m1!4b1!4m2!4m1!3e3
* VVS: 763 + S1

Stadtnavi found a faster route but this is its only suggestion. Google has more (four) suggestions but they are all slower. (I believe that Google Maps has a bit different GPS coords for the city of Herrenberg, this is why all of the routes has one more bus trip.) I don't quite get the difference between S1 and RB14..? They seem to be the same line.
## Wildberg → Herrenberg
* Stadtnavi: 775 or **775-E** or 759 + 773
   https://herrenberg.stadtnavi.de/reiseplan/Wildberg%3A%3A48.6226688%2C8.7484361/Herrenberg%2C%2071083%20Herrenberg%3A%3A48.595557%2C8.8674715?optimize=TRIANGLE&safetyFactor=0.4&slopeFactor=0.3&time=1595236020&timeFactor=0.3 
* Google: 759 + 773 or 775 or **RB 22219 + X77** or 775 + 773
   https://www.google.com/maps/dir/72218+Wildberg,+N%C3%A9metorsz%C3%A1g/Herrenberg,+N%C3%A9metorsz%C3%A1g/@48.6014452,8.7231329,12z/data=!3m1!4b1!4m15!4m14!1m5!1m1!1s0x479743532962123d:0x41ffd3c8d0954b0!2m2!1d8.7410966!2d48.6246322!1m5!1m1!1s0x479758c2ddc44031:0x41ffd3c8d0927b0!2m2!1d8.8671577!2d48.5950369!3e3!5i2 
* VVS: 759 + 773 or 775

Both Google and Stadtnavi has results that are **not in VVS**, and from these two, Stadtnavi found a faster alternative but with more walking (Google has 15 mins of walking, Stadtnavi has 24).
