### ISSUE TITLE
Add alert and button for Park & Ride searches

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#276]
The backend has been modified to send an alert when we are parking the car in a park & ride car park that is full or almost full.

An example route of this is the following: https://tinyurl.com/ybjmrq7w (Click on 'Now' to set the time to the current one).

However, after code review, we have abandoned the idea of putting a pseudo-ID in the field `alertUrl`. We will send normal, localised alerts and these should be put into the UI as is. Translation of the message should not be handled by the frontend.

### Acceptance criteria

- ~~Add the fields `alertHeaderText`, `alertDescriptionText`, `alertId` to the GraphQL query for routes.~~ (Already done on branch `alert-id`).
- Use the field `alertId` to identify two types of messages: one for the BicycleLeg when dropping off a bike and one for the CarLeg when parking at a car park that is almost full. 
- Make the alerts in the car leg look just like one in the bicycle leg.
- In the bicycle leg, change the translation code and display the fields coming from the backend, rather than translating them client side.

### Additional task
- When the backend sends the alertId `car_park_full` for a car leg, then not only display the alert, but also show a button saying "Exclude full car parks" (DE: "Volle Parkplätze ausschließen"). When clicking this button, then the same route search should be executed but the parameter `useCarParkAvailabilityInformation` should be set to `true`.

**Comment by leonardehrenfried** [comment]
Two features are missing:

- The alerts are not localised
![Screenshot from 2020-07-20 11-38-59](https://user-images.githubusercontent.com/151346/87923349-a0758300-ca7d-11ea-843d-88768395cb32.png)
- Can you add an alert icon to the overview?
![Screenshot from 2020-07-20 11-34-46](https://user-images.githubusercontent.com/151346/87923406-baaf6100-ca7d-11ea-91f8-dc995997a766.png)

**Comment by leonardehrenfried** [comment]
Can you give a rough overview of the work involved to the the image to the summary?

**Comment by leonardehrenfried** [comment]
I made some larger changes how the translations of the alerts are handled. Now the backend sends all of the languages at once. This seems to be the digitransit way. :man_shrugging: 

I managed to fix the CarLeg myself but the BicycleLeg needs a bit of attention because the free floating alert doesn't necessarily need to be the first one. Please also filter the alerts by their id like I did in CarLeg.

**Comment by leonardehrenfried** [comment]
Also, please take care of this error:

![Screenshot from 2020-07-20 16-02-31](https://user-images.githubusercontent.com/151346/87952481-290a1880-caaa-11ea-95ff-3c054bfa4d3d.png)

I'm pretty sure that it's harmless but we already have so many of these, I don't want to make it worse.

**Comment by Beck-berry** [comment]
Found out that the `alerts` can be fetched for the SummaryRow too, so problem solved! :smile: Next question: would we like to show the alert icon for *all* types of legs? Turned out that, for example here, the walking also has an alert but we won't show it in the details so the icon seems a bit unnecessary for me. Should we go then only with the `citybike` and the `car` legs?
![image](https://user-images.githubusercontent.com/46535522/88019586-6a420d00-cb2a-11ea-863d-51b6468d9462.png)

**Comment by leonardehrenfried** [comment]
Yes, only bike and car legs.
