### ISSUE TITLE
Fix missing bike sharing icon

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#291]
DT next has changed how the icons work and there are now several versions of the same icon for different zoom levels.

On top of this, I have also written some tooling to make working with the icons easier.

Acceptance criteria

- Take the citybike icons (various sizes and colours) from `sprite-hsl.svg`
- Copy all the versions into `sprite-hb-source.svg` renaming it "regiorad" rather than "citybike"
- Run `scripts/compile-hb-sprite`
- Check that the icons are there and run `CONFIG=hbnext yarn run dev`
- View the app in the browser to check that all icons are displayed (zoom to Stuttgart to see alle the varieties)
- Write a documentation in `docs` page about how to "compile" those icons.

**Comment by meromisi** [comment]
I compared the result and there are new orange ones(on all zoom levels as the other blue ones) as you can see. 
![image](https://user-images.githubusercontent.com/54352878/99380553-694b9d00-28ca-11eb-8a83-e5a8a4b02a17.png)

Just one question. In the `docs` folder should I just create a new file for example `Icons.md` and write the steps I did?

**Comment by leonardehrenfried** [comment]
Please replace the current blue ones with the original Helsinki ones.

Also, can you try either by CSS or modifying the SVG to make the background blue and the bike white?

> Just one question. In the docs folder should I just create a new file for example Icons.md and write the steps I did?

Yes, please. New file.
