### ISSUE TITLE
Add taxi and carsharing icons in all sizes and colours

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#293]
- Check what icon variations are missing and make copies with the various names

**Comment by meromisi** [comment]
I checked it and it seems like `svg-sprite.hb.svg` has more icons related to taxi and car sharing than `svg-sprite.hsl.svg`. Is it sure that there are missing icons?

**Comment by leonardehrenfried** [comment]
![Screenshot from 2020-11-17 14-49-19](https://user-images.githubusercontent.com/151346/99398055-2b5b7280-28e4-11eb-82b9-86f54254ce13.png)

Yes, please use the current taxi and carsharing icons, make copies and rename them to the ones showing up in the log as missing.
