### ISSUE TITLE
Add config to toggle the station and line search

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#299]
Please add a configuration option to enable developers to switch off the station and line search, as we don't have it in Herrenberg.

![Screenshot from 2020-11-19 13-19-11](https://user-images.githubusercontent.com/151346/99666363-3391ea00-2a6b-11eb-9758-009bdbb2079a.png)

Don't forget to set it to enabled in the default config.

**Comment by Beck-berry** [comment]
You mean this field, right?
![image](https://user-images.githubusercontent.com/46535522/99666229-01808800-2a6b-11eb-9a0a-fcea368583b4.png)

**Comment by leonardehrenfried** [comment]
Yes, I forgot to add a screenshot.
