### ISSUE TITLE
Re-do https://github.com/HSLdevcom/digitransit-ui/pull/3230

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#301]
Sadly, our feature https://github.com/HSLdevcom/digitransit-ui/pull/3230 is gone from the next branch.

![image](https://user-images.githubusercontent.com/151346/99696587-24249800-2a8f-11eb-950f-cb47dbb41acc.png)

Please branch from upstream, readd the feature and and make an upstream PR.

Also please reinstate the interpolation of the current vehicle positioning.

**Comment by Beck-berry** [comment]
@leonardehrenfried Sorry, but I don't quite get what do you think of when you say
> reinstate the interpolation of the current vehicle positioning

I do not remember changing anything like that, did HSL made a modification we don't need?

**Comment by leonardehrenfried** [comment]
I mean this one: https://github.com/stadtnavi/digitransit-ui/pull/233

**Comment by Beck-berry** [comment]
[PR](https://github.com/HSLdevcom/digitransit-ui/pull/3739) is in progress.
