### ISSUE TITLE
Re-add bike sharing alert about free floating drop off

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#307]
The following UI is missing:

![Screenshot from 2020-11-20 12-07-00](https://user-images.githubusercontent.com/151346/99793437-fbe97780-2b28-11eb-8cc0-00ec2e237d62.png)

**Comment by Beck-berry** [comment]
Would you please have a look at the graphQL query? `leg.alerts` is undefined and I am not sure if I did something wrong in the `schema.json` or it *really* is undefined.

**Comment by leonardehrenfried** [comment]
yeah, we had to change something there. let me look it up.
