### ISSUE TITLE
Add "parking lot" full alerts to CarLeg

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#310]
Please add the alert for when a car park is full as previously implemented in https://github.com/stadtnavi/digitransit-ui/pull/277/files#diff-85baa0a5a0d6bba50393dc15edc99d9774e3d79bcc29a534a497004751ee68bdR101

Since we don't have capacity information at the moment, fake the condition in the frontend to see the alert in action.

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/100091489-f5bf0800-2e54-11eb-859c-1b96db098740.png)

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/100339543-4875fc80-2fda-11eb-87b2-c2dafb9e7a64.png)
