### ISSUE TITLE
Add popup rows

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#311]
We need the `SelectRows` from master for

- Parking lots
- Carpool stops

Can you think of any others that I've missed?

**Comment by meromisi** [comment]
we displayed the following rows previously:
  - terminals(I think we dont have now)
  - stops (we have rn)
  - Citybikes (we have rn)
  - parkAndRide (we have rn)
  - covid19OpeningHours (we dont have rn)
  - Roadworks (we dont have rn)
  - Carpool (we have them in the stops)
  - dynamicParkingLots (we have now)

**Comment by leonardehrenfried** [comment]
That's fine because covid is dead (well, the popup) and roadworks disabled.
