### ISSUE TITLE
Re-add triangle safety factors for cycling

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#313]
DT allowed you to customize the so-called triangle factors for cycling where you could give priorities for distance, safety and slope.

It's gone in DTnext, so lets bring it back, as we've spent quite a bit of time tuning this.

Acceptance criteria:

- Find relevant GraphQL queries in `SummaryPage`
- Set `optimizeType=TRIANGLE`
- Allow configuration of the query variables `safetyFactor`, `speedFactor` and `slopeFactor`

**Comment by Beck-berry** [comment]
Should we enable this only for the bikePlan or for every plan related to biking? (bike and transport, bike and park)

**Comment by leonardehrenfried** [comment]
All of them except car and park & ride. Bike sharing counts as public transport that's why we need it there too.
