### ISSUE TITLE
Remove "Select Routes" from departure board

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#315]
The circled dialog is more confusing than helpful.

![Screenshot from 2020-11-26 11-02-23](https://user-images.githubusercontent.com/151346/100344528-3c416d80-2fe1-11eb-9cb2-8670827306b9.png)

Please introduce a config param to turn it off an disable in Herrenberg.

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/100448896-50559f80-30b3-11eb-855a-427b0c2e15fa.png)
