### ISSUE TITLE
Improve sharing popup

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#322]
## Title

The sharing popups should show the station name again.

Old:
![image](https://user-images.githubusercontent.com/151346/100427499-d44b5f80-3092-11eb-9941-162a66a47421.png)

Currently:
![image](https://user-images.githubusercontent.com/151346/100427523-ddd4c780-3092-11eb-8bbb-e573d2e0602e.png)

## Non-bikes

For car sharing and taxi we should remove the bottom half of the popup as it never makes sense.
![image](https://user-images.githubusercontent.com/151346/100427589-fb099600-3092-11eb-8c25-72f016782696.png)

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/100444120-37e18700-30ab-11eb-967c-6bcfd0b2408e.png)
![image](https://user-images.githubusercontent.com/46535522/100444999-a7a44180-30ac-11eb-81a4-4e1eea5b87e0.png)
![image](https://user-images.githubusercontent.com/46535522/100445013-b0951300-30ac-11eb-8805-dc7dfc9636a3.png)

**Comment by leonardehrenfried** [comment]
I'm very sorry for not being clear but what I wanted to have removed was the part "Bikes available at the station right now ()".

**Comment by Beck-berry** [comment]
Whoops, my bad! I should have think of that.

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/100447920-bc370880-30b1-11eb-92dc-67910588277f.png)
