### ISSUE TITLE
Investigate what is going on with the single "hybrid" icon

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#329]
"Hybrid" stops, as they are called in the code, are there for, i think, when there are more than a single type of transport on a stop.

![Screenshot from 2020-11-27 13-43-28](https://user-images.githubusercontent.com/151346/100450966-e4753600-30b6-11eb-816e-c263c144b58c.png)

In Herrenberg we have a single such stop but the rendering seems incorrect. Please investigate what is going on.

**Comment by Beck-berry** [comment]
So it seems like that in Stop.js the following condition decides on whether the hybrid icon should be used:
```js
this.config.mergeStopsByCode &&
f.properties.code &&
prevFeature.properties.type !== f.properties.type &&
f.geom.x === prevFeature.geom.x &&
f.geom.y === prevFeature.geom.y
```
In our case, `mergeStopsByCode` is enabled in the config which is OK. The problem might come from the fact that the type of the `prevFeature` and the actual `f` are not equal in this case: although we should see two bus stops on the map one has the type of 'carpool' whilst the other is 'bus'. This bug might come from the data then. What do you think?

**Comment by leonardehrenfried** [comment]
So if there are two stops on exactly the same coordinates *and* they have different modalities, then we see the hybrid icon?

**Comment by Beck-berry** [comment]
Yes, it should work that way.
