### ISSUE TITLE
Replace map popups by side/bottom sheet panes

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#344]
Especially on mobile, popups for selected map features cause a bad user experience, as they are often too large to be displayed unclipped/without need to scroll.

Details for selected features should be displayed in a side/bottom sheet pane, which allows to display more details. The pane should be scrollable.

Layers to move first are then ones that we at Herrenberg added:

- [x]  Roadworks
- [x] -Charging stations
- [x] Bike parking spaces
- [x] Parking
- [x] Road weather
- [x] "Nette Toilette"
- [x] Bycicle Repair Station
- [x] "Radlager"

**Comment by leonardehrenfried** [comment]
Does it make sense to create a PR per layer?

**Comment by andreashelms** [comment]
Maybe that would make sense. I will decide based on how much changes are needed for moving one layer's popup content to sidebar.

**Comment by Denis306** [comment]
@leonardehrenfried @andreashelms  did we miss the "Nette Toilette", the "Bicycle Repair Station" and "Radlager" Layer in this ticket? Or are those not wanted in the side panel? Just asking because we could ignore this issue https://github.com/stadtnavi/digitransit-ui/issues/469 for now then.

**Comment by leonardehrenfried** [comment]
I spoke to Holger about it and he would like to move them as well. They are all GeoJSON-based so I think it would with a single code change.

However, I don't think it's necessary to define a URL for them.

**Comment by Denis306** [comment]
Alright, I updated the ticket and will put it back in the In Progress column until @andreashelms fixes it.
