### ISSUE TITLE
Adding hierarchies to the layer switcher

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#345]
Stadtnavi has a couple of layers, so the list is getting quite long. Layers should be grouped by category so that you can disable, for example, all stop types at once. Level 2 should be collapsible.

## Design

This is the design/flow that Sandra created for the map layer switcher: https://xd.adobe.com/view/fd112b40-8ae5-4756-8620-31731933c234-a842/ 

IMPORTANT: Please use the Icons that are already in use in the WebApp!

- [x] Categories for the Layer Tree:         ENGLISH  /  GERMAN

Public Transit  /  Öffentlicher Nahverkehr
- Bus stops  /  Bushaltestellen
- Metro stations  /  U-Bahnhöfe
- Train stations  /  Bahnhöfe

Bicycle  /  Fahrrad
- Bike parking spaces  /  Fahrradstellplätze
- Service stations and stores  /  Service Stationen und Läden

Sharing Offers  /  Sharing Angebote
- Car, Bike & Cargo bike sharing  /  Carsharing & Fahrrad- / Lastenradverleih
- Carpool stops  /  Mitfahrpunkte

Car  /  Auto
- Parking spaces / Parkplätze
- Charging stations / Ladestationen

Others  /  Andere
- Public toilets  /  Nette Toilette
- Roadworks  /  Baustellen
- Road weather  /  Straßenwetter
- LoRaWAN Gateways  /  LoRaWAN Gateways

- [x] The Top level Layers have the following 3 states:
1. Main Category Selected with a checkmark -> Means all subcategories are selected as well.
2. Main Category Selected with a minus -> Means that some subcategories are selected but not all or none.
3. Main Category not selected -> None of the sub categories are selected either.

- [x] The Map Layer Panel has to be scrollable so that when all of the Categories are expanded the user can scroll through them.
- [x] Also please add the 3 Map Type tiles at the bottom of the map layer switcher panel.
- [x] Add light grey lines to divide the layer groups. 

![image](https://user-images.githubusercontent.com/63004289/120940886-d36d4780-c71f-11eb-8078-0324912c2110.png)
![image](https://user-images.githubusercontent.com/63004289/120940873-bdf81d80-c71f-11eb-93ec-c66e4b30899f.png)
![image](https://user-images.githubusercontent.com/63004289/122005476-f8b02480-cdb5-11eb-82e8-fe7c4b5db223.png)

**Comment by Denis306** [comment]
@andreashelms @SamuelRioTz I updated the Structure and names of the layers and added both the english and german texts. Let me know if anything is still unclear.
