### ISSUE TITLE
Booking On-Demand Transport (Taxi)

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#350]
In Herrenberg after 9pm some busses are replaced with Taxis that you need to book in advance.

For example, when you want to travel from Nufringen to Gültstein at 10 pm, you will receive something that looks like a normal bus route: https://tinyurl.com/yds6qdkz

![Screenshot from 2021-05-31 09-26-21](https://user-images.githubusercontent.com/151346/120158309-46446300-c1f4-11eb-9f16-f8b2dd2e0128.png)

## Flex mode

However, you can also book a special mode that will take you directly to your door (if it's within 300m of a bus stop). We want to show this mode in a separate "tile" next to the cycling, p+r ... modes. 
This is the "Taxi" Icon that we are using combined with the public transit icon for the new flex mode tile: 
[TaxiIcon.zip](https://github.com/stadtnavi/digitransit-ui/files/6605014/TaxiIcon.zip)

![Screenshot from 2021-05-31 10-04-01](https://user-images.githubusercontent.com/151346/120161403-8bb65f80-c1f7-11eb-88f7-81676f309f7b.png)

The icon should be a car with a bus in the background.

In this tile, you need to add the modes `FLEX_DIRECT`, `FLEX_EGRESS`. The result should then look like this.

![Screenshot from 2021-05-31 10-09-40](https://user-images.githubusercontent.com/151346/120162149-637b3080-c1f8-11eb-843e-5ee7b9525b8a.png)

## Booking info

Also in both cases you must get additional data from the GraphQL API about the following booking requirements:

- booking telephone number and URL
- a warning about having to book ahead of time

We have added new GraphQL properties for the booking info and with the following query you can get the message, telephone number and URL.

URL: https://api.dev.stadtnavi.eu/otp/routers/default/index/graphql

```
query{
  plan(
    date: "2021-06-02"
    time: "22:30"
    from: { lat:  48.6226, lon: 8.8879 }
    to: { lat: 48.5755, lon: 8.8795 }
    transportModes: [
      { mode: RAIL },
      { mode: FLEX, qualifier: EGRESS },
      { mode: FLEX, qualifier: DIRECT },
      { mode: WALK },
    ],
    maxWalkDistance: 5000
  ) {
    itineraries {
      legs {
        mode
        rentedBike
        distance
        startTime
        endTime
        pickupBookingInfo {
          message
          contactInfo {
            phoneNumber
            infoUrl
            bookingUrl
          }
        }
        route {
          url
          mode
          shortName
        }
        trip {
          gtfsId
          tripShortName
        }
        from {
          name
          bikeRentalStation {
            name
            id
          }
        }
        to {
          name
          bikeRentalStation {
            name
            id
          }
        }
      }
    }
  }
}
```

The new part is:

```
 pickupBookingInfo {
          message
          contactInfo {
            phoneNumber
            infoUrl
            bookingUrl
          }
        }
```

**Comment by patrickbeck1337** [comment]
I have to say that this ticket is very unclearly formulated. We might need to have a chat about this one @leonardehrenfried.

**Comment by leonardehrenfried** [comment]
That's a valid point.

The point is that we don't know what is going to be possible so I can't really specify it it any better.

I hope I can clarify over the next couple of days.

**Comment by derhuerst** [comment]
I'm currently writing a script that can generate GTFS-Flex and patch it into the main GTFS dataset. If there aren't any unintuitive gotchas in the [GTFS-Flex spec](https://github.com/MobilityData/gtfs-flex/blob/e1832cfea5ddb9df29bd2fc50e80b0a4987695c1/spec/reference.md), and if OTP2 can properly make use of the data, this should be the cleanest and most maintainable way forward.

**Comment by leonardehrenfried** [comment]
If it wasn't clear, @patrickbeck1337, this means that we will try hard to go with the second option.

**Comment by derhuerst** [comment]
The aforementioned GTFS-Flex script is here: https://github.com/derhuerst/generate-herrenberg-gtfs-flex

It cannot patch `stop_times.txt` yet though, as it is required for GTFS-Flex to work (it provides the links between the "normal" GTFS data and the GTFS-Flex-specific files `locations.geojson` & `booking_rules.txt`). I will work on that now.

**Comment by derhuerst** [comment]
OTP PRs related to GTFS-Flex:

- https://github.com/opentripplanner/OpenTripPlanner/pull/2603
- https://github.com/opentripplanner/OpenTripPlanner/pull/3173
- https://github.com/opentripplanner/OpenTripPlanner/issues/3343

**Comment by derhuerst** [comment]
`generate-herrenberg-gtfs-flex` can generate `booking_rules.txt` & `locations.geojson` and patch `stop_times.txt` now, but I haven't tested or validated the output yet.

Will have a look what OTP2 does with it.

**Comment by derhuerst** [comment]
from the Zulip chat:

> please don't include it yet Jannis. we need a special patch provided by Hannes Junnila for it to work.
> Jannis and I have seen huge performance problems using GTFS-Flex and are not sure what the source of it is.

**Comment by derhuerst** [comment]
> We have tried running with [the data generated by this PR](https://github.com/derhuerst/gtfs-hub/blob/4221634ac7476e7b5cf85c4923ee76cb5dca5a53/makefile#L107), but it seems that OTP2 doesn't like it either.

https://github.com/derhuerst/generate-herrenberg-gtfs-flex/pull/1#issuecomment-848781374

**Comment by leonardehrenfried** [comment]
I've updated the ticket and would be grateful if the participants could take a look and spot any mistakes.

**Comment by derhuerst** [comment]
As Leonard mentioned in the Zulip chat, the latest changes (https://github.com/derhuerst/generate-herrenberg-gtfs-flex/pull/2) seem to work in OTP2, so I merged it.

**Comment by Denis306** [comment]
@andreashelms Reopening and putting it to "In Review" so @leonardehrenfried can deploy on dev/QA for testing.

**Comment by ahmed-nawar** [comment]
- No translation when the language is set to English
- The spacing is weird

![image](https://user-images.githubusercontent.com/84456072/121912915-4171ca00-cd31-11eb-91f3-69a12cfc4e07.png)

**Comment by leonardehrenfried** [comment]
The missing translation is a technical limitation which we cannot solve easily, however you're right with the spacing.
