### ISSUE TITLE
Display fares (was ticketing)

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#352]
As a first step towards a ticketing solution we want to display fare prices in stadtnavi.

Legally we are not allowed to calculate prices, like Helsinki does, but have to go through another service. This service is quite slow so we will load the prices asynchronously.

## Sequence diagram

An overview of the various interactions is this:

![ticketing](https://user-images.githubusercontent.com/151346/116384486-2ea24500-a818-11eb-930c-1699f0de0c1a.png)

## Mock

We have already installed a mock system that allows you to test out the API call to convert an OTP itinerary to a price information. You need to send an OTP route to the ticketing backend to receive the price in the same format as OTP would send it.

Use the following `curl` example to learn how to use the API:

```
curl --request POST \
  --url https://api.dev.stadtnavi.eu/fares \
  --header 'Content-Type: application/json' \
  --data '{
  "startTime": 1619686447000,
  "endTime": 1619688124000,
  "walkDistance": 1112.27,
  "duration": 1677,
  "fares": null,
  "legs": [
    {
      "mode": "RAIL",
      "alerts": null,
      "agency": {
        "name": "VVS",
        "url": "http://www.vvs.de",
        "fareUrl": null,
        "id": "QWdlbmN5OjE6MQ"
      },
      "from": {
        "lat": 48.662792,
        "lon": 8.944269,
        "name": "Ehningen",
        "vertexType": "TRANSIT",
        "bikeRentalStation": null,
        "stop": {
          "gtfsId": "1:de:08115:5773:1:2",
          "code": null,
          "platformCode": null,
          "vehicleMode": "RAIL",
          "zoneId": null,
          "alerts": [
            
          ],
          "id": "U3RvcDoxOmRlOjA4MTE1OjU3NzM6MToy"
        }
      },
      "to": {
        "lat": 48.594067,
        "lon": 8.862787,
        "name": "Herrenberg",
        "vertexType": "TRANSIT",
        "bikeRentalStation": null,
        "stop": {
          "gtfsId": "1:de:08115:4512:1:3",
          "code": null,
          "platformCode": null,
          "zoneId": null,
          "alerts": [
            
          ],
          "id": "U3RvcDoxOmRlOjA4MTE1OjQ1MTI6MToz"
        },
        "bikePark": null,
        "carPark": null
      },
      "transitLeg": true,
      "startTime": 1619687040000,
      "endTime": 1619687640000,
      "distance": 10368.007630690607,
      "duration": 600,
      "intermediatePlace": false,
      "route": {
        "shortName": "S1",
        "color": "83b23b",
        "gtfsId": "1:10-1-j21-16",
        "longName": "Kirchheim (T) - Plochingen - Stuttgart - Herrenberg",
        "desc": null,
        "agency": {
          "gtfsId": "1:1",
          "fareUrl": null,
          "name": "VVS",
          "phone": "+49 711 66060",
          "id": "QWdlbmN5OjE6MQ"
        },
        "alerts": [
          
        ],
        "id": "Um91dGU6MToxMC0xLWoyMS0xNg",
        "mode": "RAIL"
      }
    }
  ]
}'
```

## Acceptance criteria

In order to complete this ticket please fetch the price information when opening the the itinerary detail view:

![Screenshot from 2021-04-28 12-01-35](https://user-images.githubusercontent.com/151346/116385844-81303100-a819-11eb-97d1-5a62df1e4c89.png)

Just like it is displayed in Helsinki:

![Screenshot from 2021-04-28 12-02-38](https://user-images.githubusercontent.com/151346/116386127-c81e2680-a819-11eb-910b-6a899ce2eb4d.png)

- There are many ticket types available but please only display the single adult ticket. @derhuerst can advise what the id of this is.

- Only display the "Book" button when the backend sends the URL.

**Comment by leonardehrenfried** [comment]
@patrickbeck1337 can you please re-read the ticket, check if it is clear and actionable now and remove the label "needs clarification" if that is true?

**Comment by patrickbeck1337** [comment]
Yeah at least for displaying the fares everything should be clear now. So this ticket is just about displaying the fares/ prices right @leonardehrenfried ?

**Comment by leonardehrenfried** [comment]
> Yeah at least for displaying the fares everything should be clear now. So this ticket is just about displaying the fares/ prices right @leonardehrenfried ?

Yes, just the fares. We might add a deeplink to another system where you can buy a ticket but that's still up in the air.

**Comment by MartinH-open** [comment]
I assume these prices just apply to the busses and trains on the route, right ?  
There might be other additional costs for bike rental, Taxi, Carpooling etc. Not sure how these will be displayed.

**Comment by derhuerst** [comment]
> I assume these prices just apply to the busses and trains on the route, right ?

Yes, so far, we only have fares for the public transport parts of an itinerary.

**Comment by Beck-berry** [comment]
@derhuerst, as I sent the curl request, I see that there are only two types of tickets: `regular` and `youth`.

Part of the response:
```js
{
	"type":"regular",
	"currency":"EUR",
	"cents":320,
	"components":[{
		"fareId":"020112",
		"currency":"EUR",
		"cents":320,
		"url":"https://example.org/fares/foo"
	}]
},
{
	"type":"youth",
	"currency":"EUR",
	"cents":150,
	"components":[{
		"fareId":"020212",
		"currency":"EUR",
		"cents":150,
		"url":"https://example.org/fares/foo"
	}]
}
```

As @leonardehrenfried asked for only the single adult tickets, I believe that those are the `type: regular` ones. Could you please reassure me about that?

**Comment by hbruch** [comment]
`regular` is equivalent to adult, yes. We should use the term `regular`.

**Comment by leonardehrenfried** [comment]
I merged the initial PR and it's on dev, but I still see "no price information" and then afterwards the ticket.

![Screenshot from 2021-06-16 12-08-42](https://user-images.githubusercontent.com/151346/122203467-5b7ceb00-ce9e-11eb-90ec-e7d900b2e28c.png)

https://dev.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/Ehningen%3A%3A48.6592556%2C8.9405097?time=1623839321

Please take a look at this.

**Comment by nghanem-poet-egypt** [comment]
@leonardehrenfried are fares still being displayed on dev? I'm not testing them, I just wanted to compare it to the mobile app implementation and didn't find it. Could you help on that? 
![grafik](https://user-images.githubusercontent.com/84389152/122736644-89887380-d280-11eb-8bf6-38c989ab50f5.png)

**Comment by leonardehrenfried** [comment]
There is a technical problem which i'm currently resolving: https://github.com/stadtnavi/digitransit-ui/commit/b697426707ca37707cc66018c97972b4ea219bba

**Comment by leonardehrenfried** [comment]
Ill let you know when it's back

**Comment by MartinH-open** [comment]
Anyhow, is the dev system always the "newest" version available?  sometimes it appeared that beta is ahead of dev version.
We need a build/version string within each instance (dev,beta,production, apps) to view as an user from when that build is.

**Comment by leonardehrenfried** [comment]
It's back. Sorry for the interruption.

![Screenshot from 2021-06-21 12-34-24](https://user-images.githubusercontent.com/151346/122749009-1fc29680-d28d-11eb-9f1b-09e291ed0ed4.png)

**Comment by nghanem-poet-egypt** [comment]
Thank you for your information, I've noticed that it is now on Beta too. Can you confirm that?

**Comment by leonardehrenfried** [comment]
Yes it is.

**Comment by Denis306** [comment]
@sara-georgy Is there a bug or issue with this ticket? Or why was it moved back to "To Do"?

**Comment by sara-georgy** [comment]
@Denis306 yes, there is the open bug #691

**Comment by hbruch** [comment]
@sara-georgy  #691 is a backend issue unrelated to the frontend

**Comment by sara-georgy** [comment]
@hbruch @Denis306 ok, then I'll close it now.

**Comment by ahmed-nawar** [comment]
@leonardehrenfried The fares are not shown in the dev and beta system but are shown on the production.

**Comment by leonardehrenfried** [comment]
Tickets are now again on all environments although i did find quite a few cases where no prices is returned: https://github.com/stadtnavi/fares-service/issues

**Comment by ahmed-nawar** [comment]
Should we close the issue or leave it until all the cases are fixed?

**Comment by leonardehrenfried** [comment]
I would close it.
