### ISSUE TITLE
More detailed eCharging Station info

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#353]
Stadtnavi has added a layer to display charging stations for cars and bicycles.

![image1](https://user-images.githubusercontent.com/151346/115227950-71299a80-a111-11eb-8054-67a82adec9ab.png)

- stadtnavi should display detail information like e.g. 
- payment types
- charging speeds
- plug types

Basic information like e.g. occupancy status, plug type and details URL, symbols of plug types in SVG format as well as an endpoint to request an OCHP json response for an individual station will be provided as VectorTiles by another working package.

**Comment by leonardehrenfried** [comment]
@Denis306 Here is the PR for the master branch: https://github.com/stadtnavi/digitransit-ui/pull/335

**Comment by Denis306** [comment]
Thanks @leonardehrenfried !

@patrickbeck1337 As discussed earlier today, I created a second ticket to split this one up into two issues. As Leonard already described, this one will be about using the current UI from the master branch and integrating it with the data that @the-infinity is providing.

In a second step (#456) we will then apply the new UI.

**Comment by leonardehrenfried** [comment]
This feature is on hold until we have data in Herrenberg.

**Comment by samia-roubaa** [comment]
QA cycle done.
Some information are still missing:
- payment types
- occupancy status
- details URL

**Comment by Denis306** [comment]
@samia-roubaa
- What exactly do you mean by details URL?
- Occupancy status is missing apparently yes.
- Payment Types are displayed. ![image](https://user-images.githubusercontent.com/63004289/120476269-ad0b7d00-c3aa-11eb-8b51-366dedeabe63.png)

**Comment by samia-roubaa** [comment]
@Denis306 

It is written up in the description:
![image](https://user-images.githubusercontent.com/83356918/120478123-cdd4d200-c3ac-11eb-9ab9-ad6b1ae70088.png)

I couldn't find any URL to see more details of the eCharging Station as stated in the specs here.

**Comment by leonardehrenfried** [comment]
The stations in Herrenberg don't have URLs but the one for example in Echterdingen does: https://herrenberg.beta.stadtnavi.eu/ladestationen?lat=48.688517816135004&lng=9.16763886809349&stationId=1183&capacity=2&available=1

**Comment by Denis306** [comment]
@samia-roubaa  Yes I was just trying to see if we are talking about the same link.
As @leonardehrenfried mentioned we don't always have Links. But besides from that we don't have any "detail URL".

I am already coordinating regarding the Occupancy status.

**Comment by Denis306** [comment]
@patrickbeck1337 You can also close ticket #500 after you are done with this one. 
Here is also the info regarding the statuses again:https://github.com/ocpi/ocpi/blob/master/mod_locations.asciidoc#1422-status-enum

@leonardehrenfried as there sometimes is no data available regarding occupancy and also deeplinks in Herrenberg, do we want to put something instead of the occupancy status? Like the capacity? Or just leave it blank? @the-infinity implemented a status "UNKNOWN" when there is no data so we could simply do the capacity instead.

**Comment by leonardehrenfried** [comment]
If we don't know, then we could say something like "2 charging slots" rather than "2 of 2 charging slots available", isn't it?

**Comment by Denis306** [comment]
@leonardehrenfried yeah that's what I meant by "Capacity".

@patrickbeck1337 Just display the Capacity then if the status about the occupancy is set to UNKNOWN. 
And regarding the payments: Please display "RFID, App" if the Flag "REMOTE_START_STOP_CAPABLE" is set in the data.
