### ISSUE TITLE
Take car park capacity into account

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#362]
The backend has a sophisticated system for handling capacity of car parking lots.

We want to introduce two features:

## Using car park availability information

When setting the parameter `useVehicleParkingAvailabilityInformation=true` in the Park and Ride GraphQL request you will exclude parking lots that are full _right now_.
Because of this it should be set to true only when the search starts within 15 minutes of now.

## Almost full parking lots 

Stadtnavi has modified OTP to take into account when a car park is almost full and is displaying a warning to the user.

It should look like this:

![image5](https://user-images.githubusercontent.com/151346/115230032-15acdc00-a114-11eb-9e2e-d1a959d3d28b.png)

You should get this information the `tags` field of the `vehicleParking` entity in the GraphQL query. A full entity looks like this:

```
{
        "name": "Altstadtgarage",
        "lon": 8.872705,
        "lat": 48.593768,
        "capacity": {
          "carSpaces": 97
        },
        "availability": {
          "carSpaces": 58
        },
        "imageUrl": null,
        "tags": [
          "lot_type:Parkhaus",
          "address:Altstadtgarage",
          "forecast:false",
          "state:many"
        ],
        "anyCarPlaces": true
      }
```

A car park is considered almost full when it has the tag `state:few`.

In order to add the vehicleParking information you need to change the GraphQL query to include something like this: 

```
to {
          name
          bikePark {
            name
          }
          vehicleParkingWithEntrance {
            vehicleParking {
              tags
            }
          }
        }
```

## Excluding almost full parking lots

In order to exclude parking lots that are almost full you need to re-send the routing request with the following parameter:

```
bannedVehicleParkingTags: ["state:few"]
```

**Comment by andreashelms** [comment]
@leonardehrenfried How does `useVehicleParkingAvailabilityInformation=true` affect the response data? If I use `useVehicleParkingAvailabilityInformation=false` I still receive tags and capacity information within the response.
Does it affect the routing? Or could `useVehicleParkingAvailabilityInformation` always be set to true and the frontend can decide whether availability warnings are displayed or not?

**Comment by leonardehrenfried** [comment]
It does affect the routing (you won't be routed to full car parking lots) but doesn't affect the requested response.

If you set it always to true, you won't be routed to full car parking lots even when you're searching in the future. In the future however, we want to route to the _currently_ full ones as we don't know what's going to happen then.

**Comment by andreashelms** [comment]
Ok, got it.
