### ISSUE TITLE
Fix post-merge problems

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#365]
I've recently merged upstream's next branch into our next branch but the merge has been ugly and problematic.

Please look at the following problems:

- [x] map layer switcher looks inconsistent
- [x] make layer switcher scrollable on small screens
- [x] top left logo is too small (compare with https://herrenberg.stadtnavi.de)

**Comment by Denis306** [comment]
Which logo is too small?

**Comment by leonardehrenfried** [comment]
Updated

**Comment by aaronyamil** [comment]
Thanks @leonardehrenfried
