### ISSUE TITLE
Enable live bus map view

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#369]
DT1 has live bus display on the map. 

![Screenshot from 2021-04-20 17-43-08](https://user-images.githubusercontent.com/151346/115425452-ed9aa700-a1ff-11eb-8133-2f8679ad12ea.png)

The feature is has quite a few problems (very slow updates, unknown lines...) but we'd like to develop it further and get going with a first version.

Therefore get the code from https://github.com/stadtnavi/digitransit-ui/commit/37f0df78f2bbf381714891c67fa44a21c9c42692 and apply it to the next branch.

Please also copy the look of the popup from here: https://github.com/stadtnavi/digitransit-ui/blob/master/app/component/map/VehicleMarkerContainer.js#L171-L199

**Comment by derhuerst** [comment]
https://github.com/TheTransitClock/transitclockDocker/issues/12
