### ISSUE TITLE
Investigate why clicking on a bike rental station fails

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#374]
![Screenshot from 2021-04-28 17-12-44](https://user-images.githubusercontent.com/151346/116428301-1268cd00-a845-11eb-926f-101fe523787e.png)

When clicking on a bike rental station (from the sharing layer) an error occurs.

This is very likely down to the GraphQL API having changed slightly from OTP1 to 2.

Please investigate why the detail view fails and document which property is missing.

**Comment by optionsome** [comment]
https://github.com/HSLdevcom/OpenTripPlanner/pull/356 might fix this issue

**Comment by leonardehrenfried** [comment]
Fixed via https://github.com/opentripplanner/OpenTripPlanner/pull/3450
