### ISSUE TITLE
Add missing small icon for car sharing provider

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#379]
When you activate the map layer "Sharing", you can see that the small version of the car sharing provider icon is missing.

When you zoom in you can see the larger one.
![Screenshot from 2021-04-30 09-41-22](https://user-images.githubusercontent.com/151346/116664360-a39c8880-a998-11eb-85b0-3009465f938d.png)

But when you zoom out, it's gone. You can see in the console log what the name of the missing icon is.
![Screenshot from 2021-04-30 09-41-30](https://user-images.githubusercontent.com/151346/116664358-a26b5b80-a998-11eb-8d5b-712cfc341586.png)

Acceptance criteria

- [x] Take the icon from https://github.com/stadtnavi/digitransit-overpass-layers/blob/master/layer-icons/carsharing.svg
- [x] Use Inkscape or any other SVG editor to take one of the existing lollipop icons and put the car sharing icon on it
- [x] Add the small car sharing icon to the sprite

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried  I can see the icon:
![image](https://user-images.githubusercontent.com/8564142/116802295-b1a8f100-aadf-11eb-938d-a8ec4380e071.png)

I'm wrong?

**Comment by leonardehrenfried** [comment]
I'm talking about this one:

![116664360-a39c8880-a998-11eb-85b0-3009465f938d](https://user-images.githubusercontent.com/151346/116805969-61a34c00-ab2a-11eb-9390-6e71936b8817.png)

I disappears depending on the zoom level. Check the console for an error about a missing icon.

**Comment by leonardehrenfried** [comment]
And please work against the dev backend:

```
CONFIG=hbnext API_URL=https://api.dev.stadtnavi.eu yarn run dev
```
