### ISSUE TITLE
Missing icons in the "Nearby stops" list

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#387]
Icons for nearby Tram and Carpools are missing. Before fixing this, we should discuss the UX: do we want this list as is?

<img width="142" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117211644-939e0200-adf9-11eb-8e6b-1d28c485f2cd.png">

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-18 17-07-16](https://user-images.githubusercontent.com/151346/118676213-81f62a80-b7fb-11eb-8778-efbe38324e78.png)

I disabled the nearby view.
