### ISSUE TITLE
Nearby carpool stops and sharing locations fail to load

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#388]
After selecting nearby carpool stops or sharing locations, none is displayed but they seem to load infinetly, even though server sends a response. On the console, a couple of error messages are logged:
<img width="850" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117212316-7b7ab280-adfa-11eb-89b6-d33b351547b5.png">

<img width="754" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117212403-977e5400-adfa-11eb-9714-b3e8f22a084b.png">

<img width="407" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117212169-4a01e700-adfa-11eb-8fda-2e16ec2a6e9e.png">

**Comment by leonardehrenfried** [comment]
The carpool stops are fixed...

![Screenshot from 2021-05-07 11-36-59](https://user-images.githubusercontent.com/151346/117430656-9c412600-af28-11eb-8ce4-de10b0912e0b.png)

https://dev.stadtnavi.eu/inderhaehe/CARPOOL/POS/Herrenberg::48.595557,8.8674715

... but the sharing ones are not.

I will get @flaktack and team on the case.

**Comment by patrickbeck1337** [comment]
So this is a backend issue then?

**Comment by leonardehrenfried** [comment]
Yes, it's a backend issue.

**Comment by leonardehrenfried** [comment]
https://github.com/mfdz/OpenTripPlanner/issues/70
