### ISSUE TITLE
Bicycle stations display issues

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#390]
When selecting a bicycle station in the map, the internal id is shown and a potential capacity of 101 (a magic number we use to indicate that there bikes may be dropped off, even if all stands are in use)

<img width="457" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117212994-55a1dd80-adfb-11eb-9d1e-e7e4b4c84a08.png">

**Comment by hbruch** [comment]
The bar and the capacity should not be shown

**Comment by patrickbeck1337** [comment]
@hbruch I would suggest that we introduce a template for bug descriptions. It's quite hard to understand what's the expected vs. the actual behaviour, when you do not know the application very well.


My suggest would be following template.
```
How to reproduce:

1. Go to ...
2. Do ...

Actual behavior:
...

Expected behavior:
...
```

What do you think?

**Comment by patrickbeck1337** [comment]
I just adapted the displaying according to what we have in DT1. Please check the PR for the screenshot @hbruch if this is what the expected behaviour should be.

**Comment by MartinH-open** [comment]
> @hbruch I would suggest that we introduce a template for bug descriptions. It's quite hard to understand what's the expected vs. the actual behaviour, when you do not know the application very well.

> What do you think?

yes, definitely a good idea to avoid misunderstanding
