### ISSUE TITLE
Imprint, GDPR hint,

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#391]
Imprint an GDPR hint should show up in the menu. "Feedback senden" leads to the github repo (we don't want this, as we have a Feedback link linking a feedback form above). Copyright should be changed like in DT-1 (herrenberg.stadtnavi.de)

<img width="251" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117213447-e8db1300-adfb-11eb-9a34-3533e73b4e6a.png">

**Comment by patrickbeck1337** [comment]
@hbruch  whats the difference between those to options?

The "Feedback" options is already linking to https://stadtnavi.de/feedback/

Should "Feedback senden" option route to the same form/ url?

![image](https://user-images.githubusercontent.com/23075804/117265548-a1cd3c00-ae54-11eb-813b-0157b4da603a.png)
