### ISSUE TITLE
Changing transport modes results in showing no routings

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#395]
Scenario:
Chosen data:
1. Origin: Bahnhof Herrenberg, Bahnhofstraße 14, 71083 Herrenberg
2. To: Grundschule, Nelkenstraße 5, 71083 Herrenberg
3. With the following settings:
![image](https://user-images.githubusercontent.com/83356918/117133110-1a27f480-ada4-11eb-88bb-946106b0f0d1.png)

When I add the transport modes: Carpool and Sharing, the system showed the following message
![image](https://user-images.githubusercontent.com/83356918/117133312-607d5380-ada4-11eb-9387-e7f59c6be44a.png)

Expected behavior:
The system should have shown the same results if no new routes were found

**Comment by leonardehrenfried** [comment]
I think the reason for this was that we had not implemented Carpool on the backend. This has been fixed by https://github.com/mfdz/OpenTripPlanner/pull/67

**Comment by leonardehrenfried** [comment]
@samia-roubaa Can you try again on https://dev.stadtnavi.eu/ ?

**Comment by samia-roubaa** [comment]
Bug validation on QA system: failed

Scenario:
follow the same steps described in the main issue.
Without changing the settings, the app showed the following route suggestion:
![image](https://user-images.githubusercontent.com/83356918/118765975-1b652100-b87c-11eb-9ac3-e8d3fb8317ef.png)

After changing the settings, the app showed another routing suggestion without returning the one that has been shown before changing the settings:
![image](https://user-images.githubusercontent.com/83356918/118766068-39328600-b87c-11eb-8d83-cb1dac980603.png)

Expected behavior:
Both suggestions should be shown, as changing the settings "adds" other transportation modes and does not remove old ones.

**Comment by leonardehrenfried** [comment]
Unfortunately this is not how the routing backend works. 

Changing this will be a major undertaking and is definitely outside the scope of the project.

Is the originally reported problem resolved?

**Comment by samia-roubaa** [comment]
The original problem is solved, but could you please explain to me how the routing backend works. As I don't quite understand why not both suggestions can not be shown.

**Comment by leonardehrenfried** [comment]
When you select bike rental it forces the use of a bike rental leg but in Herrenberg there is only a single station. If you would want to combine it with bus you would have to go in a circle back to the train station and take the bike.

It would of course be ideal if you could show both bus and bike rental but we would have to change quite a bit to make this work.

**Comment by samia-roubaa** [comment]
Thanks a lot for the clarification.
I will close the issue.
