### ISSUE TITLE
No route shown when choosing the transport mode "car"

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#396]
Scenario:
inserted data:
Origin: Herrenberg
To: Gäufelden
The system shows the following available modes:
![image](https://user-images.githubusercontent.com/83356918/117133965-3ed09c00-ada5-11eb-85fc-0e738fe99a91.png)

When selecting the car mode, the system does not show any routing details
![image](https://user-images.githubusercontent.com/83356918/117134052-5d369780-ada5-11eb-9b33-e3bda2a3ce9e.png)

**Comment by leonardehrenfried** [comment]
@samia-roubaa could you paste the link from your URL bar, please?

**Comment by samia-roubaa** [comment]
https://herrenberg.qa.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/G%C3%A4ufelden%3A%3A48.5534259%2C8.8229748/car?time=1620213251

**Comment by samia-roubaa** [comment]
Bug validation on QA system: successful
