### ISSUE TITLE
Deeplinks currently will break when switching to DT-2

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#404]
The city of Herrenberg (and probably some users as well) uses deeplinks, e.g. to link a timetable at bus stops  (via 2D-code) or at an information point.

Currently, they seem to have changed in DT-next, which would break those use cases.

Example:
https://herrenberg.stadtnavi.de/POS/-/indernaehe vs
https://herrenberg.qa.stadtnavi.eu/POS/-/indernaehe

https://herrenberg.stadtnavi.de/haltestellen/hbg%3Ade%3A08111%3A6014%3A1%3A2 vs https://herrenberg.qa.stadtnavi.eu/haltestellen/hbg%3Ade%3A08111%3A6014%3A1%3A2

**Comment by MartinH-open** [comment]
@hbruch - you mean kind of QR Codes that use direct deep links to some application link ???
( Beat them !   DO NOT do this. )
If QR Codes need to reference some point of information then first a permanent mapping service from ID to deep link URL should be introduced that can handle all kinds of app URL changes in all future!
Anyhow the ID strings for points of interest (or service of interest) could be much shorter then the long deep links.
And for QR codes the string sizes matters. The shorter the strings the smaller the QR code image and the better it can be decoded by users (given a fixed size).

**Comment by leonardehrenfried** [comment]
Both URLs work now on the beta system.
