### ISSUE TITLE
Not all zoom levels are present

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#407]
The following zoom levels are missing:
50km, 30km and 3km

QA:
 image: mfdz/opentripplanner:otp2-3a2df966e9c9651305968ba22c6f2ea7fb98e255
 image: stadtnavi/digitransit-ui:35b607d8bcb728fb7ad701964375b024dbcb478b
 image: stadtnavi/hsl-map-server:755d5aa0e00d9970ada283f5c4db75bd77982cfa

**Comment by hbruch** [comment]
I suppose this was an upstream change. I'd stay with the currently implemented scales, unless there is explicit demand for them.
