### ISSUE TITLE
Black mode colors in settings

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#412]
Current behavior:
When opening the settings panel, the Bus and Train mode symbols appear in black.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/2187389/117529395-a2421000-afd7-11eb-869d-3bfad5d20ab4.png">

Expected behavior:
Like in Herrenberg.stadtnavi.de, they should appear in red and green
<img width="381" alt="image" src="https://user-images.githubusercontent.com/2187389/117529421-c9004680-afd7-11eb-9011-a1d3e29b6ab1.png">

**Comment by MartinH-open** [comment]
Are these colors based on some international standards for different modes of transportation ?
Or just a matter of personal preferences ?  For the later colors an other attributes should be some customizable somewhere.
---
here - bit strange the dark green background of the S-Bahn / Zug logo does not match the background green. For the red bus it matches well.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-10 14-27-38](https://user-images.githubusercontent.com/151346/117659154-e2ea8680-b19b-11eb-80ad-6f0a0591b4f7.png)

I'm seeing the colourful icons, @hbruch. We had this problem before but I cannot remember how we solved it. Can you?

What happens when you force-reload the page?

**Comment by hbruch** [comment]
On firefox, I see colors too, but not on Safari (MacOS). Might be related to the following exceptions in the browser console log:
![grafik](https://user-images.githubusercontent.com/2187389/117922056-26570900-b2f2-11eb-86ba-e9f9d0c5ec02.png)
