### ISSUE TITLE
Haltestellen page has no styling applied on reload

### ISSUE THREAD

**Issue by patrickbeck1337** [stadtnavi/digitransit-ui#413]
**How to reproduce**

1. Open [Stadtnavi](https://dev.stadtnavi.eu/) and enter a route
2. Select a proposed route
3. Click on one of the station to navigate to the "Haltestellen" page
4. Reload the page

**Actual behaviour**
The HTML is rendered without styling

**Expected behaviour**
The page is rendered a soon as the styling is applied to the HTML

**Comment by andreashelms** [comment]
@patrickbeck1337 I cloud no reproduce that issue. Can you please provide some more information or screenshots? Thanks!
