### ISSUE TITLE
No metro stations shown

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#417]
Stuttgart city centre has metro stations but they are not shown on the map, when you activate the layer:

![Screenshot from 2021-05-10 15-24-40](https://user-images.githubusercontent.com/151346/117666175-e1bd5780-b1a3-11eb-83ec-ae32303853a3.png)

When viewing nearby metro stations you can definitely see that they are there:

![Screenshot from 2021-05-10 15-24-18](https://user-images.githubusercontent.com/151346/117666188-e550de80-b1a3-11eb-960c-fc7b0c53ade9.png)

Also, when you decode one of the binary map tiles with the following command

```
curl https://api.dev.stadtnavi.eu/routing/v1/router/vectorTiles/stops/17/68878/45132.pbf | protoc --decode_raw
```
you can definitely see stations with the type `SUBWAY`.

I suspect the error is somewhere in the file `Stops.js`.

**Comment by leonardehrenfried** [comment]
There are not many Mitfahrpunkte, but there is one near the Autobahn.

![Screenshot from 2021-05-10 12-23-34](https://user-images.githubusercontent.com/151346/117645181-98acd980-b18a-11eb-9ee2-1c1375bcde6f.png)

But you're right: in central Stuttgart there should be metro stations, but none are displayed.
