### ISSUE TITLE
UI: Page title gets trimmed

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#418]
Scenario:
- Choose to show "Bahnhöfe"
- Choose the Haltstelle with S1 trains
- The system will display the schedule of the S1 trains and the title will be trimmed
![image](https://user-images.githubusercontent.com/83356918/117572334-bf0f3e00-b0d2-11eb-9d1d-dc66f42f1cb6.png)

Also when you open the details of any train, the title will still be trimmed
![image](https://user-images.githubusercontent.com/83356918/117572380-ea922880-b0d2-11eb-825a-7813041ce17a.png)

QA verion:
image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

**Comment by hbruch** [comment]
Will close #422 as duplicate of this issue. So be aware that clipping not only happens on the left pane but as well on the right pane. Does this happen upstream as well? If yes, we should propose a PR there as well.

**Comment by patrickbeck1337** [comment]
> @patrickbeck1337 Presumably you wanted to fix this when committing this: [684b03e](https://github.com/stadtnavi/digitransit-ui/commit/684b03ecbd0873c42bfa87d0fd9df1c8f1df29d1)
> 
> Correct?
> 
> This _does_ fix the text moving up, but it also disable the separate scroll bar for the layer switcher and the left hand panel.
> 
> ![Screenshot from 2021-05-10 17-39-05](https://user-images.githubusercontent.com/151346/117685962-b2641600-b1b6-11eb-8469-0309c190f609.png)
> 
> Can you look into this?

Yes I fixed that with the direct commit on the next branch. Should start doing that. Will never do it again sorry.


I added a custom overwrite we had which was removed due to the hsl/next merge => https://github.com/stadtnavi/digitransit-ui/commit/b4324c4c2e112aadc7e4620d9ac133e890efb1fb

**Comment by leonardehrenfried** [comment]
Not a problem. Thanks for the fix.

**Comment by leonardehrenfried** [comment]
I will keep the ones reported by the QA team open, so that they can close them themselves.

**Comment by samia-roubaa** [comment]
Bug validation on QA system: successful
