### ISSUE TITLE
UI: Layout issue when choosing a Sharing-Angebot

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#419]
Scenario:
- Choose to show "Sharing-Angebote" on the map
- Click on the Sharing-Angebot spot on the map to see its details
- The system shows an unaligned black circle around the location
![image](https://user-images.githubusercontent.com/83356918/117572630-0a761c00-b0d4-11eb-8f82-96ba8919d806.png)
![image](https://user-images.githubusercontent.com/83356918/117572636-0cd87600-b0d4-11eb-9528-dcc5430f8e8c.png)
![image](https://user-images.githubusercontent.com/83356918/117572638-106bfd00-b0d4-11eb-8103-aa0eb5a98347.png)

And sometimes when you click on another Sharing-Angebot, the black circle does not disappear from the previous spot you clicked and does not appear around the one you just chose:
![image](https://user-images.githubusercontent.com/83356918/117572670-30032580-b0d4-11eb-8128-4d33afa32494.png)

QA version:
image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

**Comment by jpidelatorre** [comment]
This problem is also present upstream. So, as discussed with @leonardehrenfried, I'm working on a formula that consistently centers the selection circle correctly.

This is how it looks upstream at certain zoom levels:
![image](https://user-images.githubusercontent.com/104569/120683855-199a8080-c46c-11eb-92a5-7e624bb36609.png)

**Comment by ahmed-nawar** [comment]
The circle is removed
