### ISSUE TITLE
Title of layer switcher is not shown

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#422]
Current behavior:
The title of the layer switcher disappears behind the header bar:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2187389/117639451-3650da80-b184-11eb-96ad-73e9fc80b333.png">

Expected behavior:
The layer-Switcher is not partially hidden by the header bar, especially the title "Show on map" is visible

**Comment by leonardehrenfried** [comment]
#418 is currently at the top of the board and will be pulled next.

**Comment by hbruch** [comment]
Closing as duplicate of #418
