### ISSUE TITLE
Roadworks layer: Roadworks partly disappear, depending on zoom level

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#425]
Current behavior:
For some (possibly long distance) roadworks, parts of the display disappear, e.g. for [this one close to Grabenstetten](https://dev.stadtnavi.eu/Grabenstetten%3A%3A48.5244177%2C9.4612632/-)
<img width="424" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117661533-c6038280-b19e-11eb-85b5-a249c4952b6f.png">

<img width="581" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117661579-d0258100-b19e-11eb-93ac-aee3a33e7265.png">

Expected behavior:
The roadwork should be visible completely.

**Comment by hbruch** [comment]
Might this be a tilelive issue then?

**Comment by hbruch** [comment]
But looks like a tiling issue, yes. Like in this case near by as well

<img width="217" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117662258-a6208e80-b19f-11eb-950e-6b6ccb8991b8.png">

**Comment by leonardehrenfried** [comment]
Over night I also had another idea what could be the problem: maybe my code always assumed that it's always a single polyline per tile but in the example above there are several.
