### ISSUE TITLE
Parkplatz free places are not calculated

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#428]
I opened the details of the Parkplatz "Stuttgarter Straße - Parkplatz für Menschen mit Behinderung"
The free places were not calculated and the following appeared: {total} Stellplätze
![image](https://user-images.githubusercontent.com/83356918/117717144-b9048480-b1da-11eb-8b52-ad17ee8203aa.png)

QA version:
 image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
 image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
 image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
 image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

**Comment by leonardehrenfried** [comment]
Fixed via https://github.com/stadtnavi/digitransit-ui/commit/4eacf8b2d52e6ee9f94d871244095fafad2460f1

**Comment by samia-roubaa** [comment]
Bug validation on QA system: successful

Another issue rose: #467
