### ISSUE TITLE
Parking details: Missing notes

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#437]
Current behavior:
In next branch, the parking details don't show additional notes.

<img width="308" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117824959-31b52080-b26f-11eb-8a07-0521f63d7ade.png">

Expected behavior: 
Like in ol digitransit, the (language dependent) notes should be displayed
<img width="324" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117824727-003c5500-b26f-11eb-876f-0f9c4598cdbc.png">

**Comment by aaronyamil** [comment]
Hi Leonard,
I created this PR https://github.com/stadtnavi/digitransit-ui/pull/444 for this ticket. Thanks.
