### ISSUE TITLE
Parking places: Missing availability indicator

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#451]
It is written in the user stories, that the parking places will have a badge that the indicates the availability:
- green tick: if it has empty slots
- red cross symbol: if it's occupied

Current behavior:
These indicators are missing
![image](https://user-images.githubusercontent.com/83356918/117960175-0852ce00-b31d-11eb-9c12-7d781a3259a0.png)
![image](https://user-images.githubusercontent.com/83356918/117960227-156fbd00-b31d-11eb-974d-6b18b37df56f.png)
 
QA version:
 image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
 image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
 image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
 image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

**Comment by MartinH-open** [comment]
"Oberer Graben"  - what a great table of opening hours.
Basically this location is open 24h all year. 
So, for such cases a text like "always open" oder "immer geöffnet" would be better instead of long table.
If exceptions happen you can list them: like "but closed on Easter Monday 14. April 202X"

**Comment by aaronyamil** [comment]
Hi @samia-roubaa and @leonardehrenfried 
I can see these indicators in dev environment:
![image](https://user-images.githubusercontent.com/8564142/118346561-89bb8380-b50a-11eb-8f31-b85036d89d9c.png)
What is the rule for this indicators? What is the expected?
Because in some Parking places there is not the indicator:
![image](https://user-images.githubusercontent.com/8564142/118346619-d30bd300-b50a-11eb-9bcb-b5f1b8c8b08b.png)

**Comment by hbruch** [comment]
Please compare https://github.com/stadtnavi/digitransit-ui/blob/next/app/component/map/tile-layer/DynamicParkingLots.js in master and next branch. You will see that some state is currently not taken into account in next.

**Comment by aaronyamil** [comment]
Thanks for the help @hbruch 
I compared this file between two branches. In the next branch the parking place only have badge if inside the properties has **free** field. But we have another Parking places without **free** field, please see the following:
- with free field 
![image](https://user-images.githubusercontent.com/8564142/118385569-eb98ed80-b5dd-11eb-8cd2-8507d86ecbfd.png)
- without free field
![image](https://user-images.githubusercontent.com/8564142/118385570-f81d4600-b5dd-11eb-9331-61126fa0f383.png)
For this reason the badges are in some parking places and not in all.

I created a PR https://github.com/stadtnavi/digitransit-ui/pull/458 using the Master branch as guide for adding more conditionals if the Parking place does not have **free** field. I assigned to @leonardehrenfried for the review. 
![image](https://user-images.githubusercontent.com/8564142/118385678-264f5580-b5df-11eb-8a90-2abd04b2bbd2.png)

**Comment by hbruch** [comment]
Wohnmobilhafen is closed according to popup, but has no indicator
<img width="349" alt="grafik" src="https://user-images.githubusercontent.com/2187389/118632598-dfc14d00-b7d0-11eb-98d4-2881b7cd54c8.png">

**Comment by leonardehrenfried** [comment]
Where are you seeing this?

![Uploading Screenshot from 2021-05-18 12-04-12.png…]()

**Comment by hbruch** [comment]
Could not reproduce, my fault

**Comment by samia-roubaa** [comment]
Some parking places have the indicator and others don't
![image](https://user-images.githubusercontent.com/83356918/118788621-3f346100-b894-11eb-838b-89908f60c482.png)

**Comment by hbruch** [comment]
That's ok as not for all parkings we have real time information available. These are shown without indicator

**Comment by leonardehrenfried** [comment]
This is because only some parking lots have the parking sensors.

**Comment by samia-roubaa** [comment]
Thank you for the clarification.
Issue will be closed.

**Comment by MartinH-open** [comment]
The StadtNavi User might not know about this (whether parking sensors are available or related to the indicator).
Either have some other indicator (grey = unknown) or in the detail screen explain that the green indicator information is based on parking sensors for that location
