### ISSUE TITLE
No transit routes returned in safari

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#452]
Requesting the following journey returns no transit results in Safari (MacOS):
https://dev.stadtnavi.eu/reiseplan/Holzapfel%2C%20Römerweg%2C%2071083%20Herrenberg%3A%3A48.613789022229%2C8.847341537475588/ASID%20BONZ%20GmbH%2C%20Hertzstraße%203%2C%2071083%20Herrenberg%3A%3A48.576720706024986%2C8.891372680664064?time=1620823379

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/2187389/117977294-f2e79f00-b330-11eb-8357-9d11bb1ce2fd.png">

Expected behavior:
Transit results are shown as e.g. in Firefox:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/2187389/117977150-d186b300-b330-11eb-82e0-b8cd1c878cb8.png">

**Comment by leonardehrenfried** [comment]
My gut feeling is that there is an incorrect list of modes sent to the backen.

**Comment by hbruch** [comment]
Seems like this was caused by having enabled wheelchair routing in Safari, so closing this.
