### ISSUE TITLE
Apply new Panel UI to eCharging Station info

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#456]
Once ticket #353, #500 & #344 are implemented we will be chaning the UI for the eCharging station info.
Design:
![image](https://user-images.githubusercontent.com/23075804/119534184-ec244780-bd86-11eb-9756-506ac66a4850.png)

**Comment by the-infinity** [comment]
For displaying the connectors you can use these icons: https://github.com/binary-butterfly/charging-station-connector-icons .

**Comment by the-infinity** [comment]
... after some testing: here will be another revision of the icons without fonts dependencies.

**Comment by leonardehrenfried** [comment]
Is it clear what we want to show here? Does Sandra need to be involved?

**Comment by the-infinity** [comment]
Here you have the npm package: https://www.npmjs.com/package/react-charging-station-connector-icons

**Comment by Denis306** [comment]
This issue is resolved in ticket #344.
