### ISSUE TITLE
Sharing vehicle popup strings should be vehicle type specific

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#461]
The [new car-sharing data](https://github.com/stadtnavi/static-gbfs-feeds/pull/6) feed provides deep links for a couple of stations, especially in Stuttgart. The popup handles them, but displayed messages cover only the vehicle type bicycle: 

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2187389/118472136-ca80eb80-b708-11eb-9abb-960580296d63.png">

OTP reply should return the vehicle_type `form_factor` introduced with GBFS 2.1 and Digitransit should define messages for the different form factors. Note that we'll introduce an additional form_factor `cargo` (which for now only will be caargobikes, Lastenrad).

### Acceptance criteria

(This is probably done best by a German)

- Go through the car sharing and taxi UI (popups, panes)
- Replace the word Leihräder/rental bike with something that makes sense in the context of the vehicle
- Fix display of -1/99 availability

**Comment by hbruch** [comment]
As adding form_factor (= supporting GBFS 2.1) in OTP is a larger feature, please handle that on client side for now by mapping e.g. network to vehicle type car.

**Comment by samia-roubaa** [comment]
QA cycle done
