### ISSUE TITLE
Adjust UI to display bike rental warnings

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#465]
![115232399-ee0b4300-a116-11eb-9df2-7ae0198b2e41](https://user-images.githubusercontent.com/151346/118677764-cafaae80-b7fc-11eb-8e88-e316610195ee.png)

OTP1 has a feature to allow you to drop a bike anywhere even when you're supposed to bring it back to a station. The UI should display a warning though (see above screenshots).

We added the feature to OTP2 but the API response looks a little different and needs to be added to the GraphQL query.

## Acceptance criteria
- Plan a route from Nufringen to Kuppingen
- Enable bike sharing, disable bus
- See that no warning is displayed in the UI
- Modify GraphQL query to return the property and adjust UI

@flaktack Can you please describe how to modify the graphql query to get the results?

**Comment by flaktack** [comment]
The following plans a trip where the bicycle is kept on arrival using https://api.dev.stadtnavi.eu/otp/routers/default/index/graphql
```graphql
query{
  plan(
    from: { lat: 48.59432, lon: 8.85884 }
    to: { lat: 48.59045, lon: 8.87225 }
    transportModes: [
      { mode: BICYCLE, qualifier: RENT }
    ],
    maxWalkDistance: 10000
    allowKeepingRentedBicycleAtDestination: true
  ) {
    itineraries {
      arrivedAtDestinationWithRentedBicycle
      legs {
        mode
        rentedBike
        distance
        startTime
        endTime
        
        from {
          name
        }
        to {
          name
        }
      }
    }
  }
}
```

Response:
```
{
  "data": {
    "plan": {
      "itineraries": [
        {
          "arrivedAtDestinationWithRentedBicycle": true,
          "legs": [
            {
              "mode": "WALK",
              "rentedBike": false,
              "distance": 285.30100000000004,
              "startTime": 1621354598000,
              "endTime": 1621354909000,
              "from": {
                "name": "Origin"
              },
              "to": {
                "name": "Bhf. Herrenberg / Kalkofenstraße"
              }
            },
            {
              "mode": "BICYCLE",
              "rentedBike": true,
              "distance": 1438.3089999999995,
              "startTime": 1621354909000,
              "endTime": 1621355287000,
              "from": {
                "name": "Bhf. Herrenberg / Kalkofenstraße"
              },
              "to": {
                "name": "Destination"
              }
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by leonardehrenfried** [comment]
Not sure if I said it in a dev meeting before: `allowKeepingRentedBicycleAtDestination: true` is already set by the backend and the frontend doesn't need to set it.

What you need to do is add the property `arrivedAtDestinationWithRentedBicycle` to the query and then process it when you get a response from the server.

**Comment by leonardehrenfried** [comment]
If I remember correctly then in the old API we returned the translated messages. In the new one we don't do that anymore and you will have to add the messages to the frontend.

**Comment by leonardehrenfried** [comment]
The texts are:

de: Ziel ist keine Rückgabestation. Ausleihe kann hier nicht abgeschlossen werden. Anbieterabhängig fallen weiter Gebühren bis zur Rückgabe an einer Station an.

en: Rental cannot be completed here. Please check terms & conditions for additional fees.

**Comment by samia-roubaa** [comment]
QA cycle done.
Related bug created: #551
