### ISSUE TITLE
When clicking on a Sharing-Angebot location the icon disappears

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#468]
Scenario:
1. Go to https://herrenberg.qa.stadtnavi.eu/
2. Choose to show Sharing-Angebote
3. Click on any Sharing-Angebot location
4. The icon will disappear
![image](https://user-images.githubusercontent.com/83356918/118771142-7b5ec600-b882-11eb-9bc0-1722001cde5d.png)
5. To be able to show the icon again, you will have to zoom out
![image](https://user-images.githubusercontent.com/83356918/118771263-a6491a00-b882-11eb-917a-eb17251ff5b7.png)

Expected behavior:
The icon should not disappear

QA system version:
 image: mfdz/opentripplanner:otp2-15fd09f6e08683d05cfe96e1400a33356d17afa9
 image: stadtnavi/digitransit-ui:b10a74a97df348e1962ffc454571053966332520
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b80f1ce50fff9b72be5e9f8b02e0b374c7c5c833
Last version change: 2021-05-18T17:38:58+0200

**Comment by patrickbeck1337** [comment]
Fix it, but there is apparently a new issue with the map layer settings. Due to some reasons the hsl default options are all true.
@leonardehrenfried should/ can we open a new ticket for this one?

**Comment by leonardehrenfried** [comment]
Yes please.

**Comment by leonardehrenfried** [comment]
In fact we can ask Joell today if this is a bug or a feature.
