### ISSUE TITLE
A missing unified view for the Öffnungszeiten

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#469]
The view of the Öffnungszeiten varies a lot between several POIs.
The view should be unified.

ex. POI: Parking place
![image](https://user-images.githubusercontent.com/83356918/118772504-1d32e280-b884-11eb-8efe-ba592f3daa7c.png)

ex. POI: Rund um's Fahrrad
![image](https://user-images.githubusercontent.com/83356918/118773437-1f497100-b885-11eb-99c7-db9f356f194f.png)

ex. POI: Nette Toilette
![image](https://user-images.githubusercontent.com/83356918/118773507-338d6e00-b885-11eb-8df7-bb471cb7ab3f.png)

QA system version:
 image: mfdz/opentripplanner:otp2-15fd09f6e08683d05cfe96e1400a33356d17afa9
 image: stadtnavi/digitransit-ui:b10a74a97df348e1962ffc454571053966332520
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b80f1ce50fff9b72be5e9f8b02e0b374c7c5c833
Last version change: 2021-05-18T17:38:58+0200

**Comment by andreashelms** [comment]
I don't think this is a bug, but a feature request. At the moment opening hours are formatted this this in data source `bicycleinfrastructure.geojson` and have to be changed everywhere inside of it:

`        "popupContent_de": "Telefon: +49 7073 852520, \u00d6ffnungszeiten: Mo-Di 17:00-20:00, Do-Fr 17:00-20:00, Sa 10:00-14:00;Barrierefrei: nein",`

@Denis306 Should we do this with priority, though?

**Comment by leonardehrenfried** [comment]
No, this is a low priority ticket.

**Comment by jpidelatorre** [comment]
Actually, the component `OSMOpeningHours` already deals with strings in that format. I added the component to the popup that appears out of GeoJSON markers.

**Comment by samia-roubaa** [comment]
QA validation failed.

The layout of the opening hours of the bicycle infrastructure and public toilets is still not fixed
![image](https://user-images.githubusercontent.com/83356918/120376929-c1a13400-c31c-11eb-9e7e-57d587b9d8b8.png)
![image](https://user-images.githubusercontent.com/83356918/120376941-c36af780-c31c-11eb-8f23-b9ab0f37c055.png)

**Comment by leonardehrenfried** [comment]
@samia-roubaa O'm going to close this as the it has been like this on the production site for a long time and the client isn't too unhappy with it. It could use improvement, sure, but it's not a priority at the moment.
