### ISSUE TITLE
Sharing icons broken in Chrome

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#472]
## Steps to reproduce

1. Visit http://localhost:8080/fahrradstationen/80104?locale=de
2. Zoom in and out a bit
3. See error on console

![Screenshot from 2021-05-19 12-07-18](https://user-images.githubusercontent.com/151346/118795411-d7cddf80-b89a-11eb-9ad3-aa103a00aac1.png)
![Screenshot from 2021-05-19 12-07-09](https://user-images.githubusercontent.com/151346/118795421-d997a300-b89a-11eb-8a1e-e146915d372c.png)

It seems that there is a syntactical error in the SVG. Strangely it works in Firefox.

**Comment by andreashelms** [comment]
@leonardehrenfried Actually I don't see any differences between Firefox and Chrome. What icon should be visible there?

**Comment by leonardehrenfried** [comment]
In firefox if you zoom in an out again, you can see the icon coming back.

![Screenshot from 2021-05-20 09-42-07](https://user-images.githubusercontent.com/151346/118939181-b1b64700-b94f-11eb-942d-d627083d58bb.png)

**Comment by leonardehrenfried** [comment]
So there are two issue with these icons: this one and this https://github.com/stadtnavi/digitransit-ui/issues/468

**Comment by jpidelatorre** [comment]
The last commit in #489 fixes the error that appears in the console. But, the problem with the icons persists.

The problem here is that `drawCitybikeIcon` is not being called during the first rendering. I've been trying to figure out the reason. But the flow is too complicated to figure out within this timeframe.

**Comment by samia-roubaa** [comment]
QA validation successful
