### ISSUE TITLE
"Suche nach Haltestellen oder Linien" is not working

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#474]
Scenario:
1. Go to https://herrenberg.qa.stadtnavi.eu/
![image](https://user-images.githubusercontent.com/83356918/118804314-d86b7380-b8a4-11eb-9bbe-5c8a8e321a93.png)

2. Try to search for the Bushaltestelle "Herrenberg Reinhold-Schick-Platz in the search field "Suche nach Haltestellen oder Linien"
![image](https://user-images.githubusercontent.com/83356918/118804484-0b156c00-b8a5-11eb-868d-a93ff3b204d4.png)

3. The system shows an error message
![image](https://user-images.githubusercontent.com/83356918/118804587-2aac9480-b8a5-11eb-91a2-0f01dba2b3e3.png)

Generally the search is not working, I tried many cases with Bahnhöfe, etc. but the search does not work and always returns an error.

**Comment by leonardehrenfried** [comment]
It looks like it has something to do with the paths, which I fixed upstream: https://github.com/HSLdevcom/digitransit-ui/pull/3747

**Comment by leonardehrenfried** [comment]
This search box has been completely removed.

**Comment by samia-roubaa** [comment]
QA validation: search was temporarily removed
