### ISSUE TITLE
Bus info - missing translation in Fahrplan

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#475]
Scenario:
1. Go to "herrenberg.qa.stadtnavi.eu"
2. Search for 
    Start: Kreiskrankenhaus, Marienstraße
    Ziel: Grundschule, Nelkenstraße
![image](https://user-images.githubusercontent.com/83356918/118814940-fdfe7a00-b8b0-11eb-808d-ee3b6f6d4f44.png)

3. Click on the first routing suggestion, the system will open the details of the routing suggestion
![image](https://user-images.githubusercontent.com/83356918/118815009-12427700-b8b1-11eb-8c91-bf2f99d8d045.png)
 
4. Click on the red bus icon, and open the tab "Fahrplan"
5. Next to the date you will find the option "other-dates" and beneath it you will find other tabs titled in Finnish
![image](https://user-images.githubusercontent.com/83356918/118815285-5e8db700-b8b1-11eb-9721-edac5390782e.png)

Expected behavior:
The option other-dates should be translated, as the chosen language is German.
The tab titles should be translated in English and German (according to the chosen language)

QA system version:
 image: mfdz/opentripplanner:otp2-15fd09f6e08683d05cfe96e1400a33356d17afa9
 image: stadtnavi/digitransit-ui:b10a74a97df348e1962ffc454571053966332520
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b80f1ce50fff9b72be5e9f8b02e0b374c7c5c833
Last version change: 2021-05-18T17:38:58+0200

**Comment by leonardehrenfried** [comment]
This also happens upstream: https://reittiopas.hsl.fi/linjat/HSL:2200/aikataulu/HSL:2200:1:01?locale=en

**Comment by leonardehrenfried** [comment]
Upstream ticket: https://github.com/HSLdevcom/digitransit-ui/issues/4173

**Comment by leonardehrenfried** [comment]
Upstream Jira: https://digitransit.atlassian.net/browse/DT-4689

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-20 12-31-36](https://user-images.githubusercontent.com/151346/118963990-54c68b00-b967-11eb-9f8b-9955cb0f1edc.png)
