### ISSUE TITLE
UI should use route_color & route_text_color from the GTFS data

### ISSUE THREAD

**Issue by derhuerst** [stadtnavi/digitransit-ui#479]
https://dev.stadtnavi.eu/reiseplan/Heidelberg%3A%3A49.4093582%2C8.694724/Friedrichshafen%3A%3A47.6505715%2C9.4797531/0?time=1621428478

<img width="423" alt="Screenshot 2021-05-19 at 16 33 09" src="https://user-images.githubusercontent.com/5072613/118841101-e975ae00-b8bf-11eb-9e17-40f5252b32c5.png">

The itinerary shows e.g. the "T10-A"/"RE10a" leg as all-while (foreground and background), even though the data contains both a `route_color` (intended for the background) and a `route_text_color` (intended for the foreground):

```csv
agency_id,route_id,route_short_name,route_long_name,route_type,route_color,route_text_color,eligibility_restricted
AB,90-T10-A-j21-1,T10-A,RE10a,2,ffffff,000000,-999
```

**Comment by Denis306** [comment]
For now we are not going to work on this issue. But if this happens we will filter it out and change the color to black.
