### ISSUE TITLE
Can't store bus stop as favorite

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#481]
How to reproduce:
1. Select a bus stop in map
2. In stop panel, press the star to store a favorite

Current behavior:
A (half untranslated) error message pops up:
<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/2187389/118930037-8b8ba980-b945-11eb-99ab-f9fea780c344.png">

Reason: 
This is caused by a currently not supported geocoder api request: 
<img width="1063" alt="grafik" src="https://user-images.githubusercontent.com/2187389/118930156-aeb65900-b945-11eb-8e54-85fd32ed41a1.png">
https://photon.stadtnavi.eu/pelias/v1/place?ids=gtfshbg%3Astop%3AGTFS%3Ahbg%3Ade%3A08115%3A5773%3A3%3A3

This would take some time to fix, so for now, please disable the star.

**Comment by samia-roubaa** [comment]
QA validation: the star is disabled
