### ISSUE TITLE
User Feeback: remove map layer "Straßenwetter"

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#483]
The temperature sensor is not working correctly, therefore, the "Straßenwetter" has to be removed from the system until the sensor gets fixed. 
![image](https://user-images.githubusercontent.com/84382750/118965333-dec32380-b968-11eb-97e4-d63beab68c0a.png)

**Comment by leonardehrenfried** [comment]
What is your time zone?

For me it looks like this:

![Screenshot from 2021-05-20 12-49-15](https://user-images.githubusercontent.com/151346/118966281-dfa88500-b969-11eb-9920-dc5b1fa24347.png)

**Comment by leonardehrenfried** [comment]
Or hang on, is it the precipitation that is the problem?

**Comment by sara-georgy** [comment]
This issue was reported on monday at 01:57am. 
Regardless of the time zone, TUG confirmed that there is a problem in the sensor itself. So until the problem gets fixed from their side we want to remove the Straßenwetter temporarily from the map.

**Comment by leonardehrenfried** [comment]
The weather sensor at Enzstrasse has been removed.

**Comment by sara-georgy** [comment]
validated
