### ISSUE TITLE
Popup not shown

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#485]
In firefox, open dev system, press "+" (zoom in) three times and select the car sharing station at the main station.

The popup is not displayed, only the close buttton "x" and bulb arrow are rendered
  
<img width="305" alt="grafik" src="https://user-images.githubusercontent.com/2187389/118968972-d2d96080-b96c-11eb-8dec-f6882c4b24e8.png">

**Comment by jpidelatorre** [comment]
Can't reproduce the error. Clicking on a Car Sharing marker re-renders the map and the popup appears complete.

**Comment by jpidelatorre** [comment]
@leonardehrenfried I believe this can be closed, right?
