### ISSUE TITLE
Future route is navigated to with incorrect path

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#491]
## Steps to reproduce

- Plan a route from Herrenberg to Stuttgart starting tomorrow
- Go back to start page
- Plan the same route again but select the previously store route from the second drop down like highlighted here
![Screenshot from 2021-05-21 10-28-54](https://user-images.githubusercontent.com/151346/119107459-89961900-ba1f-11eb-830a-3361affcde15.png)
- Notice the the path navigated to contains the finnish "reitti" rather than the German "reiseplan".

This should have been fixed through [this upstream PR](https://github.com/HSLdevcom/digitransit-ui/pull/3747/) but it seems it got broken again somewhere along the road.

**Comment by leonardehrenfried** [comment]
Strangely, when you inspect your localstorage you can clearly see that the future route is stored with the correct URL starting with "/reiseplan".

**Comment by samia-roubaa** [comment]
QA validation successful
