### ISSUE TITLE
Routing suggestion "walking" does not appear on the web app unlike the mobile app

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#494]
Scenario:

1. Go to 'https://herrenberg.beta.stadtnavi.eu/'
2. Type in Start: Marktplatz Herrenberg
3. Type in Ziel: CAP-Markt Herrenberg
4. The web app will show the "on wheel" options
5. Open the IOS app
6. Search for the same route (Step 2 & 3)
7. The app will only show the option "walking"

Expected behavior:
The "walking" option should also be shown on the web app

![image](https://user-images.githubusercontent.com/83356918/119253737-e37b1800-bbb2-11eb-9a2b-1bedf74845ae.png)
![image](https://user-images.githubusercontent.com/83356918/119253741-e5dd7200-bbb2-11eb-83d8-944dd3570ac9.png)

Beta System version:
 image: mfdz/opentripplanner:otp2-d8feafd22c10c0cfd85b212112d4577f56dd87d6
 image: stadtnavi/digitransit-ui:e45448f44aeac7bb23787e02b3a42243de8dd7ac
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b80f1ce50fff9b72be5e9f8b02e0b374c7c5c833
Last version change: 2021-05-21T17:26:22+0200

**Comment by Denis306** [comment]
I checked in HSL and the routing also shows both "walking" and "Bike" options. 
![image](https://user-images.githubusercontent.com/63004289/119567474-a8443900-bdac-11eb-957d-b18905b8992e.png)

**Comment by Denis306** [comment]
@samia-roubaa I am closing this issue as it is fixed.
![image](https://user-images.githubusercontent.com/63004289/120860765-7d18d100-c586-11eb-8eec-e65420288de5.png)
