### ISSUE TITLE
User Feedback 191: location icon does not land in the center of "Oberjesingen"

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#496]
When the user chooses the location "Oberjesingen, Herrenberg" in his route, the location icon lands in the middle of the fields and not in the center. (See Screenshot)

![image](https://user-images.githubusercontent.com/84382750/119262279-f0136680-bbda-11eb-942a-c15bb8812e78.png)

**Comment by hbruch** [comment]
Additional examples:
[Kuppingen]( https://herrenberg.stadtnavi.de/Kuppingen%2C%20%20Herrenberg%3A%3A48.611011149999996%2C8.832897832205557/-/indernaehe?time=1622130897)
[Oberjesingen](https://herrenberg.stadtnavi.de/Oberjesingen%2C%20%20Herrenberg%3A%3A48.628435249999995%2C8.822483166151349/-/indernaehe?time=1622130897)
[Haslach](https://herrenberg.stadtnavi.de/Haslach%2C%20%20Herrenberg%3A%3A48.5841173%2C8.83168405192734/-/indernaehe?time=1622130897)
[Mönchberg](https://herrenberg.stadtnavi.de/M%C3%B6nchberg%2C%20%20Herrenberg%3A%3A48.583681600000006%2C8.916276592128357/-/indernaehe?time=1622130897)
[Kayh](https://herrenberg.stadtnavi.de/Kayh%2C%20%20Herrenberg%3A%3A48.57783135%2C8.92653400571529/-/indernaehe?time=1622130897)

Reason for the current behavior is, that photon returns the osm object for the boundary, with it's coordinate calculated as weighted center of the polygon, and not the coordinate of the likewise named place object.

While it might make sense to fix this in photon itself, we should work around the current behavior by explicitly preventing boundary objects to be returned like by adding an [osm_key=!boundary](https://photon.komoot.io/api?q=mönchberg%20herrenberg&osm_tag=!boundary) parameter.

**Comment by leonardehrenfried** [comment]
Implemented in https://github.com/mfdz/photon-pelias-adapter/commit/38e4bf56e11f146f58b97dcdebbf94ac34e10c6d.

**Comment by leonardehrenfried** [comment]
Also deployed to all environments.

**Comment by samia-roubaa** [comment]
QA: user will be informed that problem is solved
