### ISSUE TITLE
Add detail informations to eCharging pop up

### ISSUE THREAD

**Issue by patrickbeck1337** [stadtnavi/digitransit-ui#500]
As we agreed in todays web dev meeting we first will add all the new detail informations to the pop up. And as follow up apply the new UI design as side panel in #456 

The pop up should include following information:

- Name of the station
- Opening time
- Connector max amperage and power type
- Number of free slots
- Number of total slots
- Accepted payment types
- Address 
- Phone number
- Deep link to https://direct.emobilitycloud.com for each station

Design as reference:
![image](https://user-images.githubusercontent.com/23075804/119533840-8fc12800-bd86-11eb-8c95-dc892ec9d69d.png)

**Comment by samia-roubaa** [comment]
Please check #353.
There are still some information missing.
