### ISSUE TITLE
On Mobile browser: wrong time is shown in pop-up

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#502]
1. Open Stadtnavi webapp form a mobile device
2. Enter any From and To adresses
3. The time of departure is shown correctly like the local time
4. Open the pop-up to set another time for the journey and click on "leaving now" and then on "Ready"
5. Open the pop-up again --> The time **preset** in the pop-up is wrong, it is one hour after the actual time 

On a PC this is not the case, the time is set correctly. 

![Time in pop-up](https://user-images.githubusercontent.com/84389152/119622203-3fd67580-be07-11eb-89db-3356cd66e34f.png)

**Comment by leonardehrenfried** [comment]
This is very likely because an incorrect timezone is being passed to the component.

I fixed this [for a few components a while ago](https://github.com/HSLdevcom/digitransit-ui/pull/3751) but there is still a problem with the mobile time picker. 

Please investigate and pass the timezone.

**Comment by samia-roubaa** [comment]
QA validation successful
