### ISSUE TITLE
Wrong message displayed although routes were found

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#503]
Try the following URL: 
https://herrenberg.qa.stadtnavi.eu/reiseplan/Kreiskrankenhaus%2C%20Marienstra%C3%9Fe%2025%2C%2071083%20Herrenberg%3A%3A48.59177235%2C8.875281170394544/Fahrradparkplatz%20Bahnhof%20Herrenberg%2C%20Bahnhof%20Herrenberg%2C%2071083%20Herrenberg%3A%3A48.5942784%2C8.86228425?time=1622027411 

From: Kreiskrankenhaus
To: Fahrradparkplatz Bahnhof Herrenberg
--> this is only an example but it  happens to other routes as well

System shows the message: "Ihre Suche ergab nur Fahrrad-Routen" although there are other routes by "Car" and by "Park and Ride" modes, also the bike route is not shown unless I click on the bike icon. 

I think the message leads to confusion, maybe the message should be changed to "Ihre Suche ergab keine ÖPNV Ergebnisse" or the behavior should be changed to not show any message at all. 

![20210526 13_10_23-Window](https://user-images.githubusercontent.com/84389152/119650968-bdf54500-be24-11eb-8365-e5039303d00b.png)

**Comment by leonardehrenfried** [comment]
In Helsinki this works as expected: https://reittiopas.hsl.fi/reitti/Ratakatu%209%2C%20Helsinki%3A%3A60.162970373419064%2C24.943857192993168/Uudenmaankatu%2023%2C%20Helsinki%3A%3A60.16376038319639%2C24.938642978668216?locale=en&time=1622642658

It shows a walk and bike tile. Perhaps this needs to be activated?

**Comment by leonardehrenfried** [comment]
@jpidelatorre I fixed this already.

**Comment by jpidelatorre** [comment]
Thanks, @leonardehrenfried !

**Comment by ahmed-nawar** [comment]
This issue is tracked here https://github.com/stadtnavi/digitransit-ui/issues/542

**Comment by ahmed-nawar** [comment]
Tracked here https://github.com/stadtnavi/digitransit-ui/issues/599
