### ISSUE TITLE
Clicking on "Origin" or "Destination" button in echarging panel sets incorrect longitude

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#513]
Steps to reproduce

- Visit https://dev.stadtnavi.eu/ladestationen?lat=48.59410518761695&lng=8.865510821342468&stationId=2953&capacity=1&available=1
- Click on the "Origin" button
- Observe that URL is `https://dev.stadtnavi.eu/Hasenplatz%206%3A%3A48.59410518761695%2Cundefined/-` (note undefined at the end)
- Do a routing search and observe that it produces an error

I'm pretty sure that it's because of a lon/lng mismatch somewhere in the app.

**Comment by andreashelms** [comment]
@jpidelatorre I already fixed this with my last PR. Issue can be closed.
