### ISSUE TITLE
Bicycle-transit mode pushes bike at destination

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#519]
Observation:

Requesting a bike&transit returns trip suggestions where the egress mode is walking (=pushing): 
https://herrenberg.beta.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/Thingstraße%2C%2070565%20Stuttgart%3A%3A48.7160064%2C9.0982223/bikeAndVehicle/?mapMode=bicycle&time=1622266328

<img width="496" alt="image" src="https://user-images.githubusercontent.com/2187389/120059339-4821f100-c051-11eb-9475-0766073240bf.png">

Besides this, the mode name "Parken & Reisen" is wrong and in the details the instructions are "Gehen" (walking) instead of "schieben" (pushing).

Expected behavior:
Egress mode should be "cycle" at destination.

Note:
This issue might be caused by changed semantics in OTP2 for access/egress mode.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-31 13-07-44](https://user-images.githubusercontent.com/151346/120184380-34bd8400-c211-11eb-8fa3-31f9d630faf3.png)

It was indeed a backend problem, but not what I thought. The bike parking stations where not resolved correctly. I have a fix but would like to test it a little more before rolling it out.

**Comment by leonardehrenfried** [comment]
What you saw in your original screenshot was the bike + park option which was awkwardly phrased. What you you think about "Fahrrad abstellen und weiterfahren"?

**Comment by leonardehrenfried** [comment]
I'm now investigating why you cannot take the bike onto the train.

**Comment by leonardehrenfried** [comment]
It seems that VVS doesn't contain any `bikes_allowed` information in their GTFS feed. Can you confirm this @hbruch?

**Comment by leonardehrenfried** [comment]
Bike park URL on dev: https://dev.stadtnavi.eu/reiseplan/Lange%20Stra%C3%9Fe%2C%2071126%20G%C3%A4ufelden-Nebringen%3A%3A48.56206753526866%2C8.846569061279299/Stuttgart%3A%3A48.7784485%2C9.1800132/bikeAndVehicle/?mapMode=bicycle&time=1622465325

**Comment by hbruch** [comment]
No, VVS does not contain bikes_allowed. OTP1 had an option to allow bikes per default. Does this relate to the push mode at destination?

**Comment by leonardehrenfried** [comment]
No, however, since you ask for the "take the bike on transit" option, I think the reason it's missing is that `bikes_allowed` is missing.

**Comment by leonardehrenfried** [comment]
Do we want to allow bikes on transit by default?
