### ISSUE TITLE
Weird line is shown in the details of a "Ladestation"

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#521]
Scenario:
1. Go to https://herrenberg.beta.stadtnavi.eu/
2. Show the Ladestationen
3. Click on any Ladestation to see its details
4. The web app will open in the left panel the details of the Ladestation, you will see a weird line between the details
![image](https://user-images.githubusercontent.com/83356918/120069186-d19ee680-c084-11eb-93cd-84c4b6016e0a.png)
![image](https://user-images.githubusercontent.com/83356918/120069193-da8fb800-c084-11eb-8b07-1f860ba5565d.png)

Expected behavior:
The line should be removed

Beta version:
 image: mfdz/opentripplanner:otp2-4e918914dabed6c05ccabf092f14232eb5801191
 image: stadtnavi/digitransit-ui:d046c65a52f8e754988b7385b9dc80dc2e935393
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b83aaea7eab1ed8eaa9154ce3ce63aca9c949afd
Last version change: 2021-05-28T18:59:03+0200

**Comment by jpidelatorre** [comment]
Normally, this line would separate the text that shows the capacity for the charging station.

![image](https://user-images.githubusercontent.com/104569/121288653-b1a3ca00-c8b1-11eb-9441-0f09161ebfae.png)

I'm changing it so that it hides the line when the message is empty.
