### ISSUE TITLE
Roadworks start/endtime wrong

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#523]
Current behavior:
For any selected roadwork, start/enddate are rendered as current dates:
<img width="673" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120076278-13d82000-c0a5-11eb-98d5-3eb7ae64ccec.png">

Expected behavior:
The start/end date/time of the roadwork are displayed as specified in the data source.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-31 14-21-55](https://user-images.githubusercontent.com/151346/120192775-e661b280-c21b-11eb-8c42-2aa49ec3b4ad.png)

Fixed by 55cf55e3c01e08fef8f023c54415969998197dc9
