### ISSUE TITLE
DT-next bicycle priorities use QUICK mode instead of DT-1 weights

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#525]
While [DT-1 uses safety-oriented routing preferences](https://herrenberg.stadtnavi.de/reiseplan/Reinhold-Schick-Platz%2C%20Reinhold-Schick-Platz%2C%2071083%20Herrenberg%3A%3A48.5956515%2C8.8673058/G%C3%A4ufelden%3A%3A48.5534259%2C8.8229748?mapMode=bicycle&modes=BICYCLE&time=1622407878) for bicycle routing, DT-Next optimizes for [QUICK mode](https://herrenberg.beta.stadtnavi.eu/reiseplan/Reinhold-Schick-Platz%2C%20Reinhold-Schick-Platz%2C%2071083%20Herrenberg%3A%3A48.5956515%2C8.8673058/G%C3%A4ufelden%3A%3A48.5534259%2C8.8229748/bike?mapMode=bicycle&time=1622407913).

DT-Next:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/2187389/120119981-f71e1400-c19a-11eb-8710-ea62817d201c.png">

DT-1:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/2187389/120119995-0c933e00-c19b-11eb-9800-7cee977238b8.png">

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-31 11-26-08](https://user-images.githubusercontent.com/151346/120172112-0173f880-c203-11eb-844e-93f5e91f1b33.png)

DT-1 behaviour restored with ba92a78d610dbbf2f9b5c7510b2cf41a0be4358c
