### ISSUE TITLE
User Feedback: sharing and train only fails for long cycling legs in Stuttgart

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#529]
Feedback numbers: 209, 210

**Feedback number 209 from Ansgar**
From: Herrenberg, Bahnhof Herrenberg
To: Erwin-Bälz-Straße, 70597 
Settings: U-Bahn and Bus are disabled in the settings, Sharing is enabled
Current behavior: 133 minutes with the shared bike are shown
Expected result: better route would be a combination of S-Bahn and Sharing as fist option or also as second option 

Current: 
![grafik](https://user-images.githubusercontent.com/84389152/120203273-d059ef00-c227-11eb-973a-10db25fb08b4.png)

Expected: 
![grafik](https://user-images.githubusercontent.com/84389152/120203288-d51ea300-c227-11eb-8b50-ae15729a57d1.png)

Settings: 
![grafik](https://user-images.githubusercontent.com/84389152/120203590-2af34b00-c228-11eb-9fcd-55e6f6634364.png)

**Comment by leonardehrenfried** [comment]
I'm going to remove the second part of this ticket since there is a separate one for it #541.

**Comment by leonardehrenfried** [comment]
Fixed on dev: https://dev.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/Erwin-B%C3%A4lz-Stra%C3%9Fe%2C%2070597%20Stuttgart%3A%3A48.748679%2C9.1749312?time=1623148964
