### ISSUE TITLE
User Feedback: Sharing offer not useful in selected route - walking is better for this leg 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#531]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Herrenberg%2C%20Bahnhof%20Herrenberg%2C%2071083%20Herrenberg%3A%3A48.594059%2C8.8629217/Stuttgart%20Hauptbahnhof%2C%20Baustra%C3%9Fe%20Stuttgart%2021%2C%2070173%20Stuttgart%3A%3A48.7856099%2C9.1833959/?time=1622637960

Settings: turn on the Sharing 
Current behavior: the last 5 minutes are shown as a sharing offer which is divided in two further legs (see screenshot)
![grafik](https://user-images.githubusercontent.com/84389152/120247288-3f106a00-c273-11eb-9002-a9a3e947c3f6.png)

Expected behavior: walking is preferred in that case

Another Issue is: when I click on the details of the route with the sharing offer I get an error. However it's working on the mobile app.
![grafik](https://user-images.githubusercontent.com/84389152/120247338-68c99100-c273-11eb-9386-fde471f3be3a.png)

**Comment by leonardehrenfried** [comment]
Yesterday I changed the settings so that even if you activate sharing, it's not taken when there is a really short rental part.

The route you sent now looks like this:

![Screenshot from 2021-06-01 11-19-34](https://user-images.githubusercontent.com/151346/120299463-4d8a7000-c2cb-11eb-8dc2-0671ca47db48.png)

**Comment by leonardehrenfried** [comment]
I also fixed the issue in the UI.

@nghanem-poet-egypt Can you try again?

**Comment by nghanem-poet-egypt** [comment]
@leonardehrenfried I tested it on the webapp and everything is working fine. However it is wrong in the mobile app, should I create it in the other project stadtnavi_app as well or should it have been fixed by default?

**Comment by leonardehrenfried** [comment]
It should be fixed in the app as well. Are you using the app from the app store or a custom version?

**Comment by samia-roubaa** [comment]
I couldn't validate the bug on the iOS app, as I got the following error
![image](https://user-images.githubusercontent.com/83356918/120505438-447dc980-c3c5-11eb-8da9-24110d0b9a94.png)

**Comment by leonardehrenfried** [comment]
I pushed a fix. Can you try again?

**Comment by ahmed-nawar** [comment]
If you activate sharing, it is taken into account when there is a really short rental part still.
The route looks like this:

![image](https://user-images.githubusercontent.com/84456072/120923337-51086780-c6ce-11eb-8a46-6093799860a0.png)

**Comment by ahmed-nawar** [comment]
Keep in mind that Avoid walking toggle is on. If it is turned off the routes returned are like this
![image](https://user-images.githubusercontent.com/84456072/120923528-54e8b980-c6cf-11eb-83c8-baa0160791f9.png)
