### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#532]
- [x] 1. The abbreviation of the day should start with a capital letter like in the drop-down list 

- [x] 2. The words "Früher" and "Später" don't have same font size or color

- [x] 3. Is it really "Fährt **ab um** 11:22..." in German? or only ab

~4. Viewing webapp in mobile: When writing in the search drop-down the suggestion of the last search has the day in English although I chose German as language~ ( Tracked in #596 )

![grafik](https://user-images.githubusercontent.com/84389152/120250693-640ada00-c27f-11eb-8deb-a0f20d450ce4.png)
![grafik](https://user-images.githubusercontent.com/84389152/120251130-cfa17700-c280-11eb-9baa-4d43a9b9223c.png)

**Comment by jpidelatorre** [comment]
* [x]  1. The abbreviation of the day should start with a capital letter like in the drop-down list

* [x]  2. The words "Früher" and "Später" don't have same font size or color

* [x]  3. Is it really "Fährt **ab um** 11:22..." in German? or only ab
- I think `ab um` is correct. @Denis306 can you help us clarify this?

* [ ]  4. Viewing webapp in mobile: When writing in the search drop-down the suggestion of the last search has the day in English although I chose German as language
- For some reason I don't get the last search in the dropdown. @leonardehrenfried Do you know what could be happening?

**Comment by Denis306** [comment]
@jpidelatorre @nghanem-poet-egypt "Fährt ab um 11:22..." is correct. 
And I also can't seem to reproduce the bug with the dropdown in the searchbar when in mobile view. @nghanem-poet-egypt could you clarify how you got that suggestion in the dropdown?

**Comment by jpidelatorre** [comment]
@Denis306 I was able to replicate the bug. With the help of @leonardehrenfried, I'm pushing upstream a solution that should fix number *4.*

**Comment by jpidelatorre** [comment]
@leonardehrenfried The PR was accepted upstream.

https://github.com/HSLdevcom/digitransit-ui/pull/4232

How should we proceed?

**Comment by leonardehrenfried** [comment]
Does that change anything when you build locally?

**Comment by jpidelatorre** [comment]
No change at all. I guess they would need to publish the last version of their package.

**Comment by leonardehrenfried** [comment]
Ok, remove the last line and make another ticket for just that one problem.

**Comment by jpidelatorre** [comment]
@leonardehrenfried The new ticket is #596
