### ISSUE TITLE
Replace Park&Ride symbol

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#533]
The current symbol for park and ride suggestions is not very meaningfull, as it only displays a "P" and a car:
<img width="133" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120269109-78fb6380-c2a7-11eb-9eeb-7c2f672698cd.png">

HSL's symbology (showing a bicycle and small transit symbol in the background for bike & ride, would be car & transit for P&R) seems much more intuitive:
<img width="126" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120269021-48b3c500-c2a7-11eb-9e2d-13ed1caccf3b.png">

HSL probably already has prepared such symbols, so coordinate with them.

As we ae currently preparing Flex&Transit routing, a resembling symbol, perhaps with a taxi symbol (e.g. a car with a black bar on top) combined with transit instead of a car symbol should be prepared as well.

**Comment by Denis306** [comment]
Talked to Joel and he will provide the Icons they use for P+R today.

**Comment by hbruch** [comment]
And regarding flex/transit?

**Comment by Denis306** [comment]
Flex/Transit is supposed to be "On demand Taxi" and as mentioned yesterday in this [Conversation](https://chat.stadtnavi.eu/#narrow/stream/27-digitransit-ui/topic/cargo.20bike.20booking/near/10455) Ansgar/Agentur Kraus was going to provide those.

**Comment by Denis306** [comment]
This is how HSL uses the Icons for Park & Ride: https://www.figma.com/file/wCkiYqAczNjmf9Gl1B1u4J/Park-%26-Ride-%E2%80%93-Car?node-id=0%3A1

For the P&R Tiles in the suggestions they simply combine the Car Icon with whatever Transportation type icon used in that itinerary.
![image](https://user-images.githubusercontent.com/63004289/120328179-de247880-c2ea-11eb-86cd-791030e8179c.png)
 
These are the Icon SVGs from the figma mockups for the parking space.
[Park & Ride – Car.zip](https://github.com/stadtnavi/digitransit-ui/files/6576426/Park.Ride.Car.zip)

- [ ] Please change the blue Icon in the park & ride mode tile to the same Logic as with the bike & ride mode tile by using the car icon as main Icon and combining it with a small public transport icon.

![image](https://user-images.githubusercontent.com/63004289/120827544-d3244f00-c55b-11eb-8d60-914824db891d.png)

- [ ] The only have one "Specific" P&R Icon that they use for car parking spaces in the itinerary overview. This should be done int the itinerary suggestion as well.

![image](https://user-images.githubusercontent.com/63004289/120328243-eda3c180-c2ea-11eb-98b8-c29750daad45.png)

**Comment by ahmed-nawar** [comment]
The icon for Park & ride is the same as the car icon

![image](https://user-images.githubusercontent.com/84456072/121882941-766e2480-cd11-11eb-858d-a28f25854695.png)

**Comment by Denis306** [comment]
@leonardehrenfried @hbruch should we change the Icon in the settings to also use that "Car Icon + Transit Icon" Symbology?

**Comment by leonardehrenfried** [comment]
Probably a good idea but what are we going to use as the smaller icon? Probably the train.

I think it would be easier in this case if Sandra could prepare the fixed icon rather than a developer having to superimpose two them onto each other.

**Comment by Denis306** [comment]
@leonardehrenfried & @ahmed-nawar I created this seperate ticket for the Icon topic: https://github.com/stadtnavi/digitransit-ui/issues/640
