### ISSUE TITLE
Missing carpool leg

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#535]
How to repoduce:
1. enable carpools in settings
2. search for connections from Affstätt to Tübingen at 6:00am e.g. https://herrenberg.qa.stadtnavi.eu/reiseplan/Affst%C3%A4tt%2C%20%20Herrenberg%3A%3A48.6059715%2C8.8583072/T%C3%BCbingen%20Hbf%2C%20Hegelstra%C3%9Fe%2C%2072072%20T%C3%BCbingen%3A%3A48.5155801%2C9.0552876/?time=1622520000

Current behavior:
Carpool leg is only displayed in overview, but not in the details.
<img width="441" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120270205-7dc11700-c2a9-11eb-84ac-c97d9360bd90.png">

Expected behavior:
Carpool leg is shown corresponding to DT-1, especially showing the symbol of the carpool agency and the booking button link.
<img width="545" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120270275-9f220300-c2a9-11eb-99ef-30f8482cc086.png">

**Comment by Beck-berry** [comment]
@hbruch Do you have any other requests regarding the appearance?

![Képernyőkép_2021-06-03_20-29-17](https://user-images.githubusercontent.com/46535522/120694442-7e74cb80-c4aa-11eb-9838-1edad49585c8.png)


@leonardehrenfried Did the API change? Back with DT-1 we used `leg.route.url` but I'm not sure if it's still sent. Should we use `leg.route.agency.fareUrl` instead?

![Képernyőkép_2021-06-03_20-29-02](https://user-images.githubusercontent.com/46535522/120694590-b419b480-c4aa-11eb-9aa1-6e9de6bd382c.png)

**Comment by hbruch** [comment]
Perhaps the route.url is not yet requested via the graphQL query? Could you check DT-1 commit history as it was surely added there, since it is non-standard.

Concerning the rendering, we should display it close to the way transit is rendered, I suggest. E.g.:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/2187389/120701854-b0d6f680-c4b3-11eb-823d-f74e99674c07.png">


For carpool then it would be a carpool symbol in the bar, instead of route short name, we could display the agency Logos (perhaps not on green background as it would be hard to discern...)

"Drive" is not the best translation, better would be "Ride" or "Carpool". 
The two agency symbols should have some spacing separating them.

**Comment by Beck-berry** [comment]
Thank you for the tip, I fixed the url issue!

Did you think about something like this?
![image](https://user-images.githubusercontent.com/46535522/120844300-792d8480-c56f-11eb-9514-b5a5b66aa951.png)

Next to the agency logos it prints the name of the destination.
Also, I'd use 'Ride' for the English version but what shall the German translation be?

**Comment by leonardehrenfried** [comment]
German is "Mitfahren"
