### ISSUE TITLE
Enable static messages

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#537]
Digitransit-1 supported static messages displayed on startup. They can be used to display the cookie consent, imported alerts or notifications like advertisement for new stadtnavi features or mobility options. In the config, it used to be configured via `staticMessagesUrl: STATIC_MESSAGE_URL`

These should be reactivated in DT-2, example content:

```
{"staticMessages": [{
	"content": {
		"en": [
			{"content": "Public Beta", "type": "heading"},
			{"content": "This stadtnavi version currently is in public beta. You have suggestions or issues? Please give us feedback.", "type": "text"},
			],
		"de": [
			{"content": "Öffentliche Beta-Version", "type": "heading"},
			{"content": "Diese stadtnavi Version befindet sich derzeit im öffentlichen Probebetrieb. Anregungen oder Probleme? Geben Sie uns gerne Feedback.", "type": "text"},
			],
		}, 
"type": "info", 
"id": "01062021_0727", 
"persistence": "repeat", 
"icon": "info"}]
}
```

(Fot format details, a look into [MessageStore.js](https://github.com/stadtnavi/digitransit-ui/blob/next/app/store/MessageStore.js) might be helpful)

**Comment by nghanem-poet-egypt** [comment]
@hbruch could you please validate if this is implemented, we cannot validate it. Please close the issue if it's ok.

**Comment by hbruch** [comment]
It's implemented, yes.
