### ISSUE TITLE
Wrong message shown although routes were found

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#542]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Steinerner%20Weg%2C%2071134%20Aidlingen%3A%3A48.6580831%2C8.8873906/Eisenbahnstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.5932927%2C8.8635394?locale=en&time=1622548800

The message says that there are no routes found in this area although there are Bike, Bike+Ride, Park+Ride and Car options found! 
I think the message is misleading. It should either be removed or it should say "Leider konnte keine ÖPNV Route.... " / "No transit route suggestions were found...."

![grafik](https://user-images.githubusercontent.com/84389152/120358670-0c17b600-c307-11eb-9936-315fcee4ad05.png)

**Comment by MartinH-open** [comment]
I very much confirm this kind of "error" or wrong indicator. 
Living in that town Aidlingen I see this error all the time.
For the user it is totally unclear what is meant by "außerhalb des abgedeckten Gebietes". In StadtNavi there is no such display of the "supported area". And is supported area the same for all kinds of mobile services - like bus, train, carpooling, bike rental, car sharing, and so on.  Either display the "supported area" (rectangle of boundary box) or the specific area - or else at least have some linked documentation where to find out what is supported where - and how to extend that area of support.

**Comment by leonardehrenfried** [comment]
To the frontend dev: it appears that the logic to check if there is only a walking route is buggy since that is returned but not displayed.

**Comment by leonardehrenfried** [comment]
The area polygon defining the service area was incorrectly configured. I fixed it in ad047f4d20fcf6fc48f9e46b33753ce6bbedac2a

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-02 16-44-23](https://user-images.githubusercontent.com/151346/120501354-d683d300-c3c1-11eb-8057-6709fed2a139.png)

**Comment by leonardehrenfried** [comment]
The question is though why it cannot find a route. I will track this issue here: https://github.com/mfdz/OpenTripPlanner/issues/85

**Comment by MartinH-open** [comment]
> The area polygon defining the service area was incorrectly configured. I fixed it in [ad047f4](https://github.com/stadtnavi/digitransit-ui/commit/ad047f4d20fcf6fc48f9e46b33753ce6bbedac2a)

Thanks for the reference. It appears that the service area is hardcoded in such config file. ;)
I assume config.hb.js stands for "HerrenBerg" and not "HolgerBruch".  :)

I assume this polygon applies to all kinds of services.

**Comment by ahmed-nawar** [comment]
The message is still misleading
![image](https://user-images.githubusercontent.com/84456072/120925326-6d110680-c6d8-11eb-9e09-a7314e0131af.png)

There are Bike, Bike&Ride, Park&Ride and Car options found.

**Comment by ahmed-nawar** [comment]
Similar to #503

**Comment by sara-georgy** [comment]
Reported from user feedback 231: 

https://herrenberg.beta.stadtnavi.eu/reiseplan/Vorsteigstra%C3%9Fe%2C%2070193%20Stuttgart%3A%3A48.7812373%2C9.1553375/Kocherstra%C3%9Fe%2C%2071083%20Oberjesingen%3A%3A48.6254176%2C8.8381856?time=1622828190 

The user disabled all transportation options except for car. 
Therefore, the displayed message was misleading for the user as the system retrieved a car route.

**Comment by leonardehrenfried** [comment]
Perhaps we could replace the message with something like: "Only routes without public transport were found."

Would you find that clearer?

**Comment by sara-georgy** [comment]
Yes, I agree it would be clearer if we changed the message.

**Comment by leonardehrenfried** [comment]
The actual problem of the route to Steinerner Weg not being found is fixed on dev: https://dev.stadtnavi.eu/reiseplan/Steinerner%20Weg%2C%2071134%20Aidlingen%3A%3A48.6580831%2C8.8873906/Eisenbahnstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.5932927%2C8.8635394?locale=de&time=1622548800

But this ticket is more about the error message when no route is being found, right?

**Comment by leonardehrenfried** [comment]
@Denis306 @nghanem-poet-egypt This ticket contains mostly a discussion and it would be hard for the devs to identify what they're supposed to do. Can we close this one and replace it with instructions to change the error message?

**Comment by nghanem-poet-egypt** [comment]
Yes, sure I can do that. So as a summary the error message will be changed to "Only routes without public transport were found."

**Comment by leonardehrenfried** [comment]
Correct.
