### ISSUE TITLE
Map view doesn't change and is not selected correctly in settings

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#550]
From: Bahnhof Herrenberg, Bahnhofstraße 14, 71083 Herrenberg
To: Hauptbahnhof, Lautenschlagerstraße, 70173 Stuttgart
1. the system shows me the map background as "Streets"  --> which is correct
2. Change to bike and ride mode, the system shows the map backgroud to "Bike" --> which is correct but in the map layers the radio button stays on "Streets"
3. Change the To address to "Stuttgart Schwabstraße, Rotebühlstraße, 70197 Stuttgart"
4. The system shows new routing suggestions with TRANSIT shown as first routing suggestion BUT the map background stays on "Bike" even if I change the mode to Park and ride or to Car the map backgroud stays on "Bike"
5. In all cases the radio button in the map layers side bar stays on "Streets"

Expected behavior: 
- when I change the address and the system shows me TRANSIT routes the map should get back to STREETS
- the radio button in the side bar should be changed to BIKE when the map changes its backgroud. Because otherwise the user has to change the map backgroud and then get back to streets again. 

![20210602 12_33_01-Window](https://user-images.githubusercontent.com/84389152/120468155-33bb5c80-c3a1-11eb-9526-93424b9a86f1.png)

![20210602 12_52_48-Window](https://user-images.githubusercontent.com/84389152/120468614-b3492b80-c3a1-11eb-9a48-3a43e104af66.png)

**Comment by Beck-berry** [comment]
Hi!
I'd have a short question about  
> * when I change the address and the system shows me TRANSIT routes the map should get back to STREETS

Is this the expected behavior if there are *no biking routes* at all or if there are *any transit routes*? I think about the last but want to make sure :smile:
Thanks!

**Comment by leonardehrenfried** [comment]
You should only see the bike map when viewing the bike only trip. Even for the bike + train trips I'd prefer the normal map. Is that right, @hbruch ?

**Comment by Beck-berry** [comment]
By viewing you mean when the itinerary is opened (as on the first screenshot)? Currently we change the map if the mode is changed, should it rather be when a bike route is selected?

**Comment by leonardehrenfried** [comment]
Well, Holger said that he wants the bike map for bike + transit trips.
