### ISSUE TITLE
Search for "later" trips freezed

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#553]
Scenario:
1. Go to https://herrenberg.beta.stadtnavi.eu/
2. plan a search from Nufringen to Kuppingen, deactivate the bus and activate bike rental in the settings panel.
3. The following suggestions will be shown
![image](https://user-images.githubusercontent.com/83356918/120471180-af6ad880-c3a4-11eb-9144-ac18f06abb15.png)
4. Click on "Later" to show later trips
5. The loop will keep loading and no results will be shown
![image](https://user-images.githubusercontent.com/83356918/120471316-daedc300-c3a4-11eb-9bd1-902a9f91930b.png)

Beta version:
 image: mfdz/opentripplanner:otp2-3621b1e591409b23d96b6253472d6f4bac88057e
 image: stadtnavi/digitransit-ui:55cf55e3c01e08fef8f023c54415969998197dc9
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b83aaea7eab1ed8eaa9154ce3ce63aca9c949afd
Last version change: 2021-06-02T12:12:00+0200

**Comment by samia-roubaa** [comment]
@leonardehrenfried 
Nada created a similar issue #558. Could you please check if this one addresses the same problem, so we can close one of them as a duplicate.

**Comment by leonardehrenfried** [comment]
Yes, it's the same issue. Closing in favour of #558.
