### ISSUE TITLE
Search freezed: no results are being shown

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#554]
Scenario:
1. Go to https://herrenberg.beta.stadtnavi.eu/
2. Plan a trip from Ehringen to Kuppingen (in the settings: bus is disabled and bike rental is activated)
3. The search will keep loading and no results will be shown
![image](https://user-images.githubusercontent.com/83356918/120471887-8e56b780-c3a5-11eb-9cb7-70d29f2f1a04.png)

Beta version:
 image: mfdz/opentripplanner:otp2-3621b1e591409b23d96b6253472d6f4bac88057e
 image: stadtnavi/digitransit-ui:55cf55e3c01e08fef8f023c54415969998197dc9
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b83aaea7eab1ed8eaa9154ce3ce63aca9c949afd
Last version change: 2021-06-02T12:12:00+0200

**Comment by leonardehrenfried** [comment]
Tracked in the backend: https://github.com/mfdz/OpenTripPlanner/issues/78

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-02 18-05-39](https://user-images.githubusercontent.com/151346/120514035-261bcc00-c3cd-11eb-8f21-ade4061a9994.png)

In actual fact the ticket linked above is unrelated. I managed to find the problem. I will be fixed on beta tomorrow.

**Comment by leonardehrenfried** [comment]
A side effect it that the routes containing just walking and bike rentals are back but I will work on that tomorrow.

**Comment by leonardehrenfried** [comment]
I've deployed the fix to beta. Be aware that there is still a problem of no route appearing when you set the bike speed to 10km/h.

I'm tracking _that_ problem in https://github.com/mfdz/OpenTripPlanner/issues/86

**Comment by ahmed-nawar** [comment]
> ![Screenshot from 2021-06-02 18-05-39](https://user-images.githubusercontent.com/151346/120514035-261bcc00-c3cd-11eb-8f21-ade4061a9994.png)
> 
> In actual fact the ticket linked above is unrelated. I managed to find the problem. I will be fixed on beta tomorrow.

The origin in this screen shot is different from what was originally reported.
Issue origin reported: Ehringen vs screen shot origin: Ehningen

![image](https://user-images.githubusercontent.com/84456072/120923716-46e76880-c6d0-11eb-9f43-30e5e639e9e8.png)

**Comment by leonardehrenfried** [comment]
Ehringen really is outside the service area. I'd say that this ticket is closed. Can you check?
