### ISSUE TITLE
Style carpool offer

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#555]
Can can find the carpool offer by viewing a car leg and clicking "Offer carpool".

![Screenshot from 2021-06-02 13-20-55](https://user-images.githubusercontent.com/151346/120471764-66ffea80-c3a5-11eb-8b85-82f61905d477.png)

Things to improve

- When selecting regular and then one of the days the checkboxes look broken
- Style the telephone number field

**Comment by ahmed-nawar** [comment]
The check boxes looks still broken 
![image](https://user-images.githubusercontent.com/84456072/121896055-2c8d3a80-cd21-11eb-9a72-e6515a6c8dea.png)

Things to improve: Add validation to the phone number input field. Should we limit the number of digits to a certain length?
Center the ticks in the checkboxes

**Comment by leonardehrenfried** [comment]
It's on beta.
