### ISSUE TITLE
Triangle factors are missing from earlier/later queries

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#558]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Stuttgart%20Hauptbahnhof%2C%20Baustra%C3%9Fe%20Stuttgart%2021%2C%2070173%20Stuttgart%3A%3A48.7856099%2C9.1833959/Herrenberg%2C%20Bahnhof%20Herrenberg%2C%2071083%20Herrenberg%3A%3A48.594059%2C8.8629217?time=1622637006

Click on earlier or later departures --> nothing happens it keeps loading and nothing is shown
![grafik](https://user-images.githubusercontent.com/84389152/120480462-581e3580-c3af-11eb-81ad-e7efa0bc0800.png)

**Comment by leonardehrenfried** [comment]
Thanks for reporting. I already rolled out a fix to dev. Will be on beta tomorrow.
