### ISSUE TITLE
Location bias is not working

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#560]
When you search after "Bahnhof", the first Bahnhof that appears is not in Herrenberg.
Earlier the location bias worked.
![image](https://user-images.githubusercontent.com/83356918/120492112-13e46280-c3ba-11eb-8bb0-931ff9400efe.png)

Beta version:
 image: mfdz/opentripplanner:otp2-3621b1e591409b23d96b6253472d6f4bac88057e
 image: stadtnavi/digitransit-ui:55cf55e3c01e08fef8f023c54415969998197dc9
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:b83aaea7eab1ed8eaa9154ce3ce63aca9c949afd
Last version change: 2021-06-02T13:32:55+0200

**Comment by leonardehrenfried** [comment]
This has been fixed on all environments.
