### ISSUE TITLE
Avoid Walking toggle is not working as expected

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#563]
https://herrenberg.beta.stadtnavi.eu/reiseplan/M%C3%BChlstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59598912311189%2C8.860956430435182/G.-F.-H%C3%A4ndel-Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59477574898104%2C8.879871368408205?intermediatePlaces=&locale=en&time=1622628538
Toggle Avoid Walking off and check the results then toggle it on -> the returned routes are nearly the same.

**Comment by leonardehrenfried** [comment]
Good find, however for short routes it's difficult to find better routes with less walking.

What I find more problematic is that there are so many routes suggested. It should be way fewer.

**Comment by leonardehrenfried** [comment]
I;m going to track this in a backend ticket: https://github.com/mfdz/OpenTripPlanner/issues/90
