### ISSUE TITLE
The Offer carpool button doesn't work in park and ride mode

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#564]
1. Fill in any origin destination addresses
2. Choose a park and ride route
3. Click on offer carpool button
4. Nothing happens
5. While in the car mode, the offer carpool button works
https://herrenberg.beta.stadtnavi.eu/reiseplan/M%C3%BChlstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59598912311189%2C8.860956430435182/G.-F.-H%C3%A4ndel-Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59477574898104%2C8.879871368408205/parkAndRide/?intermediatePlaces=&locale=en&time=1622628538

**Comment by leonardehrenfried** [comment]
Good catch.

**Comment by MartinH-open** [comment]
Whatever the specific problem here is/was
The map for the above URL displays strange things. There are additional dotted lines and grey path on the map.
Is that some additional debugging information or what? 
Anyhow the suggested route looks strange too: Why to use a car for 1 min (250m); then walk and take a bus for one stop - where you could simply walk to the final destination better.  (Routing seems to be totally broken in this beta.)
![image](https://user-images.githubusercontent.com/1383111/120704899-72433b00-c4b7-11eb-8ec9-3fa95dd768ac.png)

**Comment by MartinH-open** [comment]
BTW - there is not ONE Beta Version. But mulitple versions are being pushed in these days. Great. 
But where - as a user - I can see the specific Beta Version string of the instance I'm using.
I submitted feedback from the UI - but even that email does not contain any beta version string.
You would want to know the exact version in order to decide if the feedback is still relevant or due to known problems of earlier versions.

**Comment by sara-georgy** [comment]
The first step works fine. (See screenshot)
![image](https://user-images.githubusercontent.com/84382750/122966093-3221fa80-d389-11eb-991f-b62f078ae89b.png)

However after clicking on "offer carpool" the system loads indefinitely. (See screenshot)
![image](https://user-images.githubusercontent.com/84382750/122966310-77462c80-d389-11eb-8d39-49605b7e29cd.png)

**Comment by andreashelms** [comment]
I think the URL of the request for offering carpools is incorrect. Dev environment uses `POST https://dev.stadtnavi.eu/carpool-offers`. What is the correct URL for offering carpools?

**Comment by leonardehrenfried** [comment]
Actually, this is correct. I heard something about the backend (an external backend, not ours) being down. I will investigate.

**Comment by leonardehrenfried** [comment]
The problem is that in car mode the properties lat,lon in the offer are passed to the server, but in p+r they are not.

**Comment by ahmed-nawar** [comment]
This is not fixed on the beta version yet.
