### ISSUE TITLE
Toggle button without a label in the settings

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#574]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Herrenberg%2C%20Bahnhof%20Herrenberg%2C%2071083%20Herrenberg%3A%3A48.594059%2C8.8629217/Stuttgart%20Hauptbahnhof%2C%20Baustra%C3%9Fe%20Stuttgart%2021%2C%2070173%20Stuttgart%3A%3A48.7856099%2C9.1833959/?locale=en&time=1622637960
1) Click on the settings tab
2) Click on Sharing toggle

Current Behavior: Toggle button shown without a label
Expected Behavior: Toggle button should have a correct label or removed
![image](https://user-images.githubusercontent.com/84456072/120923190-86608580-c6cd-11eb-9123-70df752a38ca.png)

**Comment by nghanem-poet-egypt** [comment]
Issue was fixed
