### ISSUE TITLE
Apply new UI to Cargo bike booking Feature

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#579]
We want to implement the cargo bike booking pretty similar to the eCharging Stations.
![image](https://user-images.githubusercontent.com/63004289/120941283-0a445d00-c722-11eb-98b0-5c6482068bf8.png)

The Icons used in the Design proposal are just dummy icons. We are waiting for the icons that will be provided by the city of Herrenberg. 

These are the Cargo Bike Icons that need to be used:
[lastenrad_sharing.zip](https://github.com/stadtnavi/digitransit-ui/files/6618431/lastenrad_sharing.zip)

All the other information is here: https://github.com/stadtnavi/digitransit-ui/issues/351

**Comment by sara-georgy** [comment]
The new UI has only been applied to one station "Cargobike TUG Herrenberg" 
Is this the correct behavior? @leonardehrenfried 
![image](https://user-images.githubusercontent.com/84382750/123108094-69041900-d43a-11eb-92d2-fbe877dbb19a.png)

The other three stations "E-Lastenrad FaRe", "Lastenrad Gülf" and "Lastenrad Alf" still have the old UI:
![image](https://user-images.githubusercontent.com/84382750/123108627-de6fe980-d43a-11eb-8656-61c8e8bb9ebc.png)

![image](https://user-images.githubusercontent.com/84382750/123108712-f0ea2300-d43a-11eb-8834-1dfa95b606ac.png)

![image](https://user-images.githubusercontent.com/84382750/123108824-09f2d400-d43b-11eb-8d64-e54e04b03d6e.png)

**Comment by leonardehrenfried** [comment]
Yes, that is correct. The others don't actually have a proper booking system. You have call or just show up.

**Comment by Denis306** [comment]
Yes. This can be closed.
