### ISSUE TITLE
Feedback User 229: incorrect location of the parking place (P+R #2)

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#581]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Sch%C3%B6nbuchturm%2C%2071083%20Herrenberg%3A%3A48.6039231%2C8.909352661789013/Marktplatz%2C%2071083%20Herrenberg%3A%3A48.5964113%2C8.869932/parkAndRide/0?time=1622826846

The displayed parking place for the Marktplatz is incorrect (P+R #2). (see screenshot)
![image](https://user-images.githubusercontent.com/84382750/121004301-cf2c4300-c78e-11eb-9e8a-d451154cae80.png)

 The correct place is located in google maps as follows: https://goo.gl/maps/tnmGsDjAP1xX9Ncw5.

Recommended by Angelika:  "Auf dem Graben" or "Stadthallenparkplatz" are more convenient to park in when the user chooses the location "Markplatz"

**Comment by leonardehrenfried** [comment]
I think this must have been feedback from the weekend because I activated this on beta this morning.

![Screenshot from 2021-06-07 12-55-11](https://user-images.githubusercontent.com/151346/121005053-ad7f8b80-c78f-11eb-8147-7b6e6993395a.png)
