### ISSUE TITLE
Duplicated walking leg in route

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#582]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Vorsteigstra%C3%9Fe%2C%2070193%20Stuttgart%3A%3A48.7812373%2C9.1553375/bikeAndVehicle/0?mapMode=bicycle&time=1622828190

This route shows two times walking which is not userfriendly or correct.

![grafik](https://user-images.githubusercontent.com/84389152/121005543-3a2a4980-c790-11eb-9290-68d462638567.png)

**Comment by leonardehrenfried** [comment]
Tracked in the backend: https://github.com/mfdz/OpenTripPlanner/issues/95
