### ISSUE TITLE
Feedback from Angelika: dominance of the map views

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#584]
IOS App:
1. The map views on the IOS App is taking a big part of the screen.
2. and it makes the displayed options hard to scroll.  

![image](https://user-images.githubusercontent.com/84382750/121010021-27664380-c795-11eb-951b-ac866e266c06.png)

**Comment by Denis306** [comment]
This issue can be closed as it is obsolet after the rework of the whole map layer switcher.
