### ISSUE TITLE
Feedback user 232: intermodality when choosing P+R or bike

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#585]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Vorsteigstra%C3%9Fe%2C%2070193%20Stuttgart%3A%3A48.7812373%2C9.1553375/parkAndRide?time=1622828190

1. When the user chooses “P+R” (35km, 58min), the system shows a car ride for the first 100m of the route and the rest is a combination of other transportation options. 
2. And when the user chooses “bike” (80m, 57min), the system shows the bike option for the first 80m and the rest of the route is a combination of other transportation options. Also, the system changes the map display to bike mode although the bike is only used for the first 1min of the route.

**Comment by leonardehrenfried** [comment]
Would you prefer to replace driving/cycling with walking in this case?

**Comment by MartinH-open** [comment]
Yes, there should be some minimum amount of travel (time) before offering a certain mode of transportation.
But for walking this minimum should be 0 meter.

**Comment by MartinH-open** [comment]
BTW - the current beta is still full of issues - more than anyone can report in reasonable time.
See below picture with multiple issues for this case.
The bike icon is displayed for a 35km trip in 34 min (this is a speed of a car - not a regular bike).
German text reads "Leihrad ausleihen:" - but then "Fahrrad bei {station} zurückgeben" => use the same one term "Fahrrad" or "Leihrad"
The parameter {station} is not filled in. There is no colon ":" at the end.
Leihrad is displayed with a red car icon symbol. 
The number "-1" is unclear for users - does this mean not available at this (current) time?
There are two walking legs - one after the other: => adjacent walking legs should be combined in one.
![image](https://user-images.githubusercontent.com/1383111/121272658-de161100-c8c6-11eb-821a-bba441a33252.png)

**Comment by leonardehrenfried** [comment]
You're right Martin, this is a bug and we will fix it. Explanation: Helsinki's digitransit only knows about rental bikes but we also added car sharing which is poorly reflected in this UI. In actual fact, we should never offer any routes with those rental cars.

**Comment by leonardehrenfried** [comment]
I removed those car sharing routes. Right now only on dev but from Friday also on beta.
