### ISSUE TITLE
Walk leg is divided to two legs

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#587]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Nagolder%20Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.5955763%2C8.8668147/Kindergarten%20Spatzennest%2C%20Schulweg%202%2F1%2C%2072227%20Egenhausen%3A%3A48.56311125%2C8.618277734741747/bikeAndVehicle/0?mapMode=bicycle&time=1623065671&locale=de

Wrong label on the walking leg and leg is divided to two legs

**Reproduce:**
1) Go to link
2) Check legs in returned route

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/84456072/121051128-79b95b80-c7b9-11eb-87df-6f2333e68527.png)

**Expected behaviour:**
- To show correct label on leg
- Merge the two walking legs into one longer walking leg

**Comment by nghanem-poet-egypt** [comment]
already reported in https://github.com/stadtnavi/digitransit-ui/issues/582 so I'll close it for now
