### ISSUE TITLE
Add icons to their label in sidebar when choosing which icons to show on the map

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#593]
Add the icon of each title/label in the 'show on map' menu where the user selects which icons to be shown on the map
This might also act as a legend
![image](https://user-images.githubusercontent.com/84456072/121223522-e9961780-c887-11eb-9522-9868cc1d9382.png)

**Comment by MartinH-open** [comment]
Yes, good proposal. But icons should be next to the checkbox and left of the text label

**Comment by Denis306** [comment]
Closing this issue as this is currently being solved in #345 and the implementation of a new map layer switcher.
