### ISSUE TITLE
Simplify the map display options to only main categories

### ISSUE THREAD

**Issue by MartinH-open** [stadtnavi/digitransit-ui#594]
Current StadtNavi offers much to many map display options. 
This should be simplified to not confuse and overload the user.
In German these options should be enough: Keep it simple!
1. Bus &Bahn  (or ÖPNV = public transport)
2. Sharing (Carsharing and Carpooling, Taxi)
3. Fahrrad (bike)
4. Infrastructure (Park, Charging station, public toilets, LoRaWAN - if needed at all)

Display certain items only if specific routes are presented already: Eg. display "Baustelle" (construction) only if it has impact on the routes. 

![image](https://user-images.githubusercontent.com/1383111/121232066-7a252580-c891-11eb-823a-80ca44586bfe.png)

**Comment by hbruch** [comment]
We introduced 2-level layer groups with https://github.com/stadtnavi/digitransit-ui/pull/608, so will close here. Thanks for your suggestions
