### ISSUE TITLE
Wrong locale for date

### ISSUE THREAD

**Issue by jpidelatorre** [stadtnavi/digitransit-ui#596]
When writing in the search drop-down the suggestion of the last search has the day in English although I chose German as the language.

![image](https://user-images.githubusercontent.com/151346/121312450-ac706a80-c905-11eb-9f60-33b53a651d50.png)

German Locale is missing from the component.

@jpidelatorre fixed this upstream but it seems that we need to wait for it being published on their side: https://github.com/HSLdevcom/digitransit-ui/pull/4232

**Comment by leonardehrenfried** [comment]
I took the liberty to improve your ticket description since it was a little too bare.

**Comment by jpidelatorre** [comment]
Thanks!

**Comment by leonardehrenfried** [comment]
My hope is that with the next upstream merge this will be fixed.

**Comment by jpidelatorre** [comment]
I guess it should. I think we need a solution to the module resolution problem. To test changes like this locally.
