### ISSUE TITLE
Disable via points

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#597]
This has been implemented upstream (https://github.com/HSLdevcom/digitransit-ui/pull/4231/files) but as of writing this ticket it's not merged downstream yet.

**Comment by nghanem-poet-egypt** [comment]
@leonardehrenfried Can you please merge it as we discussed and tell us when it's merged?

**Comment by leonardehrenfried** [comment]
@andreashelms will
