### ISSUE TITLE
Compute CAR_PARK instead of CAR when destination is in Herrenberg old town

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#598]
When requesting a car route to the old town of Herrenberg, we don't want to show routes driving all the way to the destination. We would much rather see results where you drive to a parking lot and walk the rest.

For this reason when sending a request for a car route, please modify the logic as follows:

- if the destination is outside the following GeoJSON polygon https://gist.github.com/leonardehrenfried/a49da3fd68a42031767895ca33bba9d2 then use the modes
```
{ mode: CAR }
```

- if the destination is inside the GeoJSON polygon then use the modes
```
{ mode: CAR, qualifier: PARK }
```

The code for this lives in `SummaryPage`: https://github.com/stadtnavi/digitransit-ui/blob/abcd7f58dfe01f2baee299528a142b0bcc7e9927/app/component/SummaryPage.js#L801

**Comment by andreashelms** [comment]
@leonardehrenfried There already is a plan ParkAndRide defined with this modes:

` transportModes: [
            { mode: CAR, qualifier: PARK }
            { mode: BUS }
            { mode: RAIL }
            { mode: SUBWAY }
          ]`

It don't really get what is the difference to that. Or do you mean a car route where you can leave your car at a parking space at destination?

**Comment by leonardehrenfried** [comment]
The latter.

we want to compute two requests:

1. One for driving your car all the way to the destination: `transportModes: [ { mode: CAR  } ]`
2. One for driving _near_ your destination, parking your car and then walking: `transportModes: [ { mode: CAR  , qualifier: PARK} ]`

**Comment by leonardehrenfried** [comment]
@Denis306 @andreashelms @GustavoTCh @SamuelRioTz 

After having talked to @hbruch about this we decided to change the feature quite significantly. It will probably be easier to implement but I think the app devs already implemented an earlier version. Sorry about the back and forth.

**Comment by GustavoTCh** [comment]
@leonardehrenfried this is not very complicated, @Denis306 Could you create a task in the application board?

**Comment by Denis306** [comment]
@GustavoTCh Done.
