### ISSUE TITLE
Use new car and bike parking lots map layer datasource

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#604]
Right now the bike parking and car parking layers use two different sources and two different classes for fetching the data.

However, we moved and combined the data source in the backend and there is now only a single data source for both types of parking.

Just like with the stops, if one of the layers is activated in the layer switcher, you need to fetch the data for both and then filter out the parking lots that you do/don't want to display client-side.

The data format has changed quite a bit but all the information that you need for both icons and side panels should still be there. If it isn't, please get in touch.

A JSON representation of the new data is this:

```
      // this is a bicycle parking station
      {
        "name": "Bicycle parking",
        "lon": 7.7667109000000005,
        "lat": 48.578502300000004,
        "imageUrl": null,
        "tags": [
          "osm:amenity=bicycle_parking"
        ],
        "anyCarPlaces": false
      },
     // this is a statically derived park and ride parking lot
      {
        "name": "P+R",
        "lon": 8.497435600000001,
        "lat": 47.947423150000006,
        "imageUrl": null,
        "tags": [
          "osm:amenity=parking"
        ],
        "anyCarPlaces": true
      },
     // this is a dynamically created and updated parking lot that receives live updates about available spaces
     {
        "name": "Nufringer Tor",
        "lon": 8.870266,
        "lat": 48.597865,
        "capacity": {
          "carSpaces": 242
        },
        "availability": {
          "carSpaces": 142
        },
        "imageUrl": null,
        "tags": [
          "lot_type:Parkhaus",
          "address:Nufringer Tor",
          "forecast:false"
        ],
        "anyCarPlaces": true
      },
```      

The base URL to fetch the layer information from is 
```
API_URL/routing/v1/router/vectorTiles/parking/
```

If you want to preview the data in the layer, you can use a combination of curl and protoc.
```
curl https://api.dev.stadtnavi.eu/routing/v1/router/vectorTiles/parking/17/68763/45237.pbf | protoc --decode_raw
```

Fixes https://github.com/stadtnavi/digitransit-ui/issues/445

**Comment by leonardehrenfried** [comment]
BTW, I implemented a tiny part of this already: https://github.com/stadtnavi/digitransit-ui/commit/b6ae8b6d8bd8bb6a2e140ef75afc49308214ef6f

**Comment by andreashelms** [comment]
@leonardehrenfried Could you send tags property of response also send as an escaped JSON string like capacity:

`capacity: "{"bicyclePlaces":null,"carPlaces":100,"wheelchairAccessibleCarPlaces":null}"`

Currently tags property value looks like that:

`tags: "lot_type:Parkplatz,address:Naturfreibad,forecast:false,state:nodata"`

**Comment by andreashelms** [comment]
@leonardehrenfried Looks like `lot-type` 'Park-Carpool' and 'Barrierefreier-Parkplatz' are gone. Should the icons be removed, then?

**Comment by leonardehrenfried** [comment]
I can see Barrierefreier-Parkplatz in the graphQL API:
```
      {
        "name": "Oberamt - Parkplatz für Menschen mit Behinderung",
        "lon": 8.8705467,
        "lat": 48.5963798,
        "capacity": {
          "carSpaces": null
        },
        "availability": null,
        "imageUrl": null,
        "tags": [
          "lot_type:Barrierefreier-Parkplatz",
          "address:Oberamt - Parkplatz für Menschen mit Behinderung",
          "forecast:false",
          "state:nodata"
        ],
        "anyCarPlaces": true
      },
```

Is it not in the vector tiles?

**Comment by leonardehrenfried** [comment]
> @leonardehrenfried Could you send tags property of response also send as an escaped JSON string like capacity:

I'm not sure I can follow - aren't we sending the tags already? Is this a typo?

> `capacity: "{"bicyclePlaces":null,"carPlaces":100,"wheelchairAccessibleCarPlaces":null}"`
> 
> Currently tags property value looks like that:
> 
> `tags: "lot_type:Parkplatz,address:Naturfreibad,forecast:false,state:nodata"`

So you want the tags to be encoded like this ["lot_type:Parkplatz","address:Naturfreibad","forecast:false","state:nodata"] ?

**Comment by andreashelms** [comment]
> > @leonardehrenfried Could you send tags property of response also send as an escaped JSON string like capacity:
> 
> I'm not sure I can follow - aren't we sending the tags already? Is this a typo?
> 
> > `capacity: "{"bicyclePlaces":null,"carPlaces":100,"wheelchairAccessibleCarPlaces":null}"`
> > Currently tags property value looks like that:
> > `tags: "lot_type:Parkplatz,address:Naturfreibad,forecast:false,state:nodata"`
> 
> So you want the tags to be encoded like this ["lot_type:Parkplatz","address:Naturfreibad","forecast:false","state:nodata"] ?

Like this: 

`"{"lot_type":"Parkplatz","address":"Naturfreibad","forecast":false,"state":"nodata"}"`

exactly the way like `capacity` is encoded. This way it's easy to parse the information for further processing.

**Comment by leonardehrenfried** [comment]
I see.
In can implement that.

**Comment by andreashelms** [comment]
> I can see Barrierefreier-Parkplatz in the graphQL API:
> 
> ```
>       {
>         "name": "Oberamt - Parkplatz für Menschen mit Behinderung",
>         "lon": 8.8705467,
>         "lat": 48.5963798,
>         "capacity": {
>           "carSpaces": null
>         },
>         "availability": null,
>         "imageUrl": null,
>         "tags": [
>           "lot_type:Barrierefreier-Parkplatz",
>           "address:Oberamt - Parkplatz für Menschen mit Behinderung",
>           "forecast:false",
>           "state:nodata"
>         ],
>         "anyCarPlaces": true
>       },
> ```
> 
> Is it not in the vector tiles?

Now it's there. I just set a filter incorrectly.

**Comment by andreashelms** [comment]
@leonardehrenfried And yet another question: What values does property `state` have, if it's not `OPERATIONAL`? And the former API returned a property called `notes`. Does this still exist?

**Comment by leonardehrenfried** [comment]
https://github.com/mfdz/OpenTripPlanner/blob/e9c326a301bb131317a0d9ec0bf14783666fa989/src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java#L101

OPERATIONAL
TEMPORARILY_CLOSED
CLOSED

**Comment by andreashelms** [comment]
> https://github.com/mfdz/OpenTripPlanner/blob/e9c326a301bb131317a0d9ec0bf14783666fa989/src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java#L101
> 
> OPERATIONAL
> TEMPORARILY_CLOSED
> CLOSED

👍  And I just realized `notes` ist still there, now it's called `note`.

**Comment by andreashelms** [comment]
![image](https://user-images.githubusercontent.com/21622725/122418639-a3793c00-cf8a-11eb-9faf-26144a5a290a.png)

Sometimes response contains `note` with English texts, and sometimes German. Is there some way of setting the desired language returned?

**Comment by leonardehrenfried** [comment]
So there was an issue in the data where this parking lot didn't have a German note. It should be gone now.

**Comment by leonardehrenfried** [comment]
> > > @leonardehrenfried Could you send tags property of response also send as an escaped JSON string like capacity:
> > 
> > 
> > I'm not sure I can follow - aren't we sending the tags already? Is this a typo?
> > > `capacity: "{"bicyclePlaces":null,"carPlaces":100,"wheelchairAccessibleCarPlaces":null}"`
> > > Currently tags property value looks like that:
> > > `tags: "lot_type:Parkplatz,address:Naturfreibad,forecast:false,state:nodata"`
> > 
> > 
> > So you want the tags to be encoded like this ["lot_type:Parkplatz","address:Naturfreibad","forecast:false","state:nodata"] ?
> 
> Like this:
> 
> `"{"lot_type":"Parkplatz","address":"Naturfreibad","forecast":false,"state":"nodata"}"`
> 
> exactly the way like `capacity` is encoded. This way it's easy to parse the information for further processing.

I'm sorry but I realised that I cannot do that: it's not guaranteed that these strings are always key:value, they can be any strings. This means that I can't change the API.

Is it possible to do the parsing in the client?

**Comment by leonardehrenfried** [comment]
```
curl -I https://api.dev.stadtnavi.eu/routing/v1/router/vectorTiles/parking/17/68763/45237.pbf
HTTP/2 200 
server: nginx/1.14.2
date: Fri, 18 Jun 2021 08:50:55 GMT
content-type: application/x-protobuf
content-length: 2294
cache-control: no-transform, max-age=60
access-control-allow-credentials: false
```

**Comment by andreashelms** [comment]
![image](https://user-images.githubusercontent.com/21622725/122536410-c8ba8880-d024-11eb-9022-7215291667f9.png)

I just realized browser already serves data from cache because of the configured cache-control (0B transfered via network with second request). So I think the implementation is fine.

**Comment by ahmed-nawar** [comment]
@leonardehrenfried Can you please validate this issue and move it if done?

**Comment by leonardehrenfried** [comment]
I did.
