### ISSUE TITLE
Park & Ride fixes

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#606]
## Icon

https://dev.stadtnavi.eu/reiseplan/Nufringen%3A%3A48.6224388%2C8.8881021/Marktplatz%2C%2071083%20Herrenberg%3A%3A48.5964113%2C8.869932/parkAndRide?time=1623402989

![121673188-ee89df80-cab0-11eb-95ce-a488cf65ca03](https://user-images.githubusercontent.com/151346/122024701-f6a39100-cdc8-11eb-8243-a40c81667cd4.png)

When the car leg is quite short the bars don't show the car anymore. I'm not sure if this is intentional as it wouldn't fit or if it's a bug. Please investigate.

## Cached route

Steps to reproduc

- Search for a route from Herrenberg to Nufringen
- Click on park and ride
- Search from Herrenberg to Ehningen
- Click on Park and Ride
- Search again from Herrenberg to Nufringen
- Click on Park and Ride
- Route comes from the cache but there is an error in the console

![Screenshot from 2021-06-11 12-40-48](https://user-images.githubusercontent.com/151346/121674378-470dac80-cab2-11eb-9dbe-2101c052094e.png)

## Modes

The list of public transport modes is currently hardcoded and doesn't take the settings into account: https://github.com/stadtnavi/digitransit-ui/blob/fbfd12f91b26b098033b77aca7e4dc27e1297eea/app/component/SummaryPage.js#L867

Please read the mode settings and pass them accordingly.

**Comment by patrickbeck1337** [comment]
Hey @leonardehrenfried I don't get the icon issue you describe above. Whats the actual wrong behaviour here?

**Comment by leonardehrenfried** [comment]
Sorry, the first point is a little confused. I will update it.

**Comment by leonardehrenfried** [comment]
Updated.

**Comment by patrickbeck1337** [comment]
Thx that’s more clear.

**Comment by andreashelms** [comment]
@leonardehrenfried The issue with the cached route will also be solved by removing relay cache from `client.js`. Is there already a ticket for that?

**Comment by leonardehrenfried** [comment]
No, there isn't. Can you create a PR - no need for a ticket.
