### ISSUE TITLE
No name or info showed on car pool POI when displayed in the popup list

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#611]
When the map is zoomed out and you click on the car pool POI the car pool station ID is shown in the popup list and not the actual name of the car pool station:
![image](https://user-images.githubusercontent.com/63004289/121790386-3b6bd400-cbdf-11eb-838c-c0fc93b3b8a0.png)

**Comment by jpidelatorre** [comment]
The information coming from the backend for car share points doesn't include the name.

This is the URL: https://api.dev.stadtnavi.eu/routing/v1/router/vectorTiles/citybikes/15/17192/11308.pbf

The only fields that come from it are the id and the networks.

![image](https://user-images.githubusercontent.com/104569/121839520-40e12100-cca8-11eb-885b-e2353321bbe0.png)

**Comment by jpidelatorre** [comment]
@the-infinity Can you check this one out? I think it is also a problem in the backend.

**Comment by the-infinity** [comment]
I can, but I don't provide carsharing data, so I can just give you random thoughts without relevance *g

I suppose this is something for @leonardehrenfried (?).

**Comment by jpidelatorre** [comment]
No problem then. Let's wait for Leonard to check this.

**Comment by leonardehrenfried** [comment]
It's true that the map tiles don't contain the name however when you click more on an icon then more information is fetched via the GraphQL API which includes the name.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-14 09-34-57](https://user-images.githubusercontent.com/151346/121855571-cc33d400-ccf3-11eb-8fb2-3feaef8e43d7.png)

^^ This is the request.

**Comment by jpidelatorre** [comment]
@leonardehrenfried That's true. However, when rendering the `select row`, we don't have that information yet, and calling this endpoint at this point would mean we have to call it twice if the user selects a station.

Also, other endpoints do have the name of the markers in the tile. For instance, parking lots have 15 fields, including the name.

![image](https://user-images.githubusercontent.com/104569/122000275-8c64ff00-cd7c-11eb-9301-2586789e975c.png)

**Comment by leonardehrenfried** [comment]
I misunderstood the original point that Denis raised and I checked the code right now. The name should actually be already sent so I will investigate.

**Comment by Denis306** [comment]
@leonardehrenfried Any update on this?

**Comment by leonardehrenfried** [comment]
Thanks for reminding me. I'm currently testing a fix on dev and will have an update in a few minutes.

**Comment by leonardehrenfried** [comment]
Ok, there was a really silly bug in the backend which I fixed right now. Sorry for this taking forever!

```
curl https://api.dev.stadtnavi.eu/routing/v1/router/vectorTiles/citybikes/15/17192/11308.pbf | protoc --decode_raw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   181  100   181    0     0   1371      0 --:--:-- --:--:-- --:--:--  1371
3 {
  1: "citybikes"
  2 {
    2: "\000\000\001\001\002\002"
    3: 1
    4: "\t\363\037\256R"
  }
  2 {
    2: "\000\003\001\004\002\005"
    3: 1
    4: "\t\223\013\227\007"
  }
  3: "id"
  3: "name"
  3: "networks"
  4 {
    1: "80104"
  }
  4 {
    1: "Hasenplatz"
  }
  4 {
    1: "car-sharing"
  }
  4 {
    1: "cargobike-herrenberg"
  }
  4 {
    1: "Cargobike TUG Herrenberg"
  }
  4 {
    1: "cargo-bike"
  }
  5: 4096
  15: 2
}
```

**Comment by leonardehrenfried** [comment]
You should get the proper name now.

**Comment by jpidelatorre** [comment]
Works like a charm.

![image](https://user-images.githubusercontent.com/104569/122528312-2b426300-cfea-11eb-8308-e2ea5b67e4a0.png)

**Comment by leonardehrenfried** [comment]
:facepalm: So sorry I didn't realise earlier. If you want to know what the problem was: https://github.com/mfdz/OpenTripPlanner/commit/247b47a8fac8881022426c5de68c88e660ee1840

The version before looks correct but isn't.

**Comment by Denis306** [comment]
@leonardehrenfried can this issue be closed?

**Comment by leonardehrenfried** [comment]
I put it "on dev".

**Comment by leonardehrenfried** [comment]
QA team will close.
