### ISSUE TITLE
Missing Charging stations on map

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#612]
Some charging stations are missing on the map. Like the one at the "A81" Autobahn, although it is there as per @the-infinity.

**Comment by jpidelatorre** [comment]
There's this charging station in A81.

![image](https://user-images.githubusercontent.com/104569/121833379-391a8000-cc9a-11eb-8969-273cc1d11a4d.png)

With it, there are only 7 stations on the entire map and those are all of the charging stations that the backend sends (URL: `https://ochp.next-site.de/tiles/`). I think it is a problem in the backend.

**Comment by the-infinity** [comment]
Hmm. Yes. Now it's there. Maybe it was a connection issue during the test?

**Comment by jpidelatorre** [comment]
Probably it was.

**Comment by the-infinity** [comment]
So I believe this is a beloved "can't reproduce"-bug. :)

**Comment by jpidelatorre** [comment]
@Denis306 Should we close this?

**Comment by Denis306** [comment]
@jpidelatorre @the-infinity Yes. Closing it as it is not reproducable.
