### ISSUE TITLE
Live status of charging stations

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#613]
The charging stations should also have an availability indicator like for example the parking garages.
![image](https://user-images.githubusercontent.com/63004289/121807785-ee771480-cc55-11eb-9482-f0936142d7fc.png)

This is the only chariging station in Herrenberg that can have a live status indicator right now as it is the only one sending "availavility" data:
https://herrenberg.beta.stadtnavi.eu/ladestationen?lat=48.599106021717546&lng=8.870450779795647&name=Parkplatz+Benzstra%C3%9Fe&stationId=2950&capacity=2&available=2

**Comment by Denis306** [comment]
@the-infinity could you please provide some information on how to do this though? When we discussed the topic of displaying the availability in the side panel you mentioned that there are no charging stations in Herrenberg that send data on availability. Therefore you set the status UNKNOWN. Right now all the charging stations are using that which is why the availability is also always 0. (cc. @hbruch @leonardehrenfried)

**Comment by the-infinity** [comment]
There's one chargestation which has a live status in Herrenberg: the one in Benzstraße 10. Every other has "unknown" status. See this thingsboard enhancer: https://github.com/stadtnavi/thingsboard-json-enhancer/blob/main/templates/charging-stations/charging-stations-ocpi.json

**Comment by Denis306** [comment]
@the-infinity Yes, I was just trying to let everyone know, that the expected behavior right now is to only have an availability indicator at the charge station in the Benzstraße 10 in Herrenberg.
