### ISSUE TITLE
All charging stations are named "TEST" in the popup

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#614]
Currently all the charging stations are named "TEST" in their popups when clicking on them.
![image](https://user-images.githubusercontent.com/63004289/121807034-b6220700-cc52-11eb-9130-6f2629d6dce1.png)

The actual name should be displayed here.

**Comment by jpidelatorre** [comment]
The name for the map markers is coming from the backend and the value is always TEST:

 https://ochp.next-site.de/tiles/18/137532/90465.mvt
 
 There are other ways to solve this, but I think that would mean we modify the map only for charging stations. Or, maybe we are pointing to the wrong backend.

**Comment by the-infinity** [comment]
Ah, sorry, this was actually a test of a field value. I can remove the field if you want, chargestations do not really habe names.

**Comment by jpidelatorre** [comment]
What is that field in the title?

![image](https://user-images.githubusercontent.com/104569/121841326-0da09100-ccac-11eb-82d2-9583000ad75d.png)

**Comment by the-infinity** [comment]
Ah, good point. To correct myself: there are names, but they are optional: https://github.com/ocpi/ocpi/blob/master/mod_locations.asciidoc#131-location-object

In case of Herrenbergs chargestatons we actually set a name: https://github.com/stadtnavi/thingsboard-json-enhancer/blob/main/templates/charging-stations/charging-stations-ocpi.json . But you can't rely on that there is always a name.

**Comment by jpidelatorre** [comment]
Oh, I see. But, can you send it down when it is present? Because most stations show a name when you open them.

**Comment by the-infinity** [comment]
Maybe it's an idea to provide the address instead of the name if the name is not set? Then you always can have a popup with name, and the address is a required field.

**Comment by jpidelatorre** [comment]
I think that would be a good idea.

**Comment by the-infinity** [comment]
Done. :)

**Comment by jpidelatorre** [comment]
Great! It works like a charm.

![image](https://user-images.githubusercontent.com/104569/121843792-ec8e6f00-ccb0-11eb-9228-1eec4dad659b.png)

**Comment by hbruch** [comment]
I suggest that, in the popup, you insert the localized object category before the address, like "Charging station Seeländer Areal Herrenberg". There might be locations, were multiple POIs overlap and the popup is used as a selector which POI to show details for.

**Comment by ahmed-nawar** [comment]
The pop ups don't have the localized object category before the address, as @hbruch suggested. Is this the required behavior?

**Comment by Denis306** [comment]
@ahmed-nawar I am closing this ticket and created a new one #658 to discuss the localized object category.
