### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#616]
- When the language chosen is "English", there are many components that still appear in "German".

1. Ruftaxi message
![translation of Ruftaxi message](https://user-images.githubusercontent.com/83356918/121811578-18840300-cc65-11eb-8b60-73637c011bc2.png)

2. Details of public toilets
![translation details of public toilets](https://user-images.githubusercontent.com/83356918/121811610-305b8700-cc65-11eb-83d1-83cdb7dd5ccb.png)

3. Details of bicycle service stations and stores
![opening times translation missing in bicycle service stations](https://user-images.githubusercontent.com/83356918/121811653-57b25400-cc65-11eb-96ce-2b5d7021e4ad.png)

- When the language chosen is "German", the calendar in the tab "timetable" of any station shows the title "day" instead of "Tag"
![translation timetable](https://user-images.githubusercontent.com/83356918/121811763-a4962a80-cc65-11eb-9a66-32908b8bd257.png)

Beta version:
 image: mfdz/opentripplanner:otp2-a0c0ea9082ac93f3b3e62bdb23c9c8da1622e632
 image: stadtnavi/digitransit-ui:f62cb548ded409d7c02fd0744fc798ffbdfc8a8d
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:6af73d1f1b27aa379596b4b270a24514eed6d95d
Last version change: 2021-06-12T07:47:43+0200

**Comment by jpidelatorre** [comment]
The messages for the Ruftaxi come straight from the backend:

https://github.com/stadtnavi/digitransit-ui/blob/dfcaec2d906a1cef9d4b4983a7f5edf5827778f1/app/component/ItineraryTab.js#L391-L399

Besides that, the rest of the issues were solved.

**Comment by leonardehrenfried** [comment]
Yes, there is a technical limitation which prevents the Ruftaxi messages from being translated.
