### ISSUE TITLE
The timetable of a metro station in Stuttgart returns an error

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/digitransit-ui#623]
Scenario:
- Open the details of the metro station: Schlossplatz in Stuttgart
- Go to the tab "timetable"
- The app will return an error
![metrostation_Schlossplatz_error timetable](https://user-images.githubusercontent.com/83356918/121812910-1ec8ae00-cc6a-11eb-955f-13ca5865b898.png)

Beta version:
 image: mfdz/opentripplanner:otp2-a0c0ea9082ac93f3b3e62bdb23c9c8da1622e632
 image: stadtnavi/digitransit-ui:f62cb548ded409d7c02fd0744fc798ffbdfc8a8d
 image: stadtnavi/hsl-map-server:f386dcbf8ea8d9f99a9e7772e0324bed2e20fb2a
 image: stadtnavi/fares-service:6af73d1f1b27aa379596b4b270a24514eed6d95d
Last version change: 2021-06-12T07:47:43+0200

**Comment by leonardehrenfried** [comment]
I fixed this today: https://dev.stadtnavi.eu/haltestellen/hbg%3Ade%3A08111%3A6022%3A1%3A2
