### ISSUE TITLE
Change the wording of the walking speeds in the german itinerary settings

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#625]
The different walking speeds have bad wording in german and currently have five speeds.
![image](https://user-images.githubusercontent.com/63004289/121821177-a5e04b00-cc97-11eb-88b9-2ec2af0a235b.png)
![image](https://user-images.githubusercontent.com/63004289/121847262-976e4f80-cce8-11eb-8579-db59babbb7f9.png)

Please change this for it to only propose 3 options with the following names:

English / German

Slow 2,5 km/h  /  Am wenigsten 2,5 km/h    ->   Slow 3 km/h  /  Langsam 3 km/h
Average 4,3 km/h  /  Standard 4,3 km/h    ->   Normal 5 km/h  /  Normal 5 km/h
Fast 8 km/h  /  Am meisten 8 km/h    ->   Fast 7 km/h  /  Schnell 7 km/h

(This means you can delete the "Calm / Weniger" & "Prompt / Mehr" options)

**Comment by Denis306** [comment]
@hbruch @leonardehrenfried Could you approve if the wording like this is okay?

**Comment by MartinH-open** [comment]
The proposed German translations appear valid for me. 
But I wonder a bit if we really need these 5 categories: what about just 3 speed categories:
slow (langsam) = 3km/h; medium/normal (mittel/normal) = 5km/h; fast (schnell) = 7 km/h
For referenz see: https://de.wikipedia.org/wiki/Gehen
For short distances the speed is often a bit higher then the average value for long walks.
Can we reduce the selection to just 3 speeds? 
The current Standard setting of 4,3 km/h looks artificial. The intervalls between the displayed values differs, strange.
Keep it simple if possible.

**Comment by hbruch** [comment]
I agree with @MartinH-open  suggestions. Use three options only please, and use the speeds and naming suggestions proposed by Martin.
