### ISSUE TITLE
When there is no availability information on charging stations, the capacity should be displayed

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#626]
The behavior on how the capacity is currently being displayed is missleading. 

The only charging station with availability data/live status data  is the following one:
https://herrenberg.beta.stadtnavi.eu/ladestationen?lat=48.599106021717546&lng=8.870450779795647&name=Parkplatz+Benzstra%C3%9Fe&stationId=2950&capacity=2&available=2
![image](https://user-images.githubusercontent.com/63004289/121850904-c0ddaa00-cced-11eb-823b-e88b771c019f.png)

If this is the case, displaying the availability in the sidebar is correct.

If there is no availability data/live status data, the status will be set to UNKNOWN in the backend as implemented by @the-infinity.
![image](https://user-images.githubusercontent.com/63004289/121850800-9986dd00-cced-11eb-9e69-469cad9036d3.png)

If that is the case, we should display the capacity of the charging stations and not the availability, e.g.:
 "5 charging slots"  /  "5 Ladeplätze"

**Comment by patrickbeck1337** [comment]
Fixed within #579

<img width="1635" alt="Screenshot 2021-06-14 at 21 31 02" src="https://user-images.githubusercontent.com/23075804/121948738-ea332000-cd57-11eb-9462-ec1150f9a96c.png">
