### ISSUE TITLE
Feedback from Ansgar: bus station icons get cut 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#637]
When user changes the zoom layer, the bus station icon gets cut. 

![image](https://user-images.githubusercontent.com/84382750/122086493-0ee4d180-ce04-11eb-8d1d-641a11f9c899.png)

![image](https://user-images.githubusercontent.com/84382750/122086420-fb396b00-ce03-11eb-86c3-e2ed513f6b30.png)

**Comment by jpidelatorre** [comment]
@leonardehrenfried I think this is the same problem that appeared some weeks ago when a marker is too close to the boundary between two tiles and one of the tiles doesn't have the information to render the marker.

![image](https://user-images.githubusercontent.com/104569/122344202-81dd6d80-cf14-11eb-8c95-e2d5db2868cc.png)

**Comment by leonardehrenfried** [comment]
My observation is a bit different.

To me it seems that entire tiles are empty, particularly the one around the train station.

![Screenshot from 2021-06-17 09-39-07](https://user-images.githubusercontent.com/151346/122353110-0699ad00-cf50-11eb-93c4-010220dcbfa6.png)

It dependends on the zoom level.

![Screenshot from 2021-06-17 09-39-12](https://user-images.githubusercontent.com/151346/122353154-10bbab80-cf50-11eb-9819-8489aa0b5b5d.png)

Not clue if that is a frontend or backend problem. Can you figure out what the tile is a check if you get a response from the server?

**Comment by jpidelatorre** [comment]
It is not the entire tile, but it does affect some tiles in particular.

![image](https://user-images.githubusercontent.com/104569/122512979-b36b3d00-cfd7-11eb-9ef8-356ccbf02890.png)

I'm taking a look at the information from the server, but it's confusing.

**Comment by jpidelatorre** [comment]
@leonardehrenfried I think I found the problem.
