### ISSUE TITLE
Feedback from Ansgar (high priority): the number of available places in charging stations is incorrect

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#638]
The system always displays the availability in charging stations as follows: **0 from X** are available. 

There is no occupancy data available for charging stations except for Parkplatz Benzstraße. 

Here are some examples for affected stations: 
https://herrenberg.stadtnavi.de/ladestationen?lat=48.59410518761695&lng=8.872807770967484&name=Hotel+Gasthof+Hasen&stationId=2953&capacity=1&available=0
https://herrenberg.stadtnavi.de/ladestationen?lat=48.600207322778374&lng=8.865510821342468&name=Auto+Bebion&stationId=2952&capacity=2&available=0
https://herrenberg.stadtnavi.de/ladestationen?lat=48.60292821170211&lng=8.87090876698494&name=VW+Autohaus+Weeber&stationId=2956&capacity=4&available=0
https://herrenberg.stadtnavi.de/ladestationen?lat=48.599106021717546&lng=8.870450779795647&name=Parkplatz+Benzstra%C3%9Fe&stationId=2950&capacity=2&available=0

**Comment by leonardehrenfried** [comment]
A fix is already in the pipeline: https://github.com/stadtnavi/digitransit-ui/pull/633

**Comment by leonardehrenfried** [comment]
A fixed has been rolled out to all envs. Please inform Ansgar.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-17 12-04-58](https://user-images.githubusercontent.com/151346/122376258-466a8f80-cf64-11eb-897b-3d1cb42597f8.png)
