### ISSUE TITLE
Ruftaxi (on demand) time is incorrect

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#639]
\
![Screenshot from 2021-06-15 19-27-26](https://user-images.githubusercontent.com/151346/122097469-fed2ef00-ce0f-11eb-82e4-d79820e5ce4d.png)

It says 1 hour but it there isn't a route that is longer than 39 minutes.

https://dev.stadtnavi.eu/reiseplan/Nufringen%3A%3A48.6224388%2C8.8881021/Ziegelfeldweg%2C%2071083%20Herrenberg%3A%3A48.5977042%2C8.886265?time=1623789000

**Comment by Beck-berry** [comment]
![image](https://user-images.githubusercontent.com/46535522/122261370-9ef24c00-ced4-11eb-83c9-9c70e957c351.png)

Weird thing, I have the correct time displayed, so I cannot reproduce the problem. Could you please check if it's still there for you?

**Comment by leonardehrenfried** [comment]
Erm, yeah. I fixed it on the server-side and forgot that this ticket existed. :flushed:

**Comment by leonardehrenfried** [comment]
Sorry about that.

**Comment by Beck-berry** [comment]
No worries :smile:
