### ISSUE TITLE
Internal Server Error when changing language

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#649]
- Click on an icon on the map ex: Public toilet
- Change the language from the settings
- Internal error appears

![image](https://user-images.githubusercontent.com/84456072/122226121-efa67c80-ceb5-11eb-8d03-819604c1b118.png)

**Comment by ahmed-nawar** [comment]
The error appears only when you are viewing one of the two icons: 
- Public Toilets
- LoRaWAN Gateways
![image](https://user-images.githubusercontent.com/84456072/122226651-79564a00-ceb6-11eb-82d8-d65bfb93e421.png)

**Comment by ahmed-nawar** [comment]
Similar to https://github.com/stadtnavi/digitransit-ui/issues/620

**Comment by leonardehrenfried** [comment]
I think it's exactly the same. Lets close it.
