### ISSUE TITLE
P+R faulty navigation between itineraries 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#659]
1. Try this route [This route](https://herrenberg.beta.stadtnavi.eu/reiseplan/Kleintierz%C3%BCchterverein%20Nufringen%2C%2071154%20Nufringen%3A%3A48.623388649999995%2C8.906790891010605/Krone%2C%20Kelterplatz%204%2C%2071083%20Herrenberg%3A%3A48.577052949999995%2C8.92293205/parkAndRide?locale=de&mapMode=bicycle&time=1624003200)

2. Choose p+r mode
3. Click on the details of the first route
4. Now click on the arrow to the right to view the next option 

Current behavior: the next itinerary is only transit route not a P+R route although on the overview 4 P+R itineraries were shown 
Also if I click the arrow to the left to go back to the P+R option it is not shown anymore. 

Expected: next and previous should navigate in the p+r options not show other options 

BTW same behavior happens in the mobile apps

Screenshot come in the next comment

**Comment by nghanem-poet-egypt** [comment]
4 P+R itineraries shown

![Screenshot_20210617-220713_Chrome.jpg](https://user-images.githubusercontent.com/84389152/122465953-f79b1500-cfb8-11eb-9029-c6569e90f980.jpg)

Click on next
![Screenshot_20210617-220727_Chrome.jpg](https://user-images.githubusercontent.com/84389152/122466018-0da8d580-cfb9-11eb-9889-fdf4f925317d.jpg)

Now instead of 4 only 2 options are available and the next route is a transit route not P+R and the back button also shows a transit route
![Screenshot_20210617-220733_Chrome.jpg](https://user-images.githubusercontent.com/84389152/122466099-274a1d00-cfb9-11eb-90cf-3fc6623fd83d.jpg)

**Comment by leonardehrenfried** [comment]
It's on beta.
