### ISSUE TITLE
Feedback User 265: number of wheelchair-accessible parking spaces is wrong 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#668]
The system is displaying that 2 out of 1 wheelchair-accessible parking spaces are free. 
https://herrenberg.stadtnavi.de/parkplaetze?free=11&freeDisabled=2&lng=8.869099617004396&lotType=Parkplatz&name=Unterer%20Graben&notes=%7B%7D&openingHours=Mo,We,Th,Fr,Su%2000:00-24:00;%20Tu,Sa%2000:00-02:00,%2014:30-24:00;%20PH%2000:00-24:00&state=many&total=39&totalDisabled=1&url=https://www.herrenberg.de/de/Stadtleben/Erlebnis-Herrenberg/Service/Parkplaetze/Parkplatz?view=publish&item=parkingLocation&id=1002&%E2%AA%AB=48.59498065570909&locale=en

**Comment by leonardehrenfried** [comment]
Could we find out from the city what the total number of wheelchair-accessible parking spaces there is?

**Comment by hbruch** [comment]
This was fixed in the parking spaces data. Will close here.
