### ISSUE TITLE
Carpool suggestions in Near you view

### ISSUE THREAD

**Issue by Beck-berry** [stadtnavi/digitransit-ui#67]
- [ ] show carpool suggestions only for P+M stops close by (for now)
- [x] on click go to website of the offer
- [x] add a small symbol indicating external link (like a small arrow)
- [x] add agency logos (place of route number)
agency name in DepartureRowContainer: departure.pattern.route.agency.name (Fahrgemeinschaft.de)
- [x] show to + from if place is enough
- [x] round times to 5 min

Items are ordered in decreasing priority

**Comment by meromisi** [comment]
![Screenshot_2020-03-06_15-45-53](https://user-images.githubusercontent.com/54352878/76093944-1a6f0900-5fc2-11ea-8700-f4d420db4f4d.png)
the bus departure and next times are not rounded (they are originally :10 and :40)
