### ISSUE TITLE
Feedback from Julian: departure point of the Ruftaxi should be changed 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#679]
station: ZOB Herrenberg

the departure point of the Ruftaxi should lie further to the east, compared to VVS.

![image](https://user-images.githubusercontent.com/84382750/122881348-5c4ccb80-d33b-11eb-88c8-e4bf253d37d5.png)
![image](https://user-images.githubusercontent.com/84382750/122881425-7090c880-d33b-11eb-97a1-a640bf4e7919.png)

**Comment by leonardehrenfried** [comment]
The problem is that we receive the data from VVS themselves. Can we take up the issue with them, @hbruch?

Julian, would you be satisfied with moving the red dot to the east or does the line be moved, too?

**Comment by sara-georgy** [comment]
@leonardehrenfried we don't have to work further on this issue. I'll close it now.
