### ISSUE TITLE
Feedback from Ansgar: Herrenberg does not appear in the location suggestions

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#684]
Feedback number: 282 

When Tübingen is selected as the origin, Herrenberg does not appear in the destination suggestions. 

![image](https://user-images.githubusercontent.com/84382750/122935087-59b89900-d370-11eb-8fac-e421c6965fa1.png)

**Comment by MartinH-open** [comment]
Same is true when starting from Böblingen.
Similar for Weil der Stadt : but here you enter the whole word Herrenberg and then it appears in the list.
Strange enough, the "Bahnhof Herrenberg" appear almost everytime you enter "He .."

**Comment by leonardehrenfried** [comment]
Our location bias is quite strong, too strong, but Ansgar's example works for me.

![Screenshot from 2021-06-23 16-43-57](https://user-images.githubusercontent.com/151346/123117657-3cec9600-d442-11eb-9f7f-0461ceb7b68d.png)

**Comment by MartinH-open** [comment]
@leonardehrenfried - your example is the offical web app
in beta version it is not working for me (Win 10  Chrome)
![image](https://user-images.githubusercontent.com/1383111/123141593-d3c44d00-d458-11eb-86cb-85b0629874ab.png)

**Comment by MartinH-open** [comment]
@leonardehrenfried  - please show us your favorite places .. !
 My favorite places include "Bahnhof Herrenberg" - and I think therefore it gets displayed almost everytime.

BTW - I think "Herrenberg" should be in the favorite for everyone by default !  Only if you delete it from the favorites it should be gone ..

**Comment by leonardehrenfried** [comment]
I don't have any favourites at all.

We have reconfigured the search and we don't favour local results quite so heavily anymore. So when I go to Tübingen, I see the following results.

![Screenshot from 2021-06-24 09-35-38](https://user-images.githubusercontent.com/151346/123221988-c9916580-d4cf-11eb-8c18-791c4b2164ca.png)

To me this seems correct.

BTW, generally all environments use the same search service, so there is no (backend) difference between dev, beta or production. Sometimes we build up a new search index and test it out in dev first but this isn't the case at the moment.

**Comment by MartinH-open** [comment]
@leonardehrenfried - thanks for explaining.
I verified the "corrected" search now works for Tübingen, Böblingen, Weil der Stadt ! 
For these origins it is enough to enter "Herr.." at the destination field for "Herrenberg" to show up now.
Thanks for the fix!

**Comment by leonardehrenfried** [comment]
Thanks for the feedback.
