### ISSUE TITLE
Missing translation 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#685]
When the language chosen is German, the following components appear in English. 

- [x] 1.
![image](https://user-images.githubusercontent.com/84382750/122956977-c6885f00-d381-11eb-84a8-3d0a72d88c1f.png)

- [ ] 2.
![image](https://user-images.githubusercontent.com/84382750/122962316-9478fc00-d385-11eb-9f0a-5e4201c4f3be.png)

**Comment by andreashelms** [comment]
@leonardehrenfried The name "Bicycle Parking" of the bike park comes from the backend. Will you change that or how should we deal with that?

**Comment by hbruch** [comment]
![Image](https://github.com/user-attachments/assets/a44c842a-1f4d-4240-9ce2-cce093613316)



![Image](https://github.com/user-attachments/assets/20b42115-d849-4138-96be-b521e9f524ff)

Meanwhile, this is fixed. Closing.
