### ISSUE TITLE
P+R mode: route is displayed in a strange way

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#687]
Origin: Mühlstraße, 71083 Herrenberg
Destination: G.-F.-Händel-Straße, 71083 Herrenberg
Mode: P+R
https://herrenberg.beta.stadtnavi.eu/reiseplan/M%C3%BChlstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59598912311189%2C8.860956430435182/G.-F.-H%C3%A4ndel-Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59477574898104%2C8.879871368408205/parkAndRide/?intermediatePlaces=&locale=de

The map displays the route in a strange way. There are grey lines displayed that are not related to the route. However opening the details of the route, the grey lines disappear. 

![image](https://user-images.githubusercontent.com/84382750/122967937-4bc44180-d38b-11eb-9532-7c56b5a325ca.png)

![image](https://user-images.githubusercontent.com/84382750/122968002-5d0d4e00-d38b-11eb-9f1b-2a97e6817f6c.png)

**Comment by leonardehrenfried** [comment]
These grey lines are intentional as they represent the other, not currently selected routes. In your case it's the bus line 782 going the other direction. If you click on your third result you can see what it means.

**Comment by sara-georgy** [comment]
@leonardehrenfried thank you for your clarification. 
however, I think that the other routes are displayed in a strange way. (See screenshots) Is it normal that the taxi/bus rides in two different directions?
![image](https://user-images.githubusercontent.com/84382750/123059320-f1b69100-d409-11eb-8a50-8ba268c6c870.png)
![image](https://user-images.githubusercontent.com/84382750/123059383-02ff9d80-d40a-11eb-82a2-25ba20e5c466.png)

**Comment by leonardehrenfried** [comment]
The data provided by VVS says that he bus really takes this route: https://herrenberg.stadtnavi.de/routen/hbg:31-782-j21-1/haltestellen/hbg:31-782-j21-1:0:01/hbg:39.T0.31-782-j21-1.5.H

However, I did some digging on their website and found this: https://www.vvs.de/download/Geltungsbereich-StadtTicket-Herrenberg.pdf

This suggests that the bus doesn't turn back on itself but rather goes along Marienstrasse. I am not sure which is correct. It's also possible that the PDF is outdated.

Can you ask someone with local knowledge which is right?

cc @hbruch
