### ISSUE TITLE
Live bus locations doesn't show

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#689]
If the webapp is launched while the toggle for **Bus Positions** is `off`, when I turn the toggle `on` the **Bus Positions** will not show until I refresh the browser.
To reproduce:
- Toggle the checkbox off
- Refresh the browser
- Try to toggle the checkbox on
- It won't show until you refresh the browser

**Comment by ahmed-nawar** [comment]
@leonardehrenfried when will the new live bus locations be available on the Beta version?

**Comment by leonardehrenfried** [comment]
Will be tomorrow morning. You can check dev for a preview: https://dev.stadtnavi.eu/
