### ISSUE TITLE
Timeout when calculating extra routes from Herrenberg train station to Stuttgart train station

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#693]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Seestra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.60771690398517%2C8.876609802246096?time=1624455993

**Reproduce:**
Settings: BUS, TRAIN, METRO, WALK, CAR -> **ON**
1. Click on the link
2. Change time to 23:00
3. Click on P&R

Additional Context:
My observation is that the origin is near a parking

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-23 16-08-52](https://user-images.githubusercontent.com/151346/123111677-62c36c00-d43d-11eb-9b63-3fccdc994ea4.png)

I'm seeing this.

**Comment by ahmed-nawar** [comment]
@leonardehrenfried Can you try different times of the day?

**Weird scenario:**

1. Set time to 16:00 -> No P&R suggestions are returned2. 
2. Set time to 15:00
3. Click on P&R -> No P&R routes appear
4. Click on later departures
5. Many P&R routes appear (Including 16:00) which is very weird

![image](https://user-images.githubusercontent.com/84456072/123118799-3d396100-d443-11eb-811c-c6de9d2248d2.png)

**Comment by ahmed-nawar** [comment]
**Another scenario**
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Stuttgart%20Hauptbahnhof%20(tief)%2C%20Stuttgart%3A%3A48.7830723%2C9.1799271/?time=1624807311

_Reproduce_
1. Click on the link
2. Observe itins
3. Click on the P&R
4. No car leg appears

_Observation:_
When the origin is Bahnhof Herrenberg this weird behavior happens

**Comment by nghanem-poet-egypt** [comment]
@leonardehrenfried Ahmed's last comment has the scenario that I was telling you about today in the morning. When I click on P+R nothing changes, only transit routes are shown.

**Comment by hbruch** [comment]
Not reproducible
