### ISSUE TITLE
cargobike: fare is not displayed correctly

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#694]
The system doesn't show the correct fare when choosing to rent the cargobike for 1 day. 
current behavior: The system shows 0,00€
correct behavior: the system should show 15,00€

![image](https://user-images.githubusercontent.com/84382750/123222015-d1510a00-d4cf-11eb-8ca5-8d07c6b1441f.png)

**Comment by leonardehrenfried** [comment]
@the-infinity can give information about this. I think I heard something about the cargo bikes being free but he will explain.

**Comment by the-infinity** [comment]
Yea, this is not defined until now, so nothing which is shown is final. But this is clearly an interface bug, will fix it.

**Comment by the-infinity** [comment]
Fixed with https://github.com/openbikebox/backend/commit/f09be18bbf716e4a952791f764a9dd03388297de . Was a rounding issue.

**Comment by sara-georgy** [comment]
@the-infinity If I find any new bugs related to the booking of the cargobikes, should I report them or should I wait till the final version is deployed?

**Comment by the-infinity** [comment]
@sara-georgy the final version will be ready in a few month because the payment process will be unclear for some time. so if you find something just report it, I will answer to this. (Except maybe one: the bug that PayPal does not work is intention)
