### ISSUE TITLE
Clicking on Ruftaxi tile causes an error 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#731]
Try this route https://herrenberg.beta.stadtnavi.eu/reiseplan/Stuttgart-Mitte%2C%20%20Stuttgart%3A%3A48.7759%2C9.1798/Kuppingen%2C%2071083%20Herrenberg%3A%3A48.610752%2C8.8431229/onDemandTaxi?time=1625000400

Also happens here: https://herrenberg.beta.stadtnavi.eu/reiseplan/Seestra%C3%9Fe%2025%2C%2071083%20Herrenberg%3A%3A48.59759981451169%2C8.86927127838135/GWW%2C%20Adlerstra%C3%9Fe%203%2C%2071083%20Herrenberg%3A%3A48.58959551996925%2C8.857619762420656/onDemandTaxi?time=1624996800 

when I click on the Ruftaxi tile an error happens and I see this screen: 
![grafik](https://user-images.githubusercontent.com/84389152/123781056-17450e00-d8d4-11eb-957d-54928a2630b7.png)

**Comment by leonardehrenfried** [comment]
@andreashelms This runs into a timeout in the backend. Whilst it ultimately needs to be fixed there, can we hide the tile if this happens?

**Comment by andreashelms** [comment]
Not needed, I can fix this quickly.
