### ISSUE TITLE
Change decimal seperator of the ticket prices from "." to ","

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/digitransit-ui#734]
Please transform the "." (Period) into a "," (Comma) in the ticket prices. The backend currently sends it with a period but we would like to have it with a comma.

**Comment by MartinH-open** [comment]
This display of numbers and prices is a question of the selected front end language settings. That layer should decide how to present this objects to the user.
e.g. for German language setting display "," (Comma) for other languages this might be different.
