### ISSUE TITLE
Investigate display of delay information in digitransit-ui

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#746]
@hbruch has reported that a delayed train's departure time is displayed with a green font. Lets gather the necessary data here.

So there is the config `delayThreshold`: https://github.com/HSLdevcom/digitransit-ui/blob/716bc61734c78ccf3d8b5527324aa81a8e3c80c3/app/configurations/config.default.js#L180

It's currently set to 180s but we override to 60s in Herrenberg.

However, there is also code that checks if the field `departureDelay` is present and it seems that it's just never requested from the server.

It appears that you have to add it to the various GraphQL queries that request the routes.

**Comment by leonardehrenfried** [comment]
Herrenberg's config reduces this to 60s but it seems that the leg's `departureDelay` is never requested from the server. It's the same for upstream.

**Comment by Beck-berry** [comment]
> It appears that you have to add it to the various GraphQL queries that request the routes.

You were right, the query in the ItineraryTab component missed the `departureDelay` field. 


> a delayed train's departure time is displayed with a green font.

It should be orange as I remember... Is it correct?
![image](https://user-images.githubusercontent.com/46535522/125506211-bceca2cd-4c78-419c-a00d-a1a133f95b96.png) or ![image](https://user-images.githubusercontent.com/46535522/125506384-0a8bc77e-3c06-4163-8589-ae31cbbf85fa.png)

We used to have another optional class for this color change:
https://github.com/stadtnavi/digitransit-ui/blob/aa86fc8006a2af2217f5ca38717df71aa2d2a029/app/component/TransitLeg.js#L264

**Comment by Beck-berry** [comment]
Found another bug:
![image](https://user-images.githubusercontent.com/46535522/125507558-7efdf3db-d155-4190-8aac-45a00f18b727.png)
Occurs when the transit leg is realtime but the delay is 0.

Fixed this one :tada:

**Comment by leonardehrenfried** [comment]
> > It appears that you have to add it to the various GraphQL queries that request the routes.
> 
> You were right, the query in the ItineraryTab component missed the `departureDelay` field.
> 
> > a delayed train's departure time is displayed with a green font.
> 
> It should be orange as I remember... Is it correct?
> ![image](https://user-images.githubusercontent.com/46535522/125506211-bceca2cd-4c78-419c-a00d-a1a133f95b96.png) or ![image](https://user-images.githubusercontent.com/46535522/125506384-0a8bc77e-3c06-4163-8589-ae31cbbf85fa.png)
> 
> We used to have another optional class for this color change:
> 
> https://github.com/stadtnavi/digitransit-ui/blob/aa86fc8006a2af2217f5ca38717df71aa2d2a029/app/component/TransitLeg.js#L264

Yes, please restore the DT1 style again:

- A delayed train is displayed in red with the original time displayed but crossed out
- Realtime is green
- Too early is shown as green with the original time crossed out
- Also apply this style to arrival time

Also apply the red/green style to the overview page:

![Screenshot from 2021-07-14 11-36-26](https://user-images.githubusercontent.com/151346/125599899-539594ad-d8c4-493c-baf6-11131c5d2503.png)

**Comment by Beck-berry** [comment]
> Also apply this style to arrival time 

As on the ItineraryTab only the departure times are shown (each time represents the departure time of the corresponding leg), how do you expect this to function? If there is a delay, the start of the next leg (for example if it's walk or ride) is calculated with the delayed time already.

![image](https://user-images.githubusercontent.com/46535522/126037553-d015bb34-9c97-4473-95e6-4061459abcf3.png)


> Also apply the red/green style to the overview page

Did you think of the text line under the legs? Like:

![image](https://user-images.githubusercontent.com/46535522/126038051-8958d2af-f213-4729-9038-532d0064ea71.png)

The start and end times above the legs come from the itinerary (containing walking too which is not "realtime").

**Comment by leonardehrenfried** [comment]
> As on the ItineraryTab only the departure times are shown (each time represents the departure time of the corresponding leg), how do you expect this to function? If there is a delay, the start of the next leg (for example if it's walk or ride) is calculated with the delayed time already.
> 
> ![image](https://user-images.githubusercontent.com/46535522/126037553-d015bb34-9c97-4473-95e6-4061459abcf3.png)

Ah, the time at the bottom doesn't represent the arrival of the train but the start of the bike leg? Hmm, hmm, @hbruch do you have an opinion here?

> > Also apply the red/green style to the overview page
> 
> Did you think of the text line under the legs? Like:
> 
> ![image](https://user-images.githubusercontent.com/46535522/126038051-8958d2af-f213-4729-9038-532d0064ea71.png)
> 
> The start and end times above the legs come from the itinerary (containing walking too which is not "realtime").

Yes, I meant the time at the bottom, not at the top.

**Comment by leonardehrenfried** [comment]
I know that it has been done this way by upstream, but I _do_ find it confusing that it shows the start of the next leg at the bottom.

![Screenshot from 2021-07-21 09-43-09](https://user-images.githubusercontent.com/151346/126451565-1dd25f84-7179-4386-9817-0beb6a242f38.png)

@hbruch Should we try to coordinate with upstream or have they been adamant that they don't want to change it? I can't remember what Joel said.

**Comment by leonardehrenfried** [comment]
@Beck-berry Can you investigate how much work it is to put the arrival time of the public transport leg, including the delay info, there?

**Comment by hbruch** [comment]
Yes, please contact upstream. Probably a feature toggle to activate this behavior makes sense.

**Comment by Beck-berry** [comment]
It wasn't really hard:

![image](https://user-images.githubusercontent.com/46535522/126862373-940574c7-7b3e-4249-a7c3-8e8513100ea7.png)

I added a new component and use it for all the non-transit legs "start time" to display the previous leg's arrival time.
