### ISSUE TITLE
Exclude non-P+R lots from P+R results

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#747]
In the city of Herrenberg we have a lot more detailed information about parking lots. 

This means however that lots are used for P+R when they should not, like the one near the train station where you are only allowed to park for a short amount of time.

For this reason we should add the following request parameters to the P+R request:

```
bannedVehicleParkingTags: ["lot_type:Parkplatz", "lot_type:Tiefgarage", "lot_type:Parkhaus"]
```

Here is a route with an unwanted parking lot.
![Screenshot from 2021-07-14 12-15-17](https://user-images.githubusercontent.com/151346/125605472-30858037-5dc1-4023-ac33-bd6d4f0562da.png)

**Comment by hbruch** [comment]
Please do not bann Park-Carpool, as this would disallow switching to a carpool passing by this parking.

**Comment by leonardehrenfried** [comment]
Ticket corrected.

**Comment by leonardehrenfried** [comment]
After the change it looks like this.

![Screenshot from 2021-07-14 14-15-46](https://user-images.githubusercontent.com/151346/125620410-9bbdeba6-5bd1-4233-9ae6-c27709e4eef8.png)

What is a little strange though is that the parking lot on Bahnhofstr. isn't used in this case (it is in others, so it's not banned). My guess is that because it's complicated to drive there (one-way) and more walking, it's actually faster to drive to Kalkofenstr.
