### ISSUE TITLE
Error with 'Installation: Start production version'

### ISSUE THREAD

**Issue by dancesWithCycles** [stadtnavi/digitransit-ui#755]
Hi folks,
I managed to run this repository in development mode with your help in issue #754.

Now I would like to run it in production mode. According to the installation [doc](https://github.com/stadtnavi/digitransit-ui/blob/next/docs/Installation.md) in the `next` branch, I invoked these instructions.

```
yarn install && yarn setup
yarn run build
yarn run start
```

This time I checked the node version in advance.

```
nvm list
->     v10.24.1
```

However, I only receive the following single line reply.

```
Unbound variable "NODE_OPTS"
```

It does not matter if I add a configuration like this.

```
CONFIG=hbnext yarn run start
```

I appreciate any hint pointing me in the right direction. Cheers!

**Comment by leonardehrenfried** [comment]
Check this out:   # setting a non-empty default value for NODE_OPTS

**Comment by leonardehrenfried** [comment]
Check this out: https://github.com/stadtnavi/digitransit-ui/blob/f867ec91b3be022bf61de3bb7cfae37ea8fd54d7/Dockerfile#L22

**Comment by dancesWithCycles** [comment]
Cheers @leonardehrenfried !
