### ISSUE TITLE
Question: Where is file stadtnavi-social-media-card.png?

### ISSUE THREAD

**Issue by dancesWithCycles** [stadtnavi/digitransit-ui#756]
Hi folks,
How is it going? I am studying this repository and came across a file called `stadtnavi-social-media-card.png` that is used in line 115 of the file [config.hbnext.js](https://github.com/stadtnavi/digitransit-ui/blob/next/app/configurations/config.hbnext.js). However, I do not find a so called file. Who can help? Cheers!

**Comment by leonardehrenfried** [comment]
It's on a different branch: https://github.com/stadtnavi/digitransit-ui/blob/master/static/img/stadtnavi-social-media-card.png

Seems like we neglected to move it when we upgraded to the new version of DT.

**Comment by dancesWithCycles** [comment]
Hi @leonardehrenfried ,
Thank you so much for your reply. Are you doing anything else then [stadtnavi](https://github.com/stadtnavi). I have the feeling you are more or less waiting to interact with contributors and I am almost always get a prompt reply to everything I am active in this repository. ;-) Appreciate!

Would you say this file should be part of the next branch? If so, shall I help to move it there?

Cheers!

**Comment by leonardehrenfried** [comment]
Thanks for being appreciative.

Besides stadtnavi I also work on other projects but I try to be as encouraging to potential contributors as I can. I'm glad that it shows.

Yes, I'd love to have this file on the next branch.

**Comment by dancesWithCycles** [comment]
You find the respective pull request in #758.
