### ISSUE TITLE
Some map icons are cropped when on a tile border

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#76]
Some map icons do not display correctly when they are on a tile border.

![Screenshot from 2020-02-26 10-21-30](https://user-images.githubusercontent.com/151346/75464004-df982000-5986-11ea-85ce-e24bb5894ddb.png)
![Screenshot from 2020-02-26 10-21-05](https://user-images.githubusercontent.com/151346/75464010-e0c94d00-5986-11ea-99d1-4d54c0f0e555.png)
![Screenshot from 2020-02-26 10-20-52](https://user-images.githubusercontent.com/151346/75464018-e1fa7a00-5986-11ea-9c25-71248aead1e4.png)

It is not entirely clear why that is but this is a ticket to collect observations and possible solutions.

**Comment by leonardehrenfried** [comment]
I took some time today to investigate and found out how these icons are drawn: each map tile is overlaid with a `<canvas>` element which is mostly transparent.

![Screenshot from 2020-02-27 17-27-14](https://user-images.githubusercontent.com/151346/75464215-2ab23300-5987-11ea-993d-5ee551c6a076.png)

When an icon overlaps a tile border it has to go on two tile canvas overlays. This mostly works but in some cases it does not. In the followin screenshot the canvas which should contain the left hand part of the icon is empty.

![Screenshot from 2020-02-27 17-26-30](https://user-images.githubusercontent.com/151346/75464307-4d444c00-5987-11ea-9de4-c6c9801b58c2.png)

Weirdly, sometimes this works:

![Screenshot from 2020-02-27 17-34-45](https://user-images.githubusercontent.com/151346/75464453-81b80800-5987-11ea-9d7e-ce249a0237e6.png)
![Screenshot from 2020-02-27 17-34-51](https://user-images.githubusercontent.com/151346/75464461-82e93500-5987-11ea-88cb-f56feb6811e0.png)

**Comment by hbruch** [comment]
All screenshots show icons clipped at the left or bottom. I assume a z-level issue where left/bottom background tiles have a higher z-level than the symbol canvas. If that‘s true, hiding neighbour-tiles would make the appear the complete symbol. Could you check this?

**Comment by hbruch** [comment]
In a comparable [leaflet issue](https://github.com/Leaflet/Leaflet.VectorGrid/issues/149), creating the vector tile with a buffer is described as possible workaround. Perhaps tessera/tilelive provides such an option.

**Comment by hbruch** [comment]
I'm not sure, at which step we need to increase the buffer. Could you please try, if increasing the geojsonvt parameter [buffer](https://github.com/mapbox/geojson-vt/blob/704094915146ff4aec12fafeb2b1fa5078352dfd/src/index.js#L14) makes any difference. 

Not sure, if this is really the right place, as the default for extent is defined as 4096 while the clipped tiles seem to have an extent of 256.

**Comment by leonardehrenfried** [comment]
I'm trying this: https://github.com/mfdz/tilelive-park-api/commit/df21fc3edad43be3f2aed7ea48b184d9be6a79b2

Total guess though.

**Comment by leonardehrenfried** [comment]
I took another stab at this with this commit: https://github.com/stadtnavi/tilelive-park-api/commit/3a25d1136750efd914baa3999472ac70b65413e1

It appears to have fixed the issue.

## Before
![Screenshot from 2020-10-29 11-48-26](https://user-images.githubusercontent.com/151346/97559819-36566d80-19de-11eb-8933-7fb820e16629.png)
## After
![Screenshot from 2020-10-29 11-48-29](https://user-images.githubusercontent.com/151346/97559815-35254080-19de-11eb-9b51-279d09b1a562.png)

I appears (but is unconfirmed) that there was a bug in geojson-vt.

**Comment by leonardehrenfried** [comment]
Now also fixed in production.

![Screenshot from 2020-10-29 12-56-23](https://user-images.githubusercontent.com/151346/97565242-2e9ac700-19e6-11eb-910e-a5c1bf036167.png)
