### ISSUE TITLE
Take bike-only charging station into account

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#766]
The following charging station https://landstadtmobil.de/ladestationen?lat=48.41251072575901&lng=9.534502029418947&name=ChargerCube+E-Bike+Ladestation+Biosph%C3%A4renzentrum+Auingen&stationId=3172

![Screenshot from 2021-09-10 16-56-06](https://user-images.githubusercontent.com/151346/132873881-89e8b74e-3d61-4b41-83d8-4bd0b4f5eba9.png)

is actually not a car charging one but just for e-bikes.

We want to show a different icon for these kinds of stations.

Acceptance criteria

- Create a new icon using the existing car charging one and putting the bike from this one https://leonard.io/stadtnavi/bikesharing.svg in place of the car.
- Check the property `cb` [here](https://github.com/stadtnavi/digitransit-ui/blob/72a8b8ae4cfeef78fd4d19d7414cc086d0e04209/app/component/map/tile-layer/ChargingStations.js#L85)
- `cb` stands for "capacity bikes" to indicate that a bike can be charged there
- if the property `c` (car capacity) is null or 0 and `cb` (bike capacity) exists, then please show the bike charging station icon.

**Comment by Beck-berry** [comment]
Just to clear things here, since I got confused:
`c` stands for car capacity
`ca` is the available capacity
`cb` means bike capacity
and `cu` represents the unknown capacity.
If ever I forget about it again, I'll remember this ticket! :D
