### ISSUE TITLE
No numbers shown for barrier-free parking

### ISSUE THREAD

**Issue by stadtnavimanager** [stadtnavi/digitransit-ui#787]
At least Altstadtgarage, Bronntor and Nufringer Tor say "of wheelchair-accessible parking spaces available" without showing numbers - Maybe a car park problem/ underground car park?

**Comment by hbruch** [comment]
Meanwhile, this has been fixed. Closing.


![Image](https://github.com/user-attachments/assets/e8254758-d069-452d-a658-64558a6e15a9)
