### ISSUE TITLE
Display CO2 emissions information for itineraries

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#820]
For each itinerary, stadtnavi should show the CO2 emissions per trip.

This functionality has been implemented by upstream already and should be backported to stadtnavi.

If code needs to be changed to get it working, consider bringing stadtnavi closer to upstream.

OTP on https://api.dev.stadtnavi.eu/ already has been configured to return the co2emissions.

The following commits introduced to core functionality to upstream digitransit (Note: the code might have been adapted in later commits, please check).

https://github.com/HSLdevcom/digitransit-ui/commit/92eb64df315167f9222bbeaf44e482273498d1de
https://github.com/HSLdevcom/digitransit-ui/commit/15a09fd5bd7ccd0cb789bc32557e37bff4a5bb89

**Comment by andreashelms** [comment]
@hbruch 
Do we only need this component from upstream?

<img width="444" alt="image" src="https://github.com/user-attachments/assets/12f27b46-4c7f-41c3-85c0-ec7637c50cb2">

Or also the compared emissions produced by a car?
<img width="437" alt="image" src="https://github.com/user-attachments/assets/8bb01099-4844-4f6b-b343-2a892832ae67">

**Comment by hbruch** [comment]
When is this component shown? and which content is linked there? We should add a link to an explaining text as well, IMHO an external page. @stadtnavimanager could you create a page in the stadtnavi CMS where we explain the calculations?

**Comment by andreashelms** [comment]
Here is an example. The component is shown at the bottom of the itinerary tab:
https://reittiopas.hsl.fi/reitti/V%C3%A4nrikki%20Stoolin%20katu%2010b%2C%20Helsinki%3A%3A60.17670743114979%2C24.926841259002686/Suvilahdenkatu%201%20B%2C%20Helsinki%3A%3A60.1870677971542%2C24.967203140258793/0?arriveBy=false&fromMap=origin&locale=en&time=1732015708.425

**Comment by stadtnavimanager** [comment]
> When is this component shown? and which content is linked there? We should add a link to an explaining text as well, IMHO an external page. @stadtnavimanager could you create a page in the stadtnavi CMS where we explain the calculations?

Here is the link to the page we can use: https://www.herrenberg.de/Mobilit%C3%A4t/CO2

**Comment by andreashelms** [comment]
Should I also display the information about CO2 in comparison to car like shown here?

<img width="437" alt="image" src="https://github.com/user-attachments/assets/8bb01099-4844-4f6b-b343-2a892832ae67">

**Comment by hbruch** [comment]
Yes, please. And instead of "This is how we reduce emissions" we should rather write "This is how we compare emissions", and link to https://www.herrenberg.de/Mobilit%C3%A4t/CO2 (link should be configurable via config). Thx

**Comment by stadtnavimanager** [comment]
Hi, I am not sure if the feedback is right in this issue. If not, pls let me know.

![Image](https://github.com/user-attachments/assets/77b57860-7d2a-4071-b932-184ad0d31888)

For the emissions of the RB14, the leaf is missing

And I realized, that for only food routes or only bicycle routes there are no emssions shown.

**Comment by hbruch** [comment]
The emissions of the RB are higher than for the S1. Only the best option (=lowest emissions) shows the leave.

**Comment by stadtnavimanager** [comment]
aaah that makes sense, of course. Thanks for the explanation!
