### ISSUE TITLE
Feature: Publish carpooling offers

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#86]
For now, it is possible to find carpool offers when searching for trips.

Next step shall be the publishing/management of carpool offers.

In this issue, we will sketch and discuss the needed UI interactions.
The backend should be a generic backend as developed currently by the ShareQuadrat project (REST interface, OpenID-Connect authentification.

Proposed interactions:
* Car legs get an additional button „Fahrgemeinschaft anbieten“/ „Offer carpool“
* This button opens a page where (as less as still tolerable) additional info may be supplied, like a radio button ‚Einmalig‘/‚Once‘ or „Regelmäßig“/„Regularly“ and a picker for all weekdays the offer should be published for
* Publishing will require a login/registration (still to be discussed)
* In the MainMenu, an action „Manage Carpool offers“, which opens a page listing all offers with an option to cancel them (bare minimum)

**Comment by leonardehrenfried** [comment]
This feature - apart from the OpenId auth - is implemented.

Can I close it, @hbruch?

We can open another one if we decide that we want the missing feature.
